package gov.nia.nrs.utils.codeutils;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DataSettingDo implements Serializable {
    /**
	 *
	 */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.Id
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.CodeId
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private String codeId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.CodeDataValue
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private String codeDataValue;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.CodeDataValueDesc
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private String codeDataValueDesc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.ActiveStatus
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private String activeStatus;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.ParentDataId
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private String parentDataId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.Comments
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.CreateUserId
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.CreateDate
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.MainUserId
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private String mainUserId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.MaintainProgramId
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private String maintainProgramId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.MaintainHost
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private String maintainHost;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.LastUpdateTime
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.Version
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private BigDecimal version;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.CodeDataValueDesc2
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private String codeDataValueDesc2;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.Flag
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.OrderList
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private Integer orderList;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.Filter1
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private String filter1;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.Filter2
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private String filter2;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column DataSetting.Filter3
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    private String filter3;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.Id
     *
     * @return the value of DataSetting.Id
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.Id
     *
     * @param id the value for DataSetting.Id
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.CodeId
     *
     * @return the value of DataSetting.CodeId
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public String getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.CodeId
     *
     * @param codeId the value for DataSetting.CodeId
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setCodeId(String codeId) {
        this.codeId = codeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.CodeDataValue
     *
     * @return the value of DataSetting.CodeDataValue
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public String getCodeDataValue() {
        return codeDataValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.CodeDataValue
     *
     * @param codeDataValue the value for DataSetting.CodeDataValue
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setCodeDataValue(String codeDataValue) {
        this.codeDataValue = codeDataValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.CodeDataValueDesc
     *
     * @return the value of DataSetting.CodeDataValueDesc
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public String getCodeDataValueDesc() {
        return codeDataValueDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.CodeDataValueDesc
     *
     * @param codeDataValueDesc the value for DataSetting.CodeDataValueDesc
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setCodeDataValueDesc(String codeDataValueDesc) {
        this.codeDataValueDesc = codeDataValueDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.ActiveStatus
     *
     * @return the value of DataSetting.ActiveStatus
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public String getActiveStatus() {
        return activeStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.ActiveStatus
     *
     * @param activeStatus the value for DataSetting.ActiveStatus
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setActiveStatus(String activeStatus) {
        this.activeStatus = activeStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.ParentDataId
     *
     * @return the value of DataSetting.ParentDataId
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public String getParentDataId() {
        return parentDataId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.ParentDataId
     *
     * @param parentDataId the value for DataSetting.ParentDataId
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setParentDataId(String parentDataId) {
        this.parentDataId = parentDataId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.Comments
     *
     * @return the value of DataSetting.Comments
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.Comments
     *
     * @param comments the value for DataSetting.Comments
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.CreateUserId
     *
     * @return the value of DataSetting.CreateUserId
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.CreateUserId
     *
     * @param createUserId the value for DataSetting.CreateUserId
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.CreateDate
     *
     * @return the value of DataSetting.CreateDate
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.CreateDate
     *
     * @param createDate the value for DataSetting.CreateDate
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.MainUserId
     *
     * @return the value of DataSetting.MainUserId
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public String getMainUserId() {
        return mainUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.MainUserId
     *
     * @param mainUserId the value for DataSetting.MainUserId
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.MaintainProgramId
     *
     * @return the value of DataSetting.MaintainProgramId
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public String getMaintainProgramId() {
        return maintainProgramId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.MaintainProgramId
     *
     * @param maintainProgramId the value for DataSetting.MaintainProgramId
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.MaintainHost
     *
     * @return the value of DataSetting.MaintainHost
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public String getMaintainHost() {
        return maintainHost;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.MaintainHost
     *
     * @param maintainHost the value for DataSetting.MaintainHost
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.LastUpdateTime
     *
     * @return the value of DataSetting.LastUpdateTime
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.LastUpdateTime
     *
     * @param lastUpdateTime the value for DataSetting.LastUpdateTime
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.Version
     *
     * @return the value of DataSetting.Version
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.Version
     *
     * @param version the value for DataSetting.Version
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setVersion(BigDecimal version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.CodeDataValueDesc2
     *
     * @return the value of DataSetting.CodeDataValueDesc2
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public String getCodeDataValueDesc2() {
        return codeDataValueDesc2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.CodeDataValueDesc2
     *
     * @param codeDataValueDesc2 the value for DataSetting.CodeDataValueDesc2
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setCodeDataValueDesc2(String codeDataValueDesc2) {
        this.codeDataValueDesc2 = codeDataValueDesc2;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.Flag
     *
     * @return the value of DataSetting.Flag
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.Flag
     *
     * @param flag the value for DataSetting.Flag
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.OrderList
     *
     * @return the value of DataSetting.OrderList
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public Integer getOrderList() {
        return orderList;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.OrderList
     *
     * @param orderList the value for DataSetting.OrderList
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setOrderList(Integer orderList) {
        this.orderList = orderList;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.Filter1
     *
     * @return the value of DataSetting.Filter1
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public String getFilter1() {
        return filter1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.Filter1
     *
     * @param filter1 the value for DataSetting.Filter1
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setFilter1(String filter1) {
        this.filter1 = filter1;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.Filter2
     *
     * @return the value of DataSetting.Filter2
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public String getFilter2() {
        return filter2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.Filter2
     *
     * @param filter2 the value for DataSetting.Filter2
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setFilter2(String filter2) {
        this.filter2 = filter2;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column DataSetting.Filter3
     *
     * @return the value of DataSetting.Filter3
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public String getFilter3() {
        return filter3;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column DataSetting.Filter3
     *
     * @param filter3 the value for DataSetting.Filter3
     *
     * @mbggenerated Thu Oct 18 19:17:39 CST 2012
     */
    public void setFilter3(String filter3) {
        this.filter3 = filter3;
    }
}
