package gov.nia.nrs.domain.iis;



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * ApplyCase generated by hbm2java
 */
@Entity
@Table(name="ApplyCase"
)
public class ApplyCase  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private String receiveNo;
    private Long version;
    private String preName;
    private String schoolName;
    private String reissueMark;
    private String visitName;
    private String visitIdNo;
    private String visitBirthDate;
    private String nationOversea;
    private Integer occupation;
    private String occupationDesc;
    private Integer position;
    private Integer education;
    private String educationDesc;
    private Integer marry;
    private Integer militaryClass;
    private Integer residentReason;
    private Integer studentType;
    private Integer overseaResident;
    private Integer attachNo;
    private Integer specialMark;
    private Integer photoNo;
    private Integer lossMark;
    private String lossDate;
    private Integer exitPostponeNo;
    private Integer entryPostponeNo;
    private Integer exchangePermitNo;
    private String applyType;
    private Long reason;
    private Integer takeaway;
    private Integer receiveBureau;
    private Integer printWayA;
    private Integer printWayB;
    private Integer permitNoCode;
    private Integer decideMark;
    private Integer mark1;
    private Integer mark2;
    private Integer mark3;
    private Integer mark4;
    private Integer mark5;
    private Integer mark6;
    private String firstReceiveNo;
    private String applyDate;
    private Integer fromTo;
    private String travelAgencyNo;
    private Integer bureauNo1;
    private String keyinUid;
    private Date keyinDate;
    private String checkUid;
    private Date checkDate;
    private Date updateDate;
    private String decideKeyinUid;
    private Date decideKeyinDate;
    private Date decideUpdateDate;
    private String decideDate;
    private String exitExpiryDate;
    private String entryExpiryDate;
    private String mailBackDate;
    private String teamOne;
    private String officialNoOne;
    private String team;
    private String officialNo;
    private Long summaryNo;
    private Long selfDefineNo;
    private Integer printNo;
    private Integer groupType;
    private Long groupNo;
    private Integer attachPosition;
    private String attachRemark;
    private String validResignDate1;
    private String validResignDate2;
    private String validResignExpiryDate1;
    private String validResignExpiryDate2;
    private String resignDate;
    private Integer resignNo;
    private String resignExitExpiryDate;
    private String resignEntryExpiryDate;
    private String resignPostponeDate;
    private String lastestExchangeDate;
    private String exitPostponeDate;
    private String entryPostponeDate;
    private Date lastUpdateTime;
    private String freeAreaMark;
    private String rejectOnFileDate;
    private String amark;
    private String passportNo;
    private String issueExpiryDate;
    private String apfNo;
    private String barcodeMark;
    private Integer exitExpNoDays;
    private String idNoDecideDate;
    private String takeAmpm;
    private String notSameone;
    private String vipmark;
    private Integer receiveType;
    private String nationalizeDate;
    private String lossExchangeEntryDate;
    private Integer receivePermitPlace;
    private String scanUid;
    private Date scanDate;
    private String photoCheckUid;
    private Date photoCheckDate;
    private String contactNameOfTaiwan;
    private String contactAddressOfTaiwan;
    private String contacTelNotOfTaiwan;
    private String contactIdNoOfTaiwan;
    private String contactBirthDateOfTaiwan;
    private String contactAgeOfTaiwan;
    private String contactTitleOfTaiwan;
    private String contactOccupationOfTaiwan;
    private String contactBirthPlaceOfTaiwan;
    private String examineTeam;
    private String resume;
    private Long procOrder;
    private String procType;
    private String examine1no;
    private String examine2no;
    private String currentStatus;
    private String paymentRemark;
    private String createUserId;
    private Date createDate;
    private String mainUserId;
    private String maintainProgramId;
    private String maintainHost;
    private String permitNoType;
    private String photoMark;
    private String applyTourType;
    private String meetingRelativeStayTimes;
    private String meetingLongStayTimes;
    private String englishNameMark;
    private String overseaRecvBureau;
    private String filler;
    private Date lastestEntryTime;
    private Integer lastestEntryPort;
    private String lastestEntryFlyNo;
    private Date lastestExitTime;
    private Integer lastestExitPort;
    private String lastestExitFlyNo;
    private Date revokeDate;
    private String notifyFlag;
    private Date notifyDate;
    private String deleteFlag;
    private String livingCity;
    private String createBy;
    private Date transferTime;
    private Long permitNoTypeYear;
    private String stayDuration;
    private String defaulteEntryDate;
    private String decideDate2;
    private String agencyName;
    private String agencyTel;
    private Long applyMethod;
    private String arcid;
    private String area;
    private String barCode;
    private String beginDecideDate;
    private String beginPermitDate;
    private String birthDate;
    private String caseNo;
    private String lossPostDate;
    private String notifyNo;
    private String chineseName;
    private String createDeptId;
    private Date createTime;
    private String englishName;
    private String receiveState;
    private Integer examinTimes;
    private String fatherBirthDate;
    private String fatherPersonId;
    private String firstApplyDate;
    private String dropOutStartDate;
    private String forceExitReason;
    private String foreignPassportNo;
    private String gender;
    private Date importTime;
    private String isDirectFlights;
    private String issueExpireDate;
    private String dropOutEndDate;
    private String maintainDeptId;
    private Date modifyDate;
    private String modifyUser;
    private String motherBirthDate;
    private String motherPersonId;
    private Long nextCycleYear;
    private String oldResidenceNo;
    private String overseasReceiveNo;
    private String paymentDate;
    private String personId;
    private String positionType;
    private String rcEndDate;
    private String rcReturnDept;
    private String rcReturnMark;
    private String rcStartDate;
    private Integer receiptAmt;
    private String receiptNo;
    private String cancelNotifyDate;
    private String receivableNo;
    private String cancelNotifyNo;
    private String reEntryRemark;
    private String applicantType;
    private String refundAccountName;
    private String refundAccountNo;
    private String refundAddress;
    private String refundFlag;
    private String refundTicketTitle;
    private String overseaReceiveBureau;
    private String intb02id;
    private String lossMarkDate;
    private String reportType;
    private String reserved;
    private String residenceStatus;
    private String revocationNo;
    private String stayMark;
    private String lossMarkUserId;
    private String selfReMark;
    private String sentTaiwanDate;
    private String sourceTable;
    private String stepStatus;
    private Long travelNoBranch;
    private String workAllowDate;
    private String workAllowDept;
    private String workAllowDocNo;
    private String workAllowEndDate;
    private String workAllowStartDate;
    private String contactMobile;
    private String contactName;
    private String contactTel;
    private String filmNo;
    private String fitLaw;
    private String invitedDept;
    private String reMark;
    private String studentKind;
    private Integer deliveWay;
    private String serviceOfficeCode;
    private String serviceOfficeName;
    private String serviceOfficeTel;
    private String etlflag;
    private Date ilApydtIltb03;
    private String importFileName;
    private Integer etlSeq;
    private String firstDecideDate;
    private Date writeBackTime;
    private String writeBackFlag;
    private Date writeFlagTime;
    private Long txnMark;
    private Date syncTime;
    private String reEntryExpiryDate;
    private String transToPermitFlag;

    public ApplyCase() {}

	
    public ApplyCase(String receiveNo) {
        this.receiveNo = receiveNo;
    }
    public ApplyCase(String receiveNo, String preName, String schoolName, String reissueMark, String visitName, String visitIdNo, String visitBirthDate, String nationOversea, Integer occupation, String occupationDesc, Integer position, Integer education, String educationDesc, Integer marry, Integer militaryClass, Integer residentReason, Integer studentType, Integer overseaResident, Integer attachNo, Integer specialMark, Integer photoNo, Integer lossMark, String lossDate, Integer exitPostponeNo, Integer entryPostponeNo, Integer exchangePermitNo, String applyType, Long reason, Integer takeaway, Integer receiveBureau, Integer printWayA, Integer printWayB, Integer permitNoCode, Integer decideMark, Integer mark1, Integer mark2, Integer mark3, Integer mark4, Integer mark5, Integer mark6, String firstReceiveNo, String applyDate, Integer fromTo, String travelAgencyNo, Integer bureauNo1, String keyinUid, Date keyinDate, String checkUid, Date checkDate, Date updateDate, String decideKeyinUid, Date decideKeyinDate, Date decideUpdateDate, String decideDate, String exitExpiryDate, String entryExpiryDate, String mailBackDate, String teamOne, String officialNoOne, String team, String officialNo, Long summaryNo, Long selfDefineNo, Integer printNo, Integer groupType, Long groupNo, Integer attachPosition, String attachRemark, String validResignDate1, String validResignDate2, String validResignExpiryDate1, String validResignExpiryDate2, String resignDate, Integer resignNo, String resignExitExpiryDate, String resignEntryExpiryDate, String resignPostponeDate, String lastestExchangeDate, String exitPostponeDate, String entryPostponeDate, Date lastUpdateTime, String freeAreaMark, String rejectOnFileDate, String amark, String passportNo, String issueExpiryDate, String apfNo, String barcodeMark, Integer exitExpNoDays, String idNoDecideDate, String takeAmpm, String notSameone, String vipmark, Integer receiveType, String nationalizeDate, String lossExchangeEntryDate, Integer receivePermitPlace, String scanUid, Date scanDate, String photoCheckUid, Date photoCheckDate, String contactNameOfTaiwan, String contactAddressOfTaiwan, String contacTelNotOfTaiwan, String contactIdNoOfTaiwan, String contactBirthDateOfTaiwan, String contactAgeOfTaiwan, String contactTitleOfTaiwan, String contactOccupationOfTaiwan, String contactBirthPlaceOfTaiwan, String examineTeam, String resume, Long procOrder, String procType, String examine1no, String examine2no, String currentStatus, String paymentRemark, String createUserId, Date createDate, String mainUserId, String maintainProgramId, String maintainHost, String permitNoType, String photoMark, String applyTourType, String meetingRelativeStayTimes, String meetingLongStayTimes, String englishNameMark, String overseaRecvBureau, String filler, Date lastestEntryTime, Integer lastestEntryPort, String lastestEntryFlyNo, Date lastestExitTime, Integer lastestExitPort, String lastestExitFlyNo, Date revokeDate, String notifyFlag, Date notifyDate, String deleteFlag, String livingCity, String createBy, Date transferTime, Long permitNoTypeYear, String stayDuration, String defaulteEntryDate, String decideDate2, String agencyName, String agencyTel, Long applyMethod, String arcid, String area, String barCode, String beginDecideDate, String beginPermitDate, String birthDate, String caseNo, String lossPostDate, String notifyNo, String chineseName, String createDeptId, Date createTime, String englishName, String receiveState, Integer examinTimes, String fatherBirthDate, String fatherPersonId, String firstApplyDate, String dropOutStartDate, String forceExitReason, String foreignPassportNo, String gender, Date importTime, String isDirectFlights, String issueExpireDate, String dropOutEndDate, String maintainDeptId, Date modifyDate, String modifyUser, String motherBirthDate, String motherPersonId, Long nextCycleYear, String oldResidenceNo, String overseasReceiveNo, String paymentDate, String personId, String positionType, String rcEndDate, String rcReturnDept, String rcReturnMark, String rcStartDate, Integer receiptAmt, String receiptNo, String cancelNotifyDate, String receivableNo, String cancelNotifyNo, String reEntryRemark, String applicantType, String refundAccountName, String refundAccountNo, String refundAddress, String refundFlag, String refundTicketTitle, String overseaReceiveBureau, String intb02id, String lossMarkDate, String reportType, String reserved, String residenceStatus, String revocationNo, String stayMark, String lossMarkUserId, String selfReMark, String sentTaiwanDate, String sourceTable, String stepStatus, Long travelNoBranch, String workAllowDate, String workAllowDept, String workAllowDocNo, String workAllowEndDate, String workAllowStartDate, String contactMobile, String contactName, String contactTel, String filmNo, String fitLaw, String invitedDept, String reMark, String studentKind, Integer deliveWay, String serviceOfficeCode, String serviceOfficeName, String serviceOfficeTel, String etlflag, Date ilApydtIltb03, String importFileName, Integer etlSeq, String firstDecideDate, Date writeBackTime, String writeBackFlag, Date writeFlagTime, Long txnMark, Date syncTime, String reEntryExpiryDate, String transToPermitFlag) {
        this.receiveNo = receiveNo;
        this.preName = preName;
        this.schoolName = schoolName;
        this.reissueMark = reissueMark;
        this.visitName = visitName;
        this.visitIdNo = visitIdNo;
        this.visitBirthDate = visitBirthDate;
        this.nationOversea = nationOversea;
        this.occupation = occupation;
        this.occupationDesc = occupationDesc;
        this.position = position;
        this.education = education;
        this.educationDesc = educationDesc;
        this.marry = marry;
        this.militaryClass = militaryClass;
        this.residentReason = residentReason;
        this.studentType = studentType;
        this.overseaResident = overseaResident;
        this.attachNo = attachNo;
        this.specialMark = specialMark;
        this.photoNo = photoNo;
        this.lossMark = lossMark;
        this.lossDate = lossDate;
        this.exitPostponeNo = exitPostponeNo;
        this.entryPostponeNo = entryPostponeNo;
        this.exchangePermitNo = exchangePermitNo;
        this.applyType = applyType;
        this.reason = reason;
        this.takeaway = takeaway;
        this.receiveBureau = receiveBureau;
        this.printWayA = printWayA;
        this.printWayB = printWayB;
        this.permitNoCode = permitNoCode;
        this.decideMark = decideMark;
        this.mark1 = mark1;
        this.mark2 = mark2;
        this.mark3 = mark3;
        this.mark4 = mark4;
        this.mark5 = mark5;
        this.mark6 = mark6;
        this.firstReceiveNo = firstReceiveNo;
        this.applyDate = applyDate;
        this.fromTo = fromTo;
        this.travelAgencyNo = travelAgencyNo;
        this.bureauNo1 = bureauNo1;
        this.keyinUid = keyinUid;
        this.keyinDate = keyinDate;
        this.checkUid = checkUid;
        this.checkDate = checkDate;
        this.updateDate = updateDate;
        this.decideKeyinUid = decideKeyinUid;
        this.decideKeyinDate = decideKeyinDate;
        this.decideUpdateDate = decideUpdateDate;
        this.decideDate = decideDate;
        this.exitExpiryDate = exitExpiryDate;
        this.entryExpiryDate = entryExpiryDate;
        this.mailBackDate = mailBackDate;
        this.teamOne = teamOne;
        this.officialNoOne = officialNoOne;
        this.team = team;
        this.officialNo = officialNo;
        this.summaryNo = summaryNo;
        this.selfDefineNo = selfDefineNo;
        this.printNo = printNo;
        this.groupType = groupType;
        this.groupNo = groupNo;
        this.attachPosition = attachPosition;
        this.attachRemark = attachRemark;
        this.validResignDate1 = validResignDate1;
        this.validResignDate2 = validResignDate2;
        this.validResignExpiryDate1 = validResignExpiryDate1;
        this.validResignExpiryDate2 = validResignExpiryDate2;
        this.resignDate = resignDate;
        this.resignNo = resignNo;
        this.resignExitExpiryDate = resignExitExpiryDate;
        this.resignEntryExpiryDate = resignEntryExpiryDate;
        this.resignPostponeDate = resignPostponeDate;
        this.lastestExchangeDate = lastestExchangeDate;
        this.exitPostponeDate = exitPostponeDate;
        this.entryPostponeDate = entryPostponeDate;
        this.lastUpdateTime = lastUpdateTime;
        this.freeAreaMark = freeAreaMark;
        this.rejectOnFileDate = rejectOnFileDate;
        this.amark = amark;
        this.passportNo = passportNo;
        this.issueExpiryDate = issueExpiryDate;
        this.apfNo = apfNo;
        this.barcodeMark = barcodeMark;
        this.exitExpNoDays = exitExpNoDays;
        this.idNoDecideDate = idNoDecideDate;
        this.takeAmpm = takeAmpm;
        this.notSameone = notSameone;
        this.vipmark = vipmark;
        this.receiveType = receiveType;
        this.nationalizeDate = nationalizeDate;
        this.lossExchangeEntryDate = lossExchangeEntryDate;
        this.receivePermitPlace = receivePermitPlace;
        this.scanUid = scanUid;
        this.scanDate = scanDate;
        this.photoCheckUid = photoCheckUid;
        this.photoCheckDate = photoCheckDate;
        this.contactNameOfTaiwan = contactNameOfTaiwan;
        this.contactAddressOfTaiwan = contactAddressOfTaiwan;
        this.contacTelNotOfTaiwan = contacTelNotOfTaiwan;
        this.contactIdNoOfTaiwan = contactIdNoOfTaiwan;
        this.contactBirthDateOfTaiwan = contactBirthDateOfTaiwan;
        this.contactAgeOfTaiwan = contactAgeOfTaiwan;
        this.contactTitleOfTaiwan = contactTitleOfTaiwan;
        this.contactOccupationOfTaiwan = contactOccupationOfTaiwan;
        this.contactBirthPlaceOfTaiwan = contactBirthPlaceOfTaiwan;
        this.examineTeam = examineTeam;
        this.resume = resume;
        this.procOrder = procOrder;
        this.procType = procType;
        this.examine1no = examine1no;
        this.examine2no = examine2no;
        this.currentStatus = currentStatus;
        this.paymentRemark = paymentRemark;
        this.createUserId = createUserId;
        this.createDate = createDate;
        this.mainUserId = mainUserId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.permitNoType = permitNoType;
        this.photoMark = photoMark;
        this.applyTourType = applyTourType;
        this.meetingRelativeStayTimes = meetingRelativeStayTimes;
        this.meetingLongStayTimes = meetingLongStayTimes;
        this.englishNameMark = englishNameMark;
        this.overseaRecvBureau = overseaRecvBureau;
        this.filler = filler;
        this.lastestEntryTime = lastestEntryTime;
        this.lastestEntryPort = lastestEntryPort;
        this.lastestEntryFlyNo = lastestEntryFlyNo;
        this.lastestExitTime = lastestExitTime;
        this.lastestExitPort = lastestExitPort;
        this.lastestExitFlyNo = lastestExitFlyNo;
        this.revokeDate = revokeDate;
        this.notifyFlag = notifyFlag;
        this.notifyDate = notifyDate;
        this.deleteFlag = deleteFlag;
        this.livingCity = livingCity;
        this.createBy = createBy;
        this.transferTime = transferTime;
        this.permitNoTypeYear = permitNoTypeYear;
        this.stayDuration = stayDuration;
        this.defaulteEntryDate = defaulteEntryDate;
        this.decideDate2 = decideDate2;
        this.agencyName = agencyName;
        this.agencyTel = agencyTel;
        this.applyMethod = applyMethod;
        this.arcid = arcid;
        this.area = area;
        this.barCode = barCode;
        this.beginDecideDate = beginDecideDate;
        this.beginPermitDate = beginPermitDate;
        this.birthDate = birthDate;
        this.caseNo = caseNo;
        this.lossPostDate = lossPostDate;
        this.notifyNo = notifyNo;
        this.chineseName = chineseName;
        this.createDeptId = createDeptId;
        this.createTime = createTime;
        this.englishName = englishName;
        this.receiveState = receiveState;
        this.examinTimes = examinTimes;
        this.fatherBirthDate = fatherBirthDate;
        this.fatherPersonId = fatherPersonId;
        this.firstApplyDate = firstApplyDate;
        this.dropOutStartDate = dropOutStartDate;
        this.forceExitReason = forceExitReason;
        this.foreignPassportNo = foreignPassportNo;
        this.gender = gender;
        this.importTime = importTime;
        this.isDirectFlights = isDirectFlights;
        this.issueExpireDate = issueExpireDate;
        this.dropOutEndDate = dropOutEndDate;
        this.maintainDeptId = maintainDeptId;
        this.modifyDate = modifyDate;
        this.modifyUser = modifyUser;
        this.motherBirthDate = motherBirthDate;
        this.motherPersonId = motherPersonId;
        this.nextCycleYear = nextCycleYear;
        this.oldResidenceNo = oldResidenceNo;
        this.overseasReceiveNo = overseasReceiveNo;
        this.paymentDate = paymentDate;
        this.personId = personId;
        this.positionType = positionType;
        this.rcEndDate = rcEndDate;
        this.rcReturnDept = rcReturnDept;
        this.rcReturnMark = rcReturnMark;
        this.rcStartDate = rcStartDate;
        this.receiptAmt = receiptAmt;
        this.receiptNo = receiptNo;
        this.cancelNotifyDate = cancelNotifyDate;
        this.receivableNo = receivableNo;
        this.cancelNotifyNo = cancelNotifyNo;
        this.reEntryRemark = reEntryRemark;
        this.applicantType = applicantType;
        this.refundAccountName = refundAccountName;
        this.refundAccountNo = refundAccountNo;
        this.refundAddress = refundAddress;
        this.refundFlag = refundFlag;
        this.refundTicketTitle = refundTicketTitle;
        this.overseaReceiveBureau = overseaReceiveBureau;
        this.intb02id = intb02id;
        this.lossMarkDate = lossMarkDate;
        this.reportType = reportType;
        this.reserved = reserved;
        this.residenceStatus = residenceStatus;
        this.revocationNo = revocationNo;
        this.stayMark = stayMark;
        this.lossMarkUserId = lossMarkUserId;
        this.selfReMark = selfReMark;
        this.sentTaiwanDate = sentTaiwanDate;
        this.sourceTable = sourceTable;
        this.stepStatus = stepStatus;
        this.travelNoBranch = travelNoBranch;
        this.workAllowDate = workAllowDate;
        this.workAllowDept = workAllowDept;
        this.workAllowDocNo = workAllowDocNo;
        this.workAllowEndDate = workAllowEndDate;
        this.workAllowStartDate = workAllowStartDate;
        this.contactMobile = contactMobile;
        this.contactName = contactName;
        this.contactTel = contactTel;
        this.filmNo = filmNo;
        this.fitLaw = fitLaw;
        this.invitedDept = invitedDept;
        this.reMark = reMark;
        this.studentKind = studentKind;
        this.deliveWay = deliveWay;
        this.serviceOfficeCode = serviceOfficeCode;
        this.serviceOfficeName = serviceOfficeName;
        this.serviceOfficeTel = serviceOfficeTel;
        this.etlflag = etlflag;
        this.ilApydtIltb03 = ilApydtIltb03;
        this.importFileName = importFileName;
        this.etlSeq = etlSeq;
        this.firstDecideDate = firstDecideDate;
        this.writeBackTime = writeBackTime;
        this.writeBackFlag = writeBackFlag;
        this.writeFlagTime = writeFlagTime;
        this.txnMark = txnMark;
        this.syncTime = syncTime;
        this.reEntryExpiryDate = reEntryExpiryDate;
        this.transToPermitFlag = transToPermitFlag;
    }
   
    @Id 

    
    @Column(name="ReceiveNo", unique=true, nullable=false, length=12)
    public String getReceiveNo() {
        return this.receiveNo;
    }
    
    public void setReceiveNo(String receiveNo) {
        this.receiveNo = receiveNo;
    }

    @Version
    @Column(name="Version", scale=0)
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

    
    @Column(name="PreName", length=80)
    public String getPreName() {
        return this.preName;
    }
    
    public void setPreName(String preName) {
        this.preName = preName;
    }

    
    @Column(name="SchoolName", length=60)
    public String getSchoolName() {
        return this.schoolName;
    }
    
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    
    @Column(name="ReissueMark", length=1)
    public String getReissueMark() {
        return this.reissueMark;
    }
    
    public void setReissueMark(String reissueMark) {
        this.reissueMark = reissueMark;
    }

    
    @Column(name="VisitName", length=80)
    public String getVisitName() {
        return this.visitName;
    }
    
    public void setVisitName(String visitName) {
        this.visitName = visitName;
    }

    
    @Column(name="VisitIdNo", length=10)
    public String getVisitIdNo() {
        return this.visitIdNo;
    }
    
    public void setVisitIdNo(String visitIdNo) {
        this.visitIdNo = visitIdNo;
    }

    
    @Column(name="VisitBirthDate", length=8)
    public String getVisitBirthDate() {
        return this.visitBirthDate;
    }
    
    public void setVisitBirthDate(String visitBirthDate) {
        this.visitBirthDate = visitBirthDate;
    }

    
    @Column(name="NationOversea", length=1)
    public String getNationOversea() {
        return this.nationOversea;
    }
    
    public void setNationOversea(String nationOversea) {
        this.nationOversea = nationOversea;
    }

    
    @Column(name="Occupation")
    public Integer getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(Integer occupation) {
        this.occupation = occupation;
    }

    
    @Column(name="OccupationDesc", length=80)
    public String getOccupationDesc() {
        return this.occupationDesc;
    }
    
    public void setOccupationDesc(String occupationDesc) {
        this.occupationDesc = occupationDesc;
    }

    
    @Column(name="Position")
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }

    
    @Column(name="Education")
    public Integer getEducation() {
        return this.education;
    }
    
    public void setEducation(Integer education) {
        this.education = education;
    }

    
    @Column(name="EducationDesc", length=80)
    public String getEducationDesc() {
        return this.educationDesc;
    }
    
    public void setEducationDesc(String educationDesc) {
        this.educationDesc = educationDesc;
    }

    
    @Column(name="Marry")
    public Integer getMarry() {
        return this.marry;
    }
    
    public void setMarry(Integer marry) {
        this.marry = marry;
    }

    
    @Column(name="MilitaryClass")
    public Integer getMilitaryClass() {
        return this.militaryClass;
    }
    
    public void setMilitaryClass(Integer militaryClass) {
        this.militaryClass = militaryClass;
    }

    
    @Column(name="ResidentReason")
    public Integer getResidentReason() {
        return this.residentReason;
    }
    
    public void setResidentReason(Integer residentReason) {
        this.residentReason = residentReason;
    }

    
    @Column(name="StudentType")
    public Integer getStudentType() {
        return this.studentType;
    }
    
    public void setStudentType(Integer studentType) {
        this.studentType = studentType;
    }

    
    @Column(name="OverseaResident")
    public Integer getOverseaResident() {
        return this.overseaResident;
    }
    
    public void setOverseaResident(Integer overseaResident) {
        this.overseaResident = overseaResident;
    }

    
    @Column(name="AttachNo")
    public Integer getAttachNo() {
        return this.attachNo;
    }
    
    public void setAttachNo(Integer attachNo) {
        this.attachNo = attachNo;
    }

    
    @Column(name="SpecialMark")
    public Integer getSpecialMark() {
        return this.specialMark;
    }
    
    public void setSpecialMark(Integer specialMark) {
        this.specialMark = specialMark;
    }

    
    @Column(name="PhotoNo")
    public Integer getPhotoNo() {
        return this.photoNo;
    }
    
    public void setPhotoNo(Integer photoNo) {
        this.photoNo = photoNo;
    }

    
    @Column(name="LossMark")
    public Integer getLossMark() {
        return this.lossMark;
    }
    
    public void setLossMark(Integer lossMark) {
        this.lossMark = lossMark;
    }

    
    @Column(name="LossDate", length=8)
    public String getLossDate() {
        return this.lossDate;
    }
    
    public void setLossDate(String lossDate) {
        this.lossDate = lossDate;
    }

    
    @Column(name="ExitPostponeNo")
    public Integer getExitPostponeNo() {
        return this.exitPostponeNo;
    }
    
    public void setExitPostponeNo(Integer exitPostponeNo) {
        this.exitPostponeNo = exitPostponeNo;
    }

    
    @Column(name="EntryPostponeNo")
    public Integer getEntryPostponeNo() {
        return this.entryPostponeNo;
    }
    
    public void setEntryPostponeNo(Integer entryPostponeNo) {
        this.entryPostponeNo = entryPostponeNo;
    }

    
    @Column(name="ExchangePermitNo")
    public Integer getExchangePermitNo() {
        return this.exchangePermitNo;
    }
    
    public void setExchangePermitNo(Integer exchangePermitNo) {
        this.exchangePermitNo = exchangePermitNo;
    }

    
    @Column(name="ApplyType", length=1)
    public String getApplyType() {
        return this.applyType;
    }
    
    public void setApplyType(String applyType) {
        this.applyType = applyType;
    }

    
    @Column(name="Reason")
    public Long getReason() {
        return this.reason;
    }
    
    public void setReason(Long reason) {
        this.reason = reason;
    }

    
    @Column(name="Takeaway")
    public Integer getTakeaway() {
        return this.takeaway;
    }
    
    public void setTakeaway(Integer takeaway) {
        this.takeaway = takeaway;
    }

    
    @Column(name="ReceiveBureau")
    public Integer getReceiveBureau() {
        return this.receiveBureau;
    }
    
    public void setReceiveBureau(Integer receiveBureau) {
        this.receiveBureau = receiveBureau;
    }

    
    @Column(name="PrintWayA")
    public Integer getPrintWayA() {
        return this.printWayA;
    }
    
    public void setPrintWayA(Integer printWayA) {
        this.printWayA = printWayA;
    }

    
    @Column(name="PrintWayB")
    public Integer getPrintWayB() {
        return this.printWayB;
    }
    
    public void setPrintWayB(Integer printWayB) {
        this.printWayB = printWayB;
    }

    
    @Column(name="PermitNoCode")
    public Integer getPermitNoCode() {
        return this.permitNoCode;
    }
    
    public void setPermitNoCode(Integer permitNoCode) {
        this.permitNoCode = permitNoCode;
    }

    
    @Column(name="DecideMark")
    public Integer getDecideMark() {
        return this.decideMark;
    }
    
    public void setDecideMark(Integer decideMark) {
        this.decideMark = decideMark;
    }

    
    @Column(name="Mark1")
    public Integer getMark1() {
        return this.mark1;
    }
    
    public void setMark1(Integer mark1) {
        this.mark1 = mark1;
    }

    
    @Column(name="Mark2")
    public Integer getMark2() {
        return this.mark2;
    }
    
    public void setMark2(Integer mark2) {
        this.mark2 = mark2;
    }

    
    @Column(name="Mark3")
    public Integer getMark3() {
        return this.mark3;
    }
    
    public void setMark3(Integer mark3) {
        this.mark3 = mark3;
    }

    
    @Column(name="Mark4")
    public Integer getMark4() {
        return this.mark4;
    }
    
    public void setMark4(Integer mark4) {
        this.mark4 = mark4;
    }

    
    @Column(name="Mark5")
    public Integer getMark5() {
        return this.mark5;
    }
    
    public void setMark5(Integer mark5) {
        this.mark5 = mark5;
    }

    
    @Column(name="Mark6")
    public Integer getMark6() {
        return this.mark6;
    }
    
    public void setMark6(Integer mark6) {
        this.mark6 = mark6;
    }

    
    @Column(name="FirstReceiveNo", length=12)
    public String getFirstReceiveNo() {
        return this.firstReceiveNo;
    }
    
    public void setFirstReceiveNo(String firstReceiveNo) {
        this.firstReceiveNo = firstReceiveNo;
    }

    
    @Column(name="ApplyDate", length=8)
    public String getApplyDate() {
        return this.applyDate;
    }
    
    public void setApplyDate(String applyDate) {
        this.applyDate = applyDate;
    }

    
    @Column(name="FromTo")
    public Integer getFromTo() {
        return this.fromTo;
    }
    
    public void setFromTo(Integer fromTo) {
        this.fromTo = fromTo;
    }

    
    @Column(name="TravelAgencyNo", length=6)
    public String getTravelAgencyNo() {
        return this.travelAgencyNo;
    }
    
    public void setTravelAgencyNo(String travelAgencyNo) {
        this.travelAgencyNo = travelAgencyNo;
    }

    
    @Column(name="BureauNo1")
    public Integer getBureauNo1() {
        return this.bureauNo1;
    }
    
    public void setBureauNo1(Integer bureauNo1) {
        this.bureauNo1 = bureauNo1;
    }

    
    @Column(name="KeyinUid", length=10)
    public String getKeyinUid() {
        return this.keyinUid;
    }
    
    public void setKeyinUid(String keyinUid) {
        this.keyinUid = keyinUid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="KeyinDate", length=23)
    public Date getKeyinDate() {
        return this.keyinDate;
    }
    
    public void setKeyinDate(Date keyinDate) {
        this.keyinDate = keyinDate;
    }

    
    @Column(name="CheckUid", length=10)
    public String getCheckUid() {
        return this.checkUid;
    }
    
    public void setCheckUid(String checkUid) {
        this.checkUid = checkUid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CheckDate", length=23)
    public Date getCheckDate() {
        return this.checkDate;
    }
    
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UpdateDate", length=23)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="DecideKeyinUid", length=10)
    public String getDecideKeyinUid() {
        return this.decideKeyinUid;
    }
    
    public void setDecideKeyinUid(String decideKeyinUid) {
        this.decideKeyinUid = decideKeyinUid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DecideKeyinDate", length=23)
    public Date getDecideKeyinDate() {
        return this.decideKeyinDate;
    }
    
    public void setDecideKeyinDate(Date decideKeyinDate) {
        this.decideKeyinDate = decideKeyinDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DecideUpdateDate", length=23)
    public Date getDecideUpdateDate() {
        return this.decideUpdateDate;
    }
    
    public void setDecideUpdateDate(Date decideUpdateDate) {
        this.decideUpdateDate = decideUpdateDate;
    }

    
    @Column(name="DecideDate", length=8)
    public String getDecideDate() {
        return this.decideDate;
    }
    
    public void setDecideDate(String decideDate) {
        this.decideDate = decideDate;
    }

    
    @Column(name="ExitExpiryDate", length=8)
    public String getExitExpiryDate() {
        return this.exitExpiryDate;
    }
    
    public void setExitExpiryDate(String exitExpiryDate) {
        this.exitExpiryDate = exitExpiryDate;
    }

    
    @Column(name="EntryExpiryDate", length=8)
    public String getEntryExpiryDate() {
        return this.entryExpiryDate;
    }
    
    public void setEntryExpiryDate(String entryExpiryDate) {
        this.entryExpiryDate = entryExpiryDate;
    }

    
    @Column(name="MailBackDate", length=8)
    public String getMailBackDate() {
        return this.mailBackDate;
    }
    
    public void setMailBackDate(String mailBackDate) {
        this.mailBackDate = mailBackDate;
    }

    
    @Column(name="TeamOne", length=2)
    public String getTeamOne() {
        return this.teamOne;
    }
    
    public void setTeamOne(String teamOne) {
        this.teamOne = teamOne;
    }

    
    @Column(name="OfficialNoOne", length=10)
    public String getOfficialNoOne() {
        return this.officialNoOne;
    }
    
    public void setOfficialNoOne(String officialNoOne) {
        this.officialNoOne = officialNoOne;
    }

    
    @Column(name="Team", length=2)
    public String getTeam() {
        return this.team;
    }
    
    public void setTeam(String team) {
        this.team = team;
    }

    
    @Column(name="OfficialNo", length=10)
    public String getOfficialNo() {
        return this.officialNo;
    }
    
    public void setOfficialNo(String officialNo) {
        this.officialNo = officialNo;
    }

    
    @Column(name="SummaryNo")
    public Long getSummaryNo() {
        return this.summaryNo;
    }
    
    public void setSummaryNo(Long summaryNo) {
        this.summaryNo = summaryNo;
    }

    
    @Column(name="SelfDefineNo")
    public Long getSelfDefineNo() {
        return this.selfDefineNo;
    }
    
    public void setSelfDefineNo(Long selfDefineNo) {
        this.selfDefineNo = selfDefineNo;
    }

    
    @Column(name="PrintNo")
    public Integer getPrintNo() {
        return this.printNo;
    }
    
    public void setPrintNo(Integer printNo) {
        this.printNo = printNo;
    }

    
    @Column(name="GroupType")
    public Integer getGroupType() {
        return this.groupType;
    }
    
    public void setGroupType(Integer groupType) {
        this.groupType = groupType;
    }

    
    @Column(name="GroupNo")
    public Long getGroupNo() {
        return this.groupNo;
    }
    
    public void setGroupNo(Long groupNo) {
        this.groupNo = groupNo;
    }

    
    @Column(name="AttachPosition")
    public Integer getAttachPosition() {
        return this.attachPosition;
    }
    
    public void setAttachPosition(Integer attachPosition) {
        this.attachPosition = attachPosition;
    }

    
    @Column(name="AttachRemark", length=12)
    public String getAttachRemark() {
        return this.attachRemark;
    }
    
    public void setAttachRemark(String attachRemark) {
        this.attachRemark = attachRemark;
    }

    
    @Column(name="ValidResignDate1", length=8)
    public String getValidResignDate1() {
        return this.validResignDate1;
    }
    
    public void setValidResignDate1(String validResignDate1) {
        this.validResignDate1 = validResignDate1;
    }

    
    @Column(name="ValidResignDate2", length=8)
    public String getValidResignDate2() {
        return this.validResignDate2;
    }
    
    public void setValidResignDate2(String validResignDate2) {
        this.validResignDate2 = validResignDate2;
    }

    
    @Column(name="ValidResignExpiryDate1", length=8)
    public String getValidResignExpiryDate1() {
        return this.validResignExpiryDate1;
    }
    
    public void setValidResignExpiryDate1(String validResignExpiryDate1) {
        this.validResignExpiryDate1 = validResignExpiryDate1;
    }

    
    @Column(name="ValidResignExpiryDate2", length=8)
    public String getValidResignExpiryDate2() {
        return this.validResignExpiryDate2;
    }
    
    public void setValidResignExpiryDate2(String validResignExpiryDate2) {
        this.validResignExpiryDate2 = validResignExpiryDate2;
    }

    
    @Column(name="ResignDate", length=8)
    public String getResignDate() {
        return this.resignDate;
    }
    
    public void setResignDate(String resignDate) {
        this.resignDate = resignDate;
    }

    
    @Column(name="ResignNo")
    public Integer getResignNo() {
        return this.resignNo;
    }
    
    public void setResignNo(Integer resignNo) {
        this.resignNo = resignNo;
    }

    
    @Column(name="ResignExitExpiryDate", length=8)
    public String getResignExitExpiryDate() {
        return this.resignExitExpiryDate;
    }
    
    public void setResignExitExpiryDate(String resignExitExpiryDate) {
        this.resignExitExpiryDate = resignExitExpiryDate;
    }

    
    @Column(name="ResignEntryExpiryDate", length=8)
    public String getResignEntryExpiryDate() {
        return this.resignEntryExpiryDate;
    }
    
    public void setResignEntryExpiryDate(String resignEntryExpiryDate) {
        this.resignEntryExpiryDate = resignEntryExpiryDate;
    }

    
    @Column(name="ResignPostponeDate", length=8)
    public String getResignPostponeDate() {
        return this.resignPostponeDate;
    }
    
    public void setResignPostponeDate(String resignPostponeDate) {
        this.resignPostponeDate = resignPostponeDate;
    }

    
    @Column(name="LastestExchangeDate", length=8)
    public String getLastestExchangeDate() {
        return this.lastestExchangeDate;
    }
    
    public void setLastestExchangeDate(String lastestExchangeDate) {
        this.lastestExchangeDate = lastestExchangeDate;
    }

    
    @Column(name="ExitPostponeDate", length=8)
    public String getExitPostponeDate() {
        return this.exitPostponeDate;
    }
    
    public void setExitPostponeDate(String exitPostponeDate) {
        this.exitPostponeDate = exitPostponeDate;
    }

    
    @Column(name="EntryPostponeDate", length=8)
    public String getEntryPostponeDate() {
        return this.entryPostponeDate;
    }
    
    public void setEntryPostponeDate(String entryPostponeDate) {
        this.entryPostponeDate = entryPostponeDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdateTime", length=23)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    
    @Column(name="FreeAreaMark", length=1)
    public String getFreeAreaMark() {
        return this.freeAreaMark;
    }
    
    public void setFreeAreaMark(String freeAreaMark) {
        this.freeAreaMark = freeAreaMark;
    }

    
    @Column(name="RejectOnFileDate", length=8)
    public String getRejectOnFileDate() {
        return this.rejectOnFileDate;
    }
    
    public void setRejectOnFileDate(String rejectOnFileDate) {
        this.rejectOnFileDate = rejectOnFileDate;
    }

    
    @Column(name="AMark", length=1)
    public String getAmark() {
        return this.amark;
    }
    
    public void setAmark(String amark) {
        this.amark = amark;
    }

    
    @Column(name="PassportNo", length=12)
    public String getPassportNo() {
        return this.passportNo;
    }
    
    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }

    
    @Column(name="IssueExpiryDate", length=8)
    public String getIssueExpiryDate() {
        return this.issueExpiryDate;
    }
    
    public void setIssueExpiryDate(String issueExpiryDate) {
        this.issueExpiryDate = issueExpiryDate;
    }

    
    @Column(name="ApfNo", length=10)
    public String getApfNo() {
        return this.apfNo;
    }
    
    public void setApfNo(String apfNo) {
        this.apfNo = apfNo;
    }

    
    @Column(name="BarcodeMark", length=1)
    public String getBarcodeMark() {
        return this.barcodeMark;
    }
    
    public void setBarcodeMark(String barcodeMark) {
        this.barcodeMark = barcodeMark;
    }

    
    @Column(name="ExitExpNoDays")
    public Integer getExitExpNoDays() {
        return this.exitExpNoDays;
    }
    
    public void setExitExpNoDays(Integer exitExpNoDays) {
        this.exitExpNoDays = exitExpNoDays;
    }

    
    @Column(name="IdNoDecideDate", length=8)
    public String getIdNoDecideDate() {
        return this.idNoDecideDate;
    }
    
    public void setIdNoDecideDate(String idNoDecideDate) {
        this.idNoDecideDate = idNoDecideDate;
    }

    
    @Column(name="TakeAMPM", length=1)
    public String getTakeAmpm() {
        return this.takeAmpm;
    }
    
    public void setTakeAmpm(String takeAmpm) {
        this.takeAmpm = takeAmpm;
    }

    
    @Column(name="NotSameone", length=1)
    public String getNotSameone() {
        return this.notSameone;
    }
    
    public void setNotSameone(String notSameone) {
        this.notSameone = notSameone;
    }

    
    @Column(name="VIPMark", length=1)
    public String getVipmark() {
        return this.vipmark;
    }
    
    public void setVipmark(String vipmark) {
        this.vipmark = vipmark;
    }

    
    @Column(name="ReceiveType")
    public Integer getReceiveType() {
        return this.receiveType;
    }
    
    public void setReceiveType(Integer receiveType) {
        this.receiveType = receiveType;
    }

    
    @Column(name="NationalizeDate", length=8)
    public String getNationalizeDate() {
        return this.nationalizeDate;
    }
    
    public void setNationalizeDate(String nationalizeDate) {
        this.nationalizeDate = nationalizeDate;
    }

    
    @Column(name="LossExchangeEntryDate", length=8)
    public String getLossExchangeEntryDate() {
        return this.lossExchangeEntryDate;
    }
    
    public void setLossExchangeEntryDate(String lossExchangeEntryDate) {
        this.lossExchangeEntryDate = lossExchangeEntryDate;
    }

    
    @Column(name="ReceivePermitPlace")
    public Integer getReceivePermitPlace() {
        return this.receivePermitPlace;
    }
    
    public void setReceivePermitPlace(Integer receivePermitPlace) {
        this.receivePermitPlace = receivePermitPlace;
    }

    
    @Column(name="ScanUid", length=10)
    public String getScanUid() {
        return this.scanUid;
    }
    
    public void setScanUid(String scanUid) {
        this.scanUid = scanUid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ScanDate", length=23)
    public Date getScanDate() {
        return this.scanDate;
    }
    
    public void setScanDate(Date scanDate) {
        this.scanDate = scanDate;
    }

    
    @Column(name="PhotoCheckUid", length=10)
    public String getPhotoCheckUid() {
        return this.photoCheckUid;
    }
    
    public void setPhotoCheckUid(String photoCheckUid) {
        this.photoCheckUid = photoCheckUid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PhotoCheckDate", length=23)
    public Date getPhotoCheckDate() {
        return this.photoCheckDate;
    }
    
    public void setPhotoCheckDate(Date photoCheckDate) {
        this.photoCheckDate = photoCheckDate;
    }

    
    @Column(name="ContactNameOfTaiwan", length=80)
    public String getContactNameOfTaiwan() {
        return this.contactNameOfTaiwan;
    }
    
    public void setContactNameOfTaiwan(String contactNameOfTaiwan) {
        this.contactNameOfTaiwan = contactNameOfTaiwan;
    }

    
    @Column(name="ContactAddressOfTaiwan", length=256)
    public String getContactAddressOfTaiwan() {
        return this.contactAddressOfTaiwan;
    }
    
    public void setContactAddressOfTaiwan(String contactAddressOfTaiwan) {
        this.contactAddressOfTaiwan = contactAddressOfTaiwan;
    }

    
    @Column(name="ContacTelNotOfTaiwan", length=15)
    public String getContacTelNotOfTaiwan() {
        return this.contacTelNotOfTaiwan;
    }
    
    public void setContacTelNotOfTaiwan(String contacTelNotOfTaiwan) {
        this.contacTelNotOfTaiwan = contacTelNotOfTaiwan;
    }

    
    @Column(name="ContactIdNoOfTaiwan", length=10)
    public String getContactIdNoOfTaiwan() {
        return this.contactIdNoOfTaiwan;
    }
    
    public void setContactIdNoOfTaiwan(String contactIdNoOfTaiwan) {
        this.contactIdNoOfTaiwan = contactIdNoOfTaiwan;
    }

    
    @Column(name="ContactBirthDateOfTaiwan", length=8)
    public String getContactBirthDateOfTaiwan() {
        return this.contactBirthDateOfTaiwan;
    }
    
    public void setContactBirthDateOfTaiwan(String contactBirthDateOfTaiwan) {
        this.contactBirthDateOfTaiwan = contactBirthDateOfTaiwan;
    }

    
    @Column(name="ContactAgeOfTaiwan", length=3)
    public String getContactAgeOfTaiwan() {
        return this.contactAgeOfTaiwan;
    }
    
    public void setContactAgeOfTaiwan(String contactAgeOfTaiwan) {
        this.contactAgeOfTaiwan = contactAgeOfTaiwan;
    }

    
    @Column(name="ContactTitleOfTaiwan", length=32)
    public String getContactTitleOfTaiwan() {
        return this.contactTitleOfTaiwan;
    }
    
    public void setContactTitleOfTaiwan(String contactTitleOfTaiwan) {
        this.contactTitleOfTaiwan = contactTitleOfTaiwan;
    }

    
    @Column(name="ContactOccupationOfTaiwan", length=32)
    public String getContactOccupationOfTaiwan() {
        return this.contactOccupationOfTaiwan;
    }
    
    public void setContactOccupationOfTaiwan(String contactOccupationOfTaiwan) {
        this.contactOccupationOfTaiwan = contactOccupationOfTaiwan;
    }

    
    @Column(name="ContactBirthPlaceOfTaiwan", length=32)
    public String getContactBirthPlaceOfTaiwan() {
        return this.contactBirthPlaceOfTaiwan;
    }
    
    public void setContactBirthPlaceOfTaiwan(String contactBirthPlaceOfTaiwan) {
        this.contactBirthPlaceOfTaiwan = contactBirthPlaceOfTaiwan;
    }

    
    @Column(name="ExamineTeam", length=2)
    public String getExamineTeam() {
        return this.examineTeam;
    }
    
    public void setExamineTeam(String examineTeam) {
        this.examineTeam = examineTeam;
    }

    
    @Column(name="Resume", length=80)
    public String getResume() {
        return this.resume;
    }
    
    public void setResume(String resume) {
        this.resume = resume;
    }

    
    @Column(name="ProcOrder")
    public Long getProcOrder() {
        return this.procOrder;
    }
    
    public void setProcOrder(Long procOrder) {
        this.procOrder = procOrder;
    }

    
    @Column(name="ProcType", length=1)
    public String getProcType() {
        return this.procType;
    }
    
    public void setProcType(String procType) {
        this.procType = procType;
    }

    
    @Column(name="Examine1No", length=10)
    public String getExamine1no() {
        return this.examine1no;
    }
    
    public void setExamine1no(String examine1no) {
        this.examine1no = examine1no;
    }

    
    @Column(name="Examine2No", length=10)
    public String getExamine2no() {
        return this.examine2no;
    }
    
    public void setExamine2no(String examine2no) {
        this.examine2no = examine2no;
    }

    
    @Column(name="CurrentStatus", length=2)
    public String getCurrentStatus() {
        return this.currentStatus;
    }
    
    public void setCurrentStatus(String currentStatus) {
        this.currentStatus = currentStatus;
    }

    
    @Column(name="PaymentRemark", length=1)
    public String getPaymentRemark() {
        return this.paymentRemark;
    }
    
    public void setPaymentRemark(String paymentRemark) {
        this.paymentRemark = paymentRemark;
    }

    
    @Column(name="CreateUserId", length=10)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDate", length=23)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="MainUserId", length=10)
    public String getMainUserId() {
        return this.mainUserId;
    }
    
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }

    
    @Column(name="MaintainProgramId", length=10)
    public String getMaintainProgramId() {
        return this.maintainProgramId;
    }
    
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    
    @Column(name="MaintainHost", length=24)
    public String getMaintainHost() {
        return this.maintainHost;
    }
    
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    
    @Column(name="PermitNoType", length=3)
    public String getPermitNoType() {
        return this.permitNoType;
    }
    
    public void setPermitNoType(String permitNoType) {
        this.permitNoType = permitNoType;
    }

    
    @Column(name="PhotoMark", length=1)
    public String getPhotoMark() {
        return this.photoMark;
    }
    
    public void setPhotoMark(String photoMark) {
        this.photoMark = photoMark;
    }

    
    @Column(name="ApplyTourType", length=1)
    public String getApplyTourType() {
        return this.applyTourType;
    }
    
    public void setApplyTourType(String applyTourType) {
        this.applyTourType = applyTourType;
    }

    
    @Column(name="MeetingRelativeStayTimes", length=4)
    public String getMeetingRelativeStayTimes() {
        return this.meetingRelativeStayTimes;
    }
    
    public void setMeetingRelativeStayTimes(String meetingRelativeStayTimes) {
        this.meetingRelativeStayTimes = meetingRelativeStayTimes;
    }

    
    @Column(name="MeetingLongStayTimes", length=4)
    public String getMeetingLongStayTimes() {
        return this.meetingLongStayTimes;
    }
    
    public void setMeetingLongStayTimes(String meetingLongStayTimes) {
        this.meetingLongStayTimes = meetingLongStayTimes;
    }

    
    @Column(name="EnglishNameMark", length=1)
    public String getEnglishNameMark() {
        return this.englishNameMark;
    }
    
    public void setEnglishNameMark(String englishNameMark) {
        this.englishNameMark = englishNameMark;
    }

    
    @Column(name="OverseaRecvBureau", length=3)
    public String getOverseaRecvBureau() {
        return this.overseaRecvBureau;
    }
    
    public void setOverseaRecvBureau(String overseaRecvBureau) {
        this.overseaRecvBureau = overseaRecvBureau;
    }

    
    @Column(name="Filler", length=33)
    public String getFiller() {
        return this.filler;
    }
    
    public void setFiller(String filler) {
        this.filler = filler;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastestEntryTime", length=23)
    public Date getLastestEntryTime() {
        return this.lastestEntryTime;
    }
    
    public void setLastestEntryTime(Date lastestEntryTime) {
        this.lastestEntryTime = lastestEntryTime;
    }

    
    @Column(name="LastestEntryPort")
    public Integer getLastestEntryPort() {
        return this.lastestEntryPort;
    }
    
    public void setLastestEntryPort(Integer lastestEntryPort) {
        this.lastestEntryPort = lastestEntryPort;
    }

    
    @Column(name="LastestEntryFlyNo", length=6)
    public String getLastestEntryFlyNo() {
        return this.lastestEntryFlyNo;
    }
    
    public void setLastestEntryFlyNo(String lastestEntryFlyNo) {
        this.lastestEntryFlyNo = lastestEntryFlyNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastestExitTime", length=23)
    public Date getLastestExitTime() {
        return this.lastestExitTime;
    }
    
    public void setLastestExitTime(Date lastestExitTime) {
        this.lastestExitTime = lastestExitTime;
    }

    
    @Column(name="LastestExitPort")
    public Integer getLastestExitPort() {
        return this.lastestExitPort;
    }
    
    public void setLastestExitPort(Integer lastestExitPort) {
        this.lastestExitPort = lastestExitPort;
    }

    
    @Column(name="LastestExitFlyNo", length=6)
    public String getLastestExitFlyNo() {
        return this.lastestExitFlyNo;
    }
    
    public void setLastestExitFlyNo(String lastestExitFlyNo) {
        this.lastestExitFlyNo = lastestExitFlyNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RevokeDate", length=23)
    public Date getRevokeDate() {
        return this.revokeDate;
    }
    
    public void setRevokeDate(Date revokeDate) {
        this.revokeDate = revokeDate;
    }

    
    @Column(name="NotifyFlag", length=1)
    public String getNotifyFlag() {
        return this.notifyFlag;
    }
    
    public void setNotifyFlag(String notifyFlag) {
        this.notifyFlag = notifyFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="NotifyDate", length=23)
    public Date getNotifyDate() {
        return this.notifyDate;
    }
    
    public void setNotifyDate(Date notifyDate) {
        this.notifyDate = notifyDate;
    }

    
    @Column(name="DeleteFlag", length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    
    @Column(name="LivingCity", length=4)
    public String getLivingCity() {
        return this.livingCity;
    }
    
    public void setLivingCity(String livingCity) {
        this.livingCity = livingCity;
    }

    
    @Column(name="CreateBy", length=6)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TransferTime", length=23)
    public Date getTransferTime() {
        return this.transferTime;
    }
    
    public void setTransferTime(Date transferTime) {
        this.transferTime = transferTime;
    }

    
    @Column(name="PermitNoTypeYear")
    public Long getPermitNoTypeYear() {
        return this.permitNoTypeYear;
    }
    
    public void setPermitNoTypeYear(Long permitNoTypeYear) {
        this.permitNoTypeYear = permitNoTypeYear;
    }

    
    @Column(name="StayDuration", length=3)
    public String getStayDuration() {
        return this.stayDuration;
    }
    
    public void setStayDuration(String stayDuration) {
        this.stayDuration = stayDuration;
    }

    
    @Column(name="DefaulteEntryDate", length=8)
    public String getDefaulteEntryDate() {
        return this.defaulteEntryDate;
    }
    
    public void setDefaulteEntryDate(String defaulteEntryDate) {
        this.defaulteEntryDate = defaulteEntryDate;
    }

    
    @Column(name="DecideDate2", length=8)
    public String getDecideDate2() {
        return this.decideDate2;
    }
    
    public void setDecideDate2(String decideDate2) {
        this.decideDate2 = decideDate2;
    }

    
    @Column(name="AgencyName", length=160)
    public String getAgencyName() {
        return this.agencyName;
    }
    
    public void setAgencyName(String agencyName) {
        this.agencyName = agencyName;
    }

    
    @Column(name="AgencyTel", length=15)
    public String getAgencyTel() {
        return this.agencyTel;
    }
    
    public void setAgencyTel(String agencyTel) {
        this.agencyTel = agencyTel;
    }

    
    @Column(name="ApplyMethod")
    public Long getApplyMethod() {
        return this.applyMethod;
    }
    
    public void setApplyMethod(Long applyMethod) {
        this.applyMethod = applyMethod;
    }

    
    @Column(name="ARCID", length=12)
    public String getArcid() {
        return this.arcid;
    }
    
    public void setArcid(String arcid) {
        this.arcid = arcid;
    }

    
    @Column(name="Area", length=2)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }

    
    @Column(name="BarCode", length=24)
    public String getBarCode() {
        return this.barCode;
    }
    
    public void setBarCode(String barCode) {
        this.barCode = barCode;
    }

    
    @Column(name="BeginDecideDate", length=8)
    public String getBeginDecideDate() {
        return this.beginDecideDate;
    }
    
    public void setBeginDecideDate(String beginDecideDate) {
        this.beginDecideDate = beginDecideDate;
    }

    
    @Column(name="BeginPermitDate", length=8)
    public String getBeginPermitDate() {
        return this.beginPermitDate;
    }
    
    public void setBeginPermitDate(String beginPermitDate) {
        this.beginPermitDate = beginPermitDate;
    }

    
    @Column(name="BirthDate", length=8)
    public String getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="CaseNo", length=10)
    public String getCaseNo() {
        return this.caseNo;
    }
    
    public void setCaseNo(String caseNo) {
        this.caseNo = caseNo;
    }

    
    @Column(name="LossPostDate", length=8)
    public String getLossPostDate() {
        return this.lossPostDate;
    }
    
    public void setLossPostDate(String lossPostDate) {
        this.lossPostDate = lossPostDate;
    }

    
    @Column(name="NotifyNo", length=10)
    public String getNotifyNo() {
        return this.notifyNo;
    }
    
    public void setNotifyNo(String notifyNo) {
        this.notifyNo = notifyNo;
    }

    
    @Column(name="ChineseName", length=80)
    public String getChineseName() {
        return this.chineseName;
    }
    
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    
    @Column(name="CreateDeptId", length=4)
    public String getCreateDeptId() {
        return this.createDeptId;
    }
    
    public void setCreateDeptId(String createDeptId) {
        this.createDeptId = createDeptId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateTime", length=23)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="EnglishName", length=50)
    public String getEnglishName() {
        return this.englishName;
    }
    
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    
    @Column(name="ReceiveState", length=1)
    public String getReceiveState() {
        return this.receiveState;
    }
    
    public void setReceiveState(String receiveState) {
        this.receiveState = receiveState;
    }

    
    @Column(name="ExaminTimes", precision=6, scale=0)
    public Integer getExaminTimes() {
        return this.examinTimes;
    }
    
    public void setExaminTimes(Integer examinTimes) {
        this.examinTimes = examinTimes;
    }

    
    @Column(name="FatherBirthDate", length=8)
    public String getFatherBirthDate() {
        return this.fatherBirthDate;
    }
    
    public void setFatherBirthDate(String fatherBirthDate) {
        this.fatherBirthDate = fatherBirthDate;
    }

    
    @Column(name="FatherPersonId", length=15)
    public String getFatherPersonId() {
        return this.fatherPersonId;
    }
    
    public void setFatherPersonId(String fatherPersonId) {
        this.fatherPersonId = fatherPersonId;
    }

    
    @Column(name="FirstApplyDate", length=8)
    public String getFirstApplyDate() {
        return this.firstApplyDate;
    }
    
    public void setFirstApplyDate(String firstApplyDate) {
        this.firstApplyDate = firstApplyDate;
    }

    
    @Column(name="DropOutStartDate", length=8)
    public String getDropOutStartDate() {
        return this.dropOutStartDate;
    }
    
    public void setDropOutStartDate(String dropOutStartDate) {
        this.dropOutStartDate = dropOutStartDate;
    }

    
    @Column(name="ForceExitReason", length=2)
    public String getForceExitReason() {
        return this.forceExitReason;
    }
    
    public void setForceExitReason(String forceExitReason) {
        this.forceExitReason = forceExitReason;
    }

    
    @Column(name="ForeignPassportNo", length=15)
    public String getForeignPassportNo() {
        return this.foreignPassportNo;
    }
    
    public void setForeignPassportNo(String foreignPassportNo) {
        this.foreignPassportNo = foreignPassportNo;
    }

    
    @Column(name="Gender", length=1)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ImportTime", length=23)
    public Date getImportTime() {
        return this.importTime;
    }
    
    public void setImportTime(Date importTime) {
        this.importTime = importTime;
    }

    
    @Column(name="IsDirectFlights", length=2)
    public String getIsDirectFlights() {
        return this.isDirectFlights;
    }
    
    public void setIsDirectFlights(String isDirectFlights) {
        this.isDirectFlights = isDirectFlights;
    }

    
    @Column(name="IssueExpireDate", length=8)
    public String getIssueExpireDate() {
        return this.issueExpireDate;
    }
    
    public void setIssueExpireDate(String issueExpireDate) {
        this.issueExpireDate = issueExpireDate;
    }

    
    @Column(name="DropOutEndDate", length=8)
    public String getDropOutEndDate() {
        return this.dropOutEndDate;
    }
    
    public void setDropOutEndDate(String dropOutEndDate) {
        this.dropOutEndDate = dropOutEndDate;
    }

    
    @Column(name="MaintainDeptId", length=4)
    public String getMaintainDeptId() {
        return this.maintainDeptId;
    }
    
    public void setMaintainDeptId(String maintainDeptId) {
        this.maintainDeptId = maintainDeptId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ModifyDate", length=23)
    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    
    @Column(name="ModifyUser", length=5)
    public String getModifyUser() {
        return this.modifyUser;
    }
    
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    
    @Column(name="MotherBirthDate", length=8)
    public String getMotherBirthDate() {
        return this.motherBirthDate;
    }
    
    public void setMotherBirthDate(String motherBirthDate) {
        this.motherBirthDate = motherBirthDate;
    }

    
    @Column(name="MotherPersonId", length=15)
    public String getMotherPersonId() {
        return this.motherPersonId;
    }
    
    public void setMotherPersonId(String motherPersonId) {
        this.motherPersonId = motherPersonId;
    }

    
    @Column(name="NextCycleYear")
    public Long getNextCycleYear() {
        return this.nextCycleYear;
    }
    
    public void setNextCycleYear(Long nextCycleYear) {
        this.nextCycleYear = nextCycleYear;
    }

    
    @Column(name="OldResidenceNo", length=10)
    public String getOldResidenceNo() {
        return this.oldResidenceNo;
    }
    
    public void setOldResidenceNo(String oldResidenceNo) {
        this.oldResidenceNo = oldResidenceNo;
    }

    
    @Column(name="OverseasReceiveNo", length=12)
    public String getOverseasReceiveNo() {
        return this.overseasReceiveNo;
    }
    
    public void setOverseasReceiveNo(String overseasReceiveNo) {
        this.overseasReceiveNo = overseasReceiveNo;
    }

    
    @Column(name="PaymentDate", length=8)
    public String getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(String paymentDate) {
        this.paymentDate = paymentDate;
    }

    
    @Column(name="PersonId", length=20)
    public String getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(String personId) {
        this.personId = personId;
    }

    
    @Column(name="PositionType", length=2)
    public String getPositionType() {
        return this.positionType;
    }
    
    public void setPositionType(String positionType) {
        this.positionType = positionType;
    }

    
    @Column(name="RcEndDate", length=8)
    public String getRcEndDate() {
        return this.rcEndDate;
    }
    
    public void setRcEndDate(String rcEndDate) {
        this.rcEndDate = rcEndDate;
    }

    
    @Column(name="RcReturnDept", length=4)
    public String getRcReturnDept() {
        return this.rcReturnDept;
    }
    
    public void setRcReturnDept(String rcReturnDept) {
        this.rcReturnDept = rcReturnDept;
    }

    
    @Column(name="RcReturnMark", length=1)
    public String getRcReturnMark() {
        return this.rcReturnMark;
    }
    
    public void setRcReturnMark(String rcReturnMark) {
        this.rcReturnMark = rcReturnMark;
    }

    
    @Column(name="RcStartDate", length=8)
    public String getRcStartDate() {
        return this.rcStartDate;
    }
    
    public void setRcStartDate(String rcStartDate) {
        this.rcStartDate = rcStartDate;
    }

    
    @Column(name="ReceiptAmt", precision=6, scale=0)
    public Integer getReceiptAmt() {
        return this.receiptAmt;
    }
    
    public void setReceiptAmt(Integer receiptAmt) {
        this.receiptAmt = receiptAmt;
    }

    
    @Column(name="ReceiptNo", length=13)
    public String getReceiptNo() {
        return this.receiptNo;
    }
    
    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo;
    }

    
    @Column(name="CancelNotifyDate", length=8)
    public String getCancelNotifyDate() {
        return this.cancelNotifyDate;
    }
    
    public void setCancelNotifyDate(String cancelNotifyDate) {
        this.cancelNotifyDate = cancelNotifyDate;
    }

    
    @Column(name="ReceivableNo", length=15)
    public String getReceivableNo() {
        return this.receivableNo;
    }
    
    public void setReceivableNo(String receivableNo) {
        this.receivableNo = receivableNo;
    }

    
    @Column(name="CancelNotifyNo", length=10)
    public String getCancelNotifyNo() {
        return this.cancelNotifyNo;
    }
    
    public void setCancelNotifyNo(String cancelNotifyNo) {
        this.cancelNotifyNo = cancelNotifyNo;
    }

    
    @Column(name="ReEntryRemark", length=40)
    public String getReEntryRemark() {
        return this.reEntryRemark;
    }
    
    public void setReEntryRemark(String reEntryRemark) {
        this.reEntryRemark = reEntryRemark;
    }

    
    @Column(name="ApplicantType", length=1)
    public String getApplicantType() {
        return this.applicantType;
    }
    
    public void setApplicantType(String applicantType) {
        this.applicantType = applicantType;
    }

    
    @Column(name="RefundAccountName", length=60)
    public String getRefundAccountName() {
        return this.refundAccountName;
    }
    
    public void setRefundAccountName(String refundAccountName) {
        this.refundAccountName = refundAccountName;
    }

    
    @Column(name="RefundAccountNo", length=20)
    public String getRefundAccountNo() {
        return this.refundAccountNo;
    }
    
    public void setRefundAccountNo(String refundAccountNo) {
        this.refundAccountNo = refundAccountNo;
    }

    
    @Column(name="RefundAddress", length=200)
    public String getRefundAddress() {
        return this.refundAddress;
    }
    
    public void setRefundAddress(String refundAddress) {
        this.refundAddress = refundAddress;
    }

    
    @Column(name="RefundFlag", length=1)
    public String getRefundFlag() {
        return this.refundFlag;
    }
    
    public void setRefundFlag(String refundFlag) {
        this.refundFlag = refundFlag;
    }

    
    @Column(name="RefundTicketTitle", length=60)
    public String getRefundTicketTitle() {
        return this.refundTicketTitle;
    }
    
    public void setRefundTicketTitle(String refundTicketTitle) {
        this.refundTicketTitle = refundTicketTitle;
    }

    
    @Column(name="OverseaReceiveBureau", length=3)
    public String getOverseaReceiveBureau() {
        return this.overseaReceiveBureau;
    }
    
    public void setOverseaReceiveBureau(String overseaReceiveBureau) {
        this.overseaReceiveBureau = overseaReceiveBureau;
    }

    
    @Column(name="INTB02ID", length=15)
    public String getIntb02id() {
        return this.intb02id;
    }
    
    public void setIntb02id(String intb02id) {
        this.intb02id = intb02id;
    }

    
    @Column(name="LossMarkDate", length=8)
    public String getLossMarkDate() {
        return this.lossMarkDate;
    }
    
    public void setLossMarkDate(String lossMarkDate) {
        this.lossMarkDate = lossMarkDate;
    }

    
    @Column(name="ReportType", length=1)
    public String getReportType() {
        return this.reportType;
    }
    
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    
    @Column(name="Reserved")
    public String getReserved() {
        return this.reserved;
    }
    
    public void setReserved(String reserved) {
        this.reserved = reserved;
    }

    
    @Column(name="ResidenceStatus", length=1)
    public String getResidenceStatus() {
        return this.residenceStatus;
    }
    
    public void setResidenceStatus(String residenceStatus) {
        this.residenceStatus = residenceStatus;
    }

    
    @Column(name="RevocationNo", length=100)
    public String getRevocationNo() {
        return this.revocationNo;
    }
    
    public void setRevocationNo(String revocationNo) {
        this.revocationNo = revocationNo;
    }

    
    @Column(name="StayMark", length=1)
    public String getStayMark() {
        return this.stayMark;
    }
    
    public void setStayMark(String stayMark) {
        this.stayMark = stayMark;
    }

    
    @Column(name="LossMarkUserId", length=10)
    public String getLossMarkUserId() {
        return this.lossMarkUserId;
    }
    
    public void setLossMarkUserId(String lossMarkUserId) {
        this.lossMarkUserId = lossMarkUserId;
    }

    
    @Column(name="SelfReMark", length=200)
    public String getSelfReMark() {
        return this.selfReMark;
    }
    
    public void setSelfReMark(String selfReMark) {
        this.selfReMark = selfReMark;
    }

    
    @Column(name="SentTaiwanDate", length=8)
    public String getSentTaiwanDate() {
        return this.sentTaiwanDate;
    }
    
    public void setSentTaiwanDate(String sentTaiwanDate) {
        this.sentTaiwanDate = sentTaiwanDate;
    }

    
    @Column(name="SourceTable", length=24)
    public String getSourceTable() {
        return this.sourceTable;
    }
    
    public void setSourceTable(String sourceTable) {
        this.sourceTable = sourceTable;
    }

    
    @Column(name="StepStatus", length=4)
    public String getStepStatus() {
        return this.stepStatus;
    }
    
    public void setStepStatus(String stepStatus) {
        this.stepStatus = stepStatus;
    }

    
    @Column(name="TravelNoBranch")
    public Long getTravelNoBranch() {
        return this.travelNoBranch;
    }
    
    public void setTravelNoBranch(Long travelNoBranch) {
        this.travelNoBranch = travelNoBranch;
    }

    
    @Column(name="WorkAllowDate", length=8)
    public String getWorkAllowDate() {
        return this.workAllowDate;
    }
    
    public void setWorkAllowDate(String workAllowDate) {
        this.workAllowDate = workAllowDate;
    }

    
    @Column(name="WorkAllowDept", length=4)
    public String getWorkAllowDept() {
        return this.workAllowDept;
    }
    
    public void setWorkAllowDept(String workAllowDept) {
        this.workAllowDept = workAllowDept;
    }

    
    @Column(name="WorkAllowDocNo", length=20)
    public String getWorkAllowDocNo() {
        return this.workAllowDocNo;
    }
    
    public void setWorkAllowDocNo(String workAllowDocNo) {
        this.workAllowDocNo = workAllowDocNo;
    }

    
    @Column(name="WorkAllowEndDate", length=8)
    public String getWorkAllowEndDate() {
        return this.workAllowEndDate;
    }
    
    public void setWorkAllowEndDate(String workAllowEndDate) {
        this.workAllowEndDate = workAllowEndDate;
    }

    
    @Column(name="WorkAllowStartDate", length=8)
    public String getWorkAllowStartDate() {
        return this.workAllowStartDate;
    }
    
    public void setWorkAllowStartDate(String workAllowStartDate) {
        this.workAllowStartDate = workAllowStartDate;
    }

    
    @Column(name="ContactMobile", length=20)
    public String getContactMobile() {
        return this.contactMobile;
    }
    
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile;
    }

    
    @Column(name="ContactName", length=24)
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    
    @Column(name="ContactTel", length=20)
    public String getContactTel() {
        return this.contactTel;
    }
    
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel;
    }

    
    @Column(name="FilmNo", length=10)
    public String getFilmNo() {
        return this.filmNo;
    }
    
    public void setFilmNo(String filmNo) {
        this.filmNo = filmNo;
    }

    
    @Column(name="FitLaw", length=1)
    public String getFitLaw() {
        return this.fitLaw;
    }
    
    public void setFitLaw(String fitLaw) {
        this.fitLaw = fitLaw;
    }

    
    @Column(name="InvitedDept", length=120)
    public String getInvitedDept() {
        return this.invitedDept;
    }
    
    public void setInvitedDept(String invitedDept) {
        this.invitedDept = invitedDept;
    }

    
    @Column(name="ReMark", length=2000)
    public String getReMark() {
        return this.reMark;
    }
    
    public void setReMark(String reMark) {
        this.reMark = reMark;
    }

    
    @Column(name="StudentKind", length=1)
    public String getStudentKind() {
        return this.studentKind;
    }
    
    public void setStudentKind(String studentKind) {
        this.studentKind = studentKind;
    }

    
    @Column(name="DeliveWay")
    public Integer getDeliveWay() {
        return this.deliveWay;
    }
    
    public void setDeliveWay(Integer deliveWay) {
        this.deliveWay = deliveWay;
    }

    
    @Column(name="ServiceOfficeCode", length=4)
    public String getServiceOfficeCode() {
        return this.serviceOfficeCode;
    }
    
    public void setServiceOfficeCode(String serviceOfficeCode) {
        this.serviceOfficeCode = serviceOfficeCode;
    }

    
    @Column(name="ServiceOfficeName", length=86)
    public String getServiceOfficeName() {
        return this.serviceOfficeName;
    }
    
    public void setServiceOfficeName(String serviceOfficeName) {
        this.serviceOfficeName = serviceOfficeName;
    }

    
    @Column(name="ServiceOfficeTel", length=15)
    public String getServiceOfficeTel() {
        return this.serviceOfficeTel;
    }
    
    public void setServiceOfficeTel(String serviceOfficeTel) {
        this.serviceOfficeTel = serviceOfficeTel;
    }

    
    @Column(name="ETLFlag", length=1)
    public String getEtlflag() {
        return this.etlflag;
    }
    
    public void setEtlflag(String etlflag) {
        this.etlflag = etlflag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="IL_APYDT_ILTB03", length=23)
    public Date getIlApydtIltb03() {
        return this.ilApydtIltb03;
    }
    
    public void setIlApydtIltb03(Date ilApydtIltb03) {
        this.ilApydtIltb03 = ilApydtIltb03;
    }

    
    @Column(name="ImportFileName", length=50)
    public String getImportFileName() {
        return this.importFileName;
    }
    
    public void setImportFileName(String importFileName) {
        this.importFileName = importFileName;
    }

    
    @Column(name="ETL_SEQ")
    public Integer getEtlSeq() {
        return this.etlSeq;
    }
    
    public void setEtlSeq(Integer etlSeq) {
        this.etlSeq = etlSeq;
    }

    
    @Column(name="FirstDecideDate", length=8)
    public String getFirstDecideDate() {
        return this.firstDecideDate;
    }
    
    public void setFirstDecideDate(String firstDecideDate) {
        this.firstDecideDate = firstDecideDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="WriteBackTime", length=23)
    public Date getWriteBackTime() {
        return this.writeBackTime;
    }
    
    public void setWriteBackTime(Date writeBackTime) {
        this.writeBackTime = writeBackTime;
    }

    
    @Column(name="WriteBackFlag", length=1)
    public String getWriteBackFlag() {
        return this.writeBackFlag;
    }
    
    public void setWriteBackFlag(String writeBackFlag) {
        this.writeBackFlag = writeBackFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="WriteFlagTime", length=23)
    public Date getWriteFlagTime() {
        return this.writeFlagTime;
    }
    
    public void setWriteFlagTime(Date writeFlagTime) {
        this.writeFlagTime = writeFlagTime;
    }

    
    @Column(name="TxnMark")
    public Long getTxnMark() {
        return this.txnMark;
    }
    
    public void setTxnMark(Long txnMark) {
        this.txnMark = txnMark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SyncTime", length=23)
    public Date getSyncTime() {
        return this.syncTime;
    }
    
    public void setSyncTime(Date syncTime) {
        this.syncTime = syncTime;
    }

    
    @Column(name="ReEntryExpiryDate", length=8)
    public String getReEntryExpiryDate() {
        return this.reEntryExpiryDate;
    }
    
    public void setReEntryExpiryDate(String reEntryExpiryDate) {
        this.reEntryExpiryDate = reEntryExpiryDate;
    }

    
    @Column(name="TransToPermitFlag", length=1)
    public String getTransToPermitFlag() {
        return this.transToPermitFlag;
    }
    
    public void setTransToPermitFlag(String transToPermitFlag) {
        this.transToPermitFlag = transToPermitFlag;
    }




}


