package gov.nia.nrs.domain.iis;



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApplyResident generated by hbm2java
 */
@Entity
@Table(name="ApplyResident"
)
public class ApplyResident  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private String receiveNo;
    private String foreignPassportNo;
    private String passNo;
    private String firstReceiveNo;
    private String applyDate;
    private String decideMark;
    private String mark1;
    private String mark2;
    private String mark3;
    private String mark4;
    private String mark5;
    private String mark6;
    private String decideDate;
    private String entryDate;
    private String updateDate;
    private String overseaResident;
    private String fromto;
    private String position;
    private String type;
    private String lawlessEntry;
    private String distributionType;
    private String distributionNo;
    private String entryModifyDate;
    private String addDocDate;
    private String lossOriginRemark;
    private String telNo;
    private String reserved;
    private Date establishTime;
    private Date importTime;
    private String deleteFlag;
    private String mainUserId;
    private String maintainProgramId;
    private String maintainHost;
    private Date lastUpdateTime;
    private String createDeptId;
    private Date createTime;
    private String createUserId;
    private Date last2updateTime;
    private String maintainDeptId;
    private String passportNo;
    private String reMark;
    private String etlflag;
    private String sourceTable;
    private String writeBackFlag;
    private Date writeBackTime;

    public ApplyResident() {}

	
    public ApplyResident(String receiveNo, String deleteFlag) {
        this.receiveNo = receiveNo;
        this.deleteFlag = deleteFlag;
    }
    public ApplyResident(String receiveNo, String foreignPassportNo, String passNo, String firstReceiveNo, String applyDate, String decideMark, String mark1, String mark2, String mark3, String mark4, String mark5, String mark6, String decideDate, String entryDate, String updateDate, String overseaResident, String fromto, String position, String type, String lawlessEntry, String distributionType, String distributionNo, String entryModifyDate, String addDocDate, String lossOriginRemark, String telNo, String reserved, Date establishTime, Date importTime, String deleteFlag, String mainUserId, String maintainProgramId, String maintainHost, Date lastUpdateTime, String createDeptId, Date createTime, String createUserId, Date last2updateTime, String maintainDeptId, String passportNo, String reMark, String etlflag, String sourceTable, String writeBackFlag, Date writeBackTime) {
        this.receiveNo = receiveNo;
        this.foreignPassportNo = foreignPassportNo;
        this.passNo = passNo;
        this.firstReceiveNo = firstReceiveNo;
        this.applyDate = applyDate;
        this.decideMark = decideMark;
        this.mark1 = mark1;
        this.mark2 = mark2;
        this.mark3 = mark3;
        this.mark4 = mark4;
        this.mark5 = mark5;
        this.mark6 = mark6;
        this.decideDate = decideDate;
        this.entryDate = entryDate;
        this.updateDate = updateDate;
        this.overseaResident = overseaResident;
        this.fromto = fromto;
        this.position = position;
        this.type = type;
        this.lawlessEntry = lawlessEntry;
        this.distributionType = distributionType;
        this.distributionNo = distributionNo;
        this.entryModifyDate = entryModifyDate;
        this.addDocDate = addDocDate;
        this.lossOriginRemark = lossOriginRemark;
        this.telNo = telNo;
        this.reserved = reserved;
        this.establishTime = establishTime;
        this.importTime = importTime;
        this.deleteFlag = deleteFlag;
        this.mainUserId = mainUserId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
        this.createDeptId = createDeptId;
        this.createTime = createTime;
        this.createUserId = createUserId;
        this.last2updateTime = last2updateTime;
        this.maintainDeptId = maintainDeptId;
        this.passportNo = passportNo;
        this.reMark = reMark;
        this.etlflag = etlflag;
        this.sourceTable = sourceTable;
        this.writeBackFlag = writeBackFlag;
        this.writeBackTime = writeBackTime;
    }
   
    @Id 

    
    @Column(name="ReceiveNo", unique=true, nullable=false, length=12)
    public String getReceiveNo() {
        return this.receiveNo;
    }
    
    public void setReceiveNo(String receiveNo) {
        this.receiveNo = receiveNo;
    }

    
    @Column(name="ForeignPassportNo", length=15)
    public String getForeignPassportNo() {
        return this.foreignPassportNo;
    }
    
    public void setForeignPassportNo(String foreignPassportNo) {
        this.foreignPassportNo = foreignPassportNo;
    }

    
    @Column(name="PassNo", length=15)
    public String getPassNo() {
        return this.passNo;
    }
    
    public void setPassNo(String passNo) {
        this.passNo = passNo;
    }

    
    @Column(name="FirstReceiveNo", length=12)
    public String getFirstReceiveNo() {
        return this.firstReceiveNo;
    }
    
    public void setFirstReceiveNo(String firstReceiveNo) {
        this.firstReceiveNo = firstReceiveNo;
    }

    
    @Column(name="ApplyDate", length=8)
    public String getApplyDate() {
        return this.applyDate;
    }
    
    public void setApplyDate(String applyDate) {
        this.applyDate = applyDate;
    }

    
    @Column(name="DecideMark", length=4)
    public String getDecideMark() {
        return this.decideMark;
    }
    
    public void setDecideMark(String decideMark) {
        this.decideMark = decideMark;
    }

    
    @Column(name="Mark1", length=4)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }

    
    @Column(name="Mark2", length=4)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }

    
    @Column(name="Mark3", length=4)
    public String getMark3() {
        return this.mark3;
    }
    
    public void setMark3(String mark3) {
        this.mark3 = mark3;
    }

    
    @Column(name="Mark4", length=4)
    public String getMark4() {
        return this.mark4;
    }
    
    public void setMark4(String mark4) {
        this.mark4 = mark4;
    }

    
    @Column(name="Mark5", length=4)
    public String getMark5() {
        return this.mark5;
    }
    
    public void setMark5(String mark5) {
        this.mark5 = mark5;
    }

    
    @Column(name="Mark6", length=4)
    public String getMark6() {
        return this.mark6;
    }
    
    public void setMark6(String mark6) {
        this.mark6 = mark6;
    }

    
    @Column(name="DecideDate", length=8)
    public String getDecideDate() {
        return this.decideDate;
    }
    
    public void setDecideDate(String decideDate) {
        this.decideDate = decideDate;
    }

    
    @Column(name="EntryDate", length=8)
    public String getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(String entryDate) {
        this.entryDate = entryDate;
    }

    
    @Column(name="UpdateDate", length=8)
    public String getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="OverseaResident", length=4)
    public String getOverseaResident() {
        return this.overseaResident;
    }
    
    public void setOverseaResident(String overseaResident) {
        this.overseaResident = overseaResident;
    }

    
    @Column(name="Fromto", length=4)
    public String getFromto() {
        return this.fromto;
    }
    
    public void setFromto(String fromto) {
        this.fromto = fromto;
    }

    
    @Column(name="Position", length=4)
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    
    @Column(name="Type", length=1)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="LawlessEntry", length=1)
    public String getLawlessEntry() {
        return this.lawlessEntry;
    }
    
    public void setLawlessEntry(String lawlessEntry) {
        this.lawlessEntry = lawlessEntry;
    }

    
    @Column(name="DistributionType", length=1)
    public String getDistributionType() {
        return this.distributionType;
    }
    
    public void setDistributionType(String distributionType) {
        this.distributionType = distributionType;
    }

    
    @Column(name="DistributionNo", length=9)
    public String getDistributionNo() {
        return this.distributionNo;
    }
    
    public void setDistributionNo(String distributionNo) {
        this.distributionNo = distributionNo;
    }

    
    @Column(name="EntryModifyDate", length=8)
    public String getEntryModifyDate() {
        return this.entryModifyDate;
    }
    
    public void setEntryModifyDate(String entryModifyDate) {
        this.entryModifyDate = entryModifyDate;
    }

    
    @Column(name="AddDocDate", length=8)
    public String getAddDocDate() {
        return this.addDocDate;
    }
    
    public void setAddDocDate(String addDocDate) {
        this.addDocDate = addDocDate;
    }

    
    @Column(name="LossOriginRemark", length=1)
    public String getLossOriginRemark() {
        return this.lossOriginRemark;
    }
    
    public void setLossOriginRemark(String lossOriginRemark) {
        this.lossOriginRemark = lossOriginRemark;
    }

    
    @Column(name="TelNo", length=20)
    public String getTelNo() {
        return this.telNo;
    }
    
    public void setTelNo(String telNo) {
        this.telNo = telNo;
    }

    
    @Column(name="Reserved", length=30)
    public String getReserved() {
        return this.reserved;
    }
    
    public void setReserved(String reserved) {
        this.reserved = reserved;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EstablishTime", length=23)
    public Date getEstablishTime() {
        return this.establishTime;
    }
    
    public void setEstablishTime(Date establishTime) {
        this.establishTime = establishTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ImportTime", length=23)
    public Date getImportTime() {
        return this.importTime;
    }
    
    public void setImportTime(Date importTime) {
        this.importTime = importTime;
    }

    
    @Column(name="DeleteFlag", nullable=false, length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    
    @Column(name="MainUserId", length=10)
    public String getMainUserId() {
        return this.mainUserId;
    }
    
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }

    
    @Column(name="MaintainProgramId", length=20)
    public String getMaintainProgramId() {
        return this.maintainProgramId;
    }
    
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    
    @Column(name="MaintainHost", length=25)
    public String getMaintainHost() {
        return this.maintainHost;
    }
    
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdateTime", length=23)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    
    @Column(name="CreateDeptId", length=4)
    public String getCreateDeptId() {
        return this.createDeptId;
    }
    
    public void setCreateDeptId(String createDeptId) {
        this.createDeptId = createDeptId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateTime", length=23)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="CreateUserId", length=10)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Last2updateTime", length=23)
    public Date getLast2updateTime() {
        return this.last2updateTime;
    }
    
    public void setLast2updateTime(Date last2updateTime) {
        this.last2updateTime = last2updateTime;
    }

    
    @Column(name="MaintainDeptId", length=4)
    public String getMaintainDeptId() {
        return this.maintainDeptId;
    }
    
    public void setMaintainDeptId(String maintainDeptId) {
        this.maintainDeptId = maintainDeptId;
    }

    
    @Column(name="PassportNo", length=15)
    public String getPassportNo() {
        return this.passportNo;
    }
    
    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }

    
    @Column(name="ReMark", length=500)
    public String getReMark() {
        return this.reMark;
    }
    
    public void setReMark(String reMark) {
        this.reMark = reMark;
    }

    
    @Column(name="ETLFlag", length=1)
    public String getEtlflag() {
        return this.etlflag;
    }
    
    public void setEtlflag(String etlflag) {
        this.etlflag = etlflag;
    }

    
    @Column(name="SourceTable", length=24)
    public String getSourceTable() {
        return this.sourceTable;
    }
    
    public void setSourceTable(String sourceTable) {
        this.sourceTable = sourceTable;
    }

    
    @Column(name="WriteBackFlag", length=1)
    public String getWriteBackFlag() {
        return this.writeBackFlag;
    }
    
    public void setWriteBackFlag(String writeBackFlag) {
        this.writeBackFlag = writeBackFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="WriteBackTime", length=23)
    public Date getWriteBackTime() {
        return this.writeBackTime;
    }
    
    public void setWriteBackTime(Date writeBackTime) {
        this.writeBackTime = writeBackTime;
    }




}


