package gov.nia.nrs.domain.iis;



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApplyRocid generated by hbm2java
 */
@Entity
@Table(name="ApplyRocid"
)
public class ApplyRocid  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private String residentIdNo;
    private String chineseName;
    private String birthDate;
    private String englishName;
    private String nation;
    private String passNo;
    private String firstReceiveNo;
    private String maintainDeptId;
    private Date lastUpdateTime;
    private String maintainHost;
    private String reserved;
    private String createUserId;
    private String createDeptId;
    private Date createTime;
    private String maintainProgramId;
    private String mainUserId;
    private String deleteFlag;
    private Date importTime;
    private String name0;
    private String name1;
    private String name2;
    private String sortEnglishName;
    private Integer positionCode;
    private String sourceTable;
    private Long txnMark;
    private Date syncTime;
    private Long etlSerialNo;
    private String etlflag;
    private String firstReceiveNo2;
    private String residentIdNo2;
    private Date writeBackTime;
    private String writeBackFlag;
    private String batchApplicantType;
    private Date batchTime;
    private String batchFirstApplicantType;
    private Date batchLastUpdateTime;
    private String batchLastestReceiveNo;
    private String eudcflag;

    public ApplyRocid() {}

	
    public ApplyRocid(String residentIdNo) {
        this.residentIdNo = residentIdNo;
    }
    public ApplyRocid(String residentIdNo, String chineseName, String birthDate, String englishName, String nation, String passNo, String firstReceiveNo, String maintainDeptId, Date lastUpdateTime, String maintainHost, String reserved, String createUserId, String createDeptId, Date createTime, String maintainProgramId, String mainUserId, String deleteFlag, Date importTime, String name0, String name1, String name2, String sortEnglishName, Integer positionCode, String sourceTable, Long txnMark, Date syncTime, Long etlSerialNo, String etlflag, String firstReceiveNo2, String residentIdNo2, Date writeBackTime, String writeBackFlag, String batchApplicantType, Date batchTime, String batchFirstApplicantType, Date batchLastUpdateTime, String batchLastestReceiveNo, String eudcflag) {
        this.residentIdNo = residentIdNo;
        this.chineseName = chineseName;
        this.birthDate = birthDate;
        this.englishName = englishName;
        this.nation = nation;
        this.passNo = passNo;
        this.firstReceiveNo = firstReceiveNo;
        this.maintainDeptId = maintainDeptId;
        this.lastUpdateTime = lastUpdateTime;
        this.maintainHost = maintainHost;
        this.reserved = reserved;
        this.createUserId = createUserId;
        this.createDeptId = createDeptId;
        this.createTime = createTime;
        this.maintainProgramId = maintainProgramId;
        this.mainUserId = mainUserId;
        this.deleteFlag = deleteFlag;
        this.importTime = importTime;
        this.name0 = name0;
        this.name1 = name1;
        this.name2 = name2;
        this.sortEnglishName = sortEnglishName;
        this.positionCode = positionCode;
        this.sourceTable = sourceTable;
        this.txnMark = txnMark;
        this.syncTime = syncTime;
        this.etlSerialNo = etlSerialNo;
        this.etlflag = etlflag;
        this.firstReceiveNo2 = firstReceiveNo2;
        this.residentIdNo2 = residentIdNo2;
        this.writeBackTime = writeBackTime;
        this.writeBackFlag = writeBackFlag;
        this.batchApplicantType = batchApplicantType;
        this.batchTime = batchTime;
        this.batchFirstApplicantType = batchFirstApplicantType;
        this.batchLastUpdateTime = batchLastUpdateTime;
        this.batchLastestReceiveNo = batchLastestReceiveNo;
        this.eudcflag = eudcflag;
    }
   
    @Id 

    
    @Column(name="ResidentIdNo", unique=true, nullable=false, length=10)
    public String getResidentIdNo() {
        return this.residentIdNo;
    }
    
    public void setResidentIdNo(String residentIdNo) {
        this.residentIdNo = residentIdNo;
    }

    
    @Column(name="ChineseName", length=80)
    public String getChineseName() {
        return this.chineseName;
    }
    
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    
    @Column(name="BirthDate", length=8)
    public String getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="EnglishName", length=50)
    public String getEnglishName() {
        return this.englishName;
    }
    
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    
    @Column(name="Nation", length=3)
    public String getNation() {
        return this.nation;
    }
    
    public void setNation(String nation) {
        this.nation = nation;
    }

    
    @Column(name="PassNo", length=15)
    public String getPassNo() {
        return this.passNo;
    }
    
    public void setPassNo(String passNo) {
        this.passNo = passNo;
    }

    
    @Column(name="FirstReceiveNo", length=12)
    public String getFirstReceiveNo() {
        return this.firstReceiveNo;
    }
    
    public void setFirstReceiveNo(String firstReceiveNo) {
        this.firstReceiveNo = firstReceiveNo;
    }

    
    @Column(name="MaintainDeptId", length=3)
    public String getMaintainDeptId() {
        return this.maintainDeptId;
    }
    
    public void setMaintainDeptId(String maintainDeptId) {
        this.maintainDeptId = maintainDeptId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdateTime", length=23)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    
    @Column(name="MaintainHost", length=24)
    public String getMaintainHost() {
        return this.maintainHost;
    }
    
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    
    @Column(name="Reserved", length=44)
    public String getReserved() {
        return this.reserved;
    }
    
    public void setReserved(String reserved) {
        this.reserved = reserved;
    }

    
    @Column(name="CreateUserId", length=10)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CreateDeptId", length=4)
    public String getCreateDeptId() {
        return this.createDeptId;
    }
    
    public void setCreateDeptId(String createDeptId) {
        this.createDeptId = createDeptId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateTime", length=23)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="MaintainProgramId", length=20)
    public String getMaintainProgramId() {
        return this.maintainProgramId;
    }
    
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    
    @Column(name="MainUserId", length=10)
    public String getMainUserId() {
        return this.mainUserId;
    }
    
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }

    
    @Column(name="DeleteFlag", length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ImportTime", length=23)
    public Date getImportTime() {
        return this.importTime;
    }
    
    public void setImportTime(Date importTime) {
        this.importTime = importTime;
    }

    
    @Column(name="Name0", length=68)
    public String getName0() {
        return this.name0;
    }
    
    public void setName0(String name0) {
        this.name0 = name0;
    }

    
    @Column(name="Name1", length=4)
    public String getName1() {
        return this.name1;
    }
    
    public void setName1(String name1) {
        this.name1 = name1;
    }

    
    @Column(name="Name2", length=8)
    public String getName2() {
        return this.name2;
    }
    
    public void setName2(String name2) {
        this.name2 = name2;
    }

    
    @Column(name="SortEnglishName", length=50)
    public String getSortEnglishName() {
        return this.sortEnglishName;
    }
    
    public void setSortEnglishName(String sortEnglishName) {
        this.sortEnglishName = sortEnglishName;
    }

    
    @Column(name="PositionCode")
    public Integer getPositionCode() {
        return this.positionCode;
    }
    
    public void setPositionCode(Integer positionCode) {
        this.positionCode = positionCode;
    }

    
    @Column(name="SourceTable", length=24)
    public String getSourceTable() {
        return this.sourceTable;
    }
    
    public void setSourceTable(String sourceTable) {
        this.sourceTable = sourceTable;
    }

    
    @Column(name="TxnMark")
    public Long getTxnMark() {
        return this.txnMark;
    }
    
    public void setTxnMark(Long txnMark) {
        this.txnMark = txnMark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SyncTime", length=23)
    public Date getSyncTime() {
        return this.syncTime;
    }
    
    public void setSyncTime(Date syncTime) {
        this.syncTime = syncTime;
    }

    
    @Column(name="ETL_SerialNo", precision=12, scale=0)
    public Long getEtlSerialNo() {
        return this.etlSerialNo;
    }
    
    public void setEtlSerialNo(Long etlSerialNo) {
        this.etlSerialNo = etlSerialNo;
    }

    
    @Column(name="ETLFlag", length=1)
    public String getEtlflag() {
        return this.etlflag;
    }
    
    public void setEtlflag(String etlflag) {
        this.etlflag = etlflag;
    }

    
    @Column(name="FirstReceiveNo2", length=12)
    public String getFirstReceiveNo2() {
        return this.firstReceiveNo2;
    }
    
    public void setFirstReceiveNo2(String firstReceiveNo2) {
        this.firstReceiveNo2 = firstReceiveNo2;
    }

    
    @Column(name="ResidentIdNo2", length=10)
    public String getResidentIdNo2() {
        return this.residentIdNo2;
    }
    
    public void setResidentIdNo2(String residentIdNo2) {
        this.residentIdNo2 = residentIdNo2;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="WriteBackTime", length=23)
    public Date getWriteBackTime() {
        return this.writeBackTime;
    }
    
    public void setWriteBackTime(Date writeBackTime) {
        this.writeBackTime = writeBackTime;
    }

    
    @Column(name="WriteBackFlag", length=1)
    public String getWriteBackFlag() {
        return this.writeBackFlag;
    }
    
    public void setWriteBackFlag(String writeBackFlag) {
        this.writeBackFlag = writeBackFlag;
    }

    
    @Column(name="BatchApplicantType", length=1)
    public String getBatchApplicantType() {
        return this.batchApplicantType;
    }
    
    public void setBatchApplicantType(String batchApplicantType) {
        this.batchApplicantType = batchApplicantType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BatchTime", length=23)
    public Date getBatchTime() {
        return this.batchTime;
    }
    
    public void setBatchTime(Date batchTime) {
        this.batchTime = batchTime;
    }

    
    @Column(name="BatchFirstApplicantType", length=1)
    public String getBatchFirstApplicantType() {
        return this.batchFirstApplicantType;
    }
    
    public void setBatchFirstApplicantType(String batchFirstApplicantType) {
        this.batchFirstApplicantType = batchFirstApplicantType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BatchLastUpdateTime", length=23)
    public Date getBatchLastUpdateTime() {
        return this.batchLastUpdateTime;
    }
    
    public void setBatchLastUpdateTime(Date batchLastUpdateTime) {
        this.batchLastUpdateTime = batchLastUpdateTime;
    }

    
    @Column(name="BatchLastestReceiveNo", length=12)
    public String getBatchLastestReceiveNo() {
        return this.batchLastestReceiveNo;
    }
    
    public void setBatchLastestReceiveNo(String batchLastestReceiveNo) {
        this.batchLastestReceiveNo = batchLastestReceiveNo;
    }

    
    @Column(name="EUDCFlag", length=1)
    public String getEudcflag() {
        return this.eudcflag;
    }
    
    public void setEudcflag(String eudcflag) {
        this.eudcflag = eudcflag;
    }




}


