package gov.nia.nrs.domain.iis;



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Applicant generated by hbm2java
 */
@Entity
@Table(name="Applicant"
)
public class Applicant  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private String firstReceiveNo;
    private Long version;
    private String passengerId;
    private String personId;
    private String gender;
    private Integer nativeCode;
    private Integer native1;
    private String native2;
    private Integer birthPlaceCode;
    private Integer birthPlace1;
    private String birthPlace2;
    private String chineseName;
    private String birthDate;
    private String englishName;
    private String foreignPassportNo;
    private String overseaIdNo;
    private String militaryNo;
    private String fatherName;
    private String motherName;
    private String loveName;
    private String passportNo;
    private Integer militaryClass;
    private Integer overseaResident;
    private Integer position;
    private Integer occupation;
    private Integer education;
    private Integer marry;
    private Integer residentMark;
    private Integer vipposition;
    private Integer mark;
    private String residentDate;
    private Integer exitEntryNo;
    private Integer residentSum;
    private Integer rank;
    private Integer twnMainland0;
    private Integer twnMainland1;
    private Integer twnMainland2;
    private Integer twnMainland3;
    private Integer twnMainland4;
    private Integer generalPermitNoYtd;
    private Integer psightNoYtd;
    private Integer lastestSightDays;
    private Long exitNoYtd;
    private Long entryNoYtd;
    private String exitDate;
    private String entryDate;
    private Long exitNo;
    private Integer entryNo;
    private String lastestFilmNo;
    private String nationOversea;
    private String lastestRejectStatus;
    private String controlMark;
    private Integer postNoA;
    private Integer postNoB;
    private String addrTypeA;
    private String addrTypeB;
    private String addrBmark;
    private String addr1a;
    private String addr2a;
    private String addr3a;
    private String addr4a;
    private String addr1b;
    private String addr2b;
    private String addr3b;
    private String addr4b;
    private Integer psightNoNext;
    private String lastestReceiveNo;
    private String mainlandIdNo;
    private String commie;
    private String militaryNumber;
    private String deadMark;
    private String militaryMark;
    private String notSameone;
    private String residentIdNo;
    private String marriedDate;
    private String createUserId;
    private Date createDate;
    private String mainUserId;
    private String maintainProgramId;
    private Date lastUpdateTime;
    private String maintainHost;
    private String reserved;
    private String deleteFlag;
    private String createBy;
    private String alleyA;
    private String alleyB;
    private String arcid;
    private String belongCity;
    private String belongDept;
    private String cityA;
    private String name2;
    private String createDeptId;
    private Date createTime;
    private String districtA;
    private String districtB;
    private String email;
    private String foreignSpouseMark;
    private Date importTime;
    private String jobTitle;
    private String laneA;
    private String laneB;
    private String maintainDeptId;
    private String mobile;
    private String multiCitizenMark;
    private String neighborhoodA;
    private String name1;
    private String numberA;
    private String name0;
    private String overseaAddress;
    private String overseaContact;
    private String overseaContactMobile;
    private String overseaContactTel;
    private String overseaTel;
    private String roadA;
    private String roadB;
    private String serviceOfficeCode;
    private String serviceOfficeName;
    private String serviceOfficeSname;
    private String serviceOfficeTel;
    private String sourceTable;
    private String telA;
    private String telB;
    private String townshipA;
    private String townshipB;
    private String transferMark;
    private String villageA;
    private String villageB;
    private String zipCodeA;
    private String zipCodeB;
    private String applicantType;
    private String fatherBirthDate;
    private String fatherMark;
    private String fatherPersonId;
    private String loveMark;
    private String motherBirthDate;
    private String motherMark;
    private String motherPersonId;
    private String reMark;
    private String etlflag;
    private Long txnMark;
    private Date syncTime;
    private String sortEnglishName;
    private String writeBackFlag;
    private Date writeBackTime;
    private Date entryInspectTime;
    private Date exitInspectTime;

    public Applicant() {}

	
    public Applicant(String firstReceiveNo) {
        this.firstReceiveNo = firstReceiveNo;
    }
    public Applicant(String firstReceiveNo, String passengerId, String personId, String gender, Integer nativeCode, Integer native1, String native2, Integer birthPlaceCode, Integer birthPlace1, String birthPlace2, String chineseName, String birthDate, String englishName, String foreignPassportNo, String overseaIdNo, String militaryNo, String fatherName, String motherName, String loveName, String passportNo, Integer militaryClass, Integer overseaResident, Integer position, Integer occupation, Integer education, Integer marry, Integer residentMark, Integer vipposition, Integer mark, String residentDate, Integer exitEntryNo, Integer residentSum, Integer rank, Integer twnMainland0, Integer twnMainland1, Integer twnMainland2, Integer twnMainland3, Integer twnMainland4, Integer generalPermitNoYtd, Integer psightNoYtd, Integer lastestSightDays, Long exitNoYtd, Long entryNoYtd, String exitDate, String entryDate, Long exitNo, Integer entryNo, String lastestFilmNo, String nationOversea, String lastestRejectStatus, String controlMark, Integer postNoA, Integer postNoB, String addrTypeA, String addrTypeB, String addrBmark, String addr1a, String addr2a, String addr3a, String addr4a, String addr1b, String addr2b, String addr3b, String addr4b, Integer psightNoNext, String lastestReceiveNo, String mainlandIdNo, String commie, String militaryNumber, String deadMark, String militaryMark, String notSameone, String residentIdNo, String marriedDate, String createUserId, Date createDate, String mainUserId, String maintainProgramId, Date lastUpdateTime, String maintainHost, String reserved, String deleteFlag, String createBy, String alleyA, String alleyB, String arcid, String belongCity, String belongDept, String cityA, String name2, String createDeptId, Date createTime, String districtA, String districtB, String email, String foreignSpouseMark, Date importTime, String jobTitle, String laneA, String laneB, String maintainDeptId, String mobile, String multiCitizenMark, String neighborhoodA, String name1, String numberA, String name0, String overseaAddress, String overseaContact, String overseaContactMobile, String overseaContactTel, String overseaTel, String roadA, String roadB, String serviceOfficeCode, String serviceOfficeName, String serviceOfficeSname, String serviceOfficeTel, String sourceTable, String telA, String telB, String townshipA, String townshipB, String transferMark, String villageA, String villageB, String zipCodeA, String zipCodeB, String applicantType, String fatherBirthDate, String fatherMark, String fatherPersonId, String loveMark, String motherBirthDate, String motherMark, String motherPersonId, String reMark, String etlflag, Long txnMark, Date syncTime, String sortEnglishName, String writeBackFlag, Date writeBackTime, Date entryInspectTime, Date exitInspectTime) {
        this.firstReceiveNo = firstReceiveNo;
        this.passengerId = passengerId;
        this.personId = personId;
        this.gender = gender;
        this.nativeCode = nativeCode;
        this.native1 = native1;
        this.native2 = native2;
        this.birthPlaceCode = birthPlaceCode;
        this.birthPlace1 = birthPlace1;
        this.birthPlace2 = birthPlace2;
        this.chineseName = chineseName;
        this.birthDate = birthDate;
        this.englishName = englishName;
        this.foreignPassportNo = foreignPassportNo;
        this.overseaIdNo = overseaIdNo;
        this.militaryNo = militaryNo;
        this.fatherName = fatherName;
        this.motherName = motherName;
        this.loveName = loveName;
        this.passportNo = passportNo;
        this.militaryClass = militaryClass;
        this.overseaResident = overseaResident;
        this.position = position;
        this.occupation = occupation;
        this.education = education;
        this.marry = marry;
        this.residentMark = residentMark;
        this.vipposition = vipposition;
        this.mark = mark;
        this.residentDate = residentDate;
        this.exitEntryNo = exitEntryNo;
        this.residentSum = residentSum;
        this.rank = rank;
        this.twnMainland0 = twnMainland0;
        this.twnMainland1 = twnMainland1;
        this.twnMainland2 = twnMainland2;
        this.twnMainland3 = twnMainland3;
        this.twnMainland4 = twnMainland4;
        this.generalPermitNoYtd = generalPermitNoYtd;
        this.psightNoYtd = psightNoYtd;
        this.lastestSightDays = lastestSightDays;
        this.exitNoYtd = exitNoYtd;
        this.entryNoYtd = entryNoYtd;
        this.exitDate = exitDate;
        this.entryDate = entryDate;
        this.exitNo = exitNo;
        this.entryNo = entryNo;
        this.lastestFilmNo = lastestFilmNo;
        this.nationOversea = nationOversea;
        this.lastestRejectStatus = lastestRejectStatus;
        this.controlMark = controlMark;
        this.postNoA = postNoA;
        this.postNoB = postNoB;
        this.addrTypeA = addrTypeA;
        this.addrTypeB = addrTypeB;
        this.addrBmark = addrBmark;
        this.addr1a = addr1a;
        this.addr2a = addr2a;
        this.addr3a = addr3a;
        this.addr4a = addr4a;
        this.addr1b = addr1b;
        this.addr2b = addr2b;
        this.addr3b = addr3b;
        this.addr4b = addr4b;
        this.psightNoNext = psightNoNext;
        this.lastestReceiveNo = lastestReceiveNo;
        this.mainlandIdNo = mainlandIdNo;
        this.commie = commie;
        this.militaryNumber = militaryNumber;
        this.deadMark = deadMark;
        this.militaryMark = militaryMark;
        this.notSameone = notSameone;
        this.residentIdNo = residentIdNo;
        this.marriedDate = marriedDate;
        this.createUserId = createUserId;
        this.createDate = createDate;
        this.mainUserId = mainUserId;
        this.maintainProgramId = maintainProgramId;
        this.lastUpdateTime = lastUpdateTime;
        this.maintainHost = maintainHost;
        this.reserved = reserved;
        this.deleteFlag = deleteFlag;
        this.createBy = createBy;
        this.alleyA = alleyA;
        this.alleyB = alleyB;
        this.arcid = arcid;
        this.belongCity = belongCity;
        this.belongDept = belongDept;
        this.cityA = cityA;
        this.name2 = name2;
        this.createDeptId = createDeptId;
        this.createTime = createTime;
        this.districtA = districtA;
        this.districtB = districtB;
        this.email = email;
        this.foreignSpouseMark = foreignSpouseMark;
        this.importTime = importTime;
        this.jobTitle = jobTitle;
        this.laneA = laneA;
        this.laneB = laneB;
        this.maintainDeptId = maintainDeptId;
        this.mobile = mobile;
        this.multiCitizenMark = multiCitizenMark;
        this.neighborhoodA = neighborhoodA;
        this.name1 = name1;
        this.numberA = numberA;
        this.name0 = name0;
        this.overseaAddress = overseaAddress;
        this.overseaContact = overseaContact;
        this.overseaContactMobile = overseaContactMobile;
        this.overseaContactTel = overseaContactTel;
        this.overseaTel = overseaTel;
        this.roadA = roadA;
        this.roadB = roadB;
        this.serviceOfficeCode = serviceOfficeCode;
        this.serviceOfficeName = serviceOfficeName;
        this.serviceOfficeSname = serviceOfficeSname;
        this.serviceOfficeTel = serviceOfficeTel;
        this.sourceTable = sourceTable;
        this.telA = telA;
        this.telB = telB;
        this.townshipA = townshipA;
        this.townshipB = townshipB;
        this.transferMark = transferMark;
        this.villageA = villageA;
        this.villageB = villageB;
        this.zipCodeA = zipCodeA;
        this.zipCodeB = zipCodeB;
        this.applicantType = applicantType;
        this.fatherBirthDate = fatherBirthDate;
        this.fatherMark = fatherMark;
        this.fatherPersonId = fatherPersonId;
        this.loveMark = loveMark;
        this.motherBirthDate = motherBirthDate;
        this.motherMark = motherMark;
        this.motherPersonId = motherPersonId;
        this.reMark = reMark;
        this.etlflag = etlflag;
        this.txnMark = txnMark;
        this.syncTime = syncTime;
        this.sortEnglishName = sortEnglishName;
        this.writeBackFlag = writeBackFlag;
        this.writeBackTime = writeBackTime;
        this.entryInspectTime = entryInspectTime;
        this.exitInspectTime = exitInspectTime;
    }
   
    @Id 

    
    @Column(name="FirstReceiveNo", unique=true, nullable=false, length=12)
    public String getFirstReceiveNo() {
        return this.firstReceiveNo;
    }
    
    public void setFirstReceiveNo(String firstReceiveNo) {
        this.firstReceiveNo = firstReceiveNo;
    }

    @Version
    @Column(name="Version", scale=0)
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

    
    @Column(name="PassengerId", length=10)
    public String getPassengerId() {
        return this.passengerId;
    }
    
    public void setPassengerId(String passengerId) {
        this.passengerId = passengerId;
    }

    
    @Column(name="PersonId", length=10)
    public String getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(String personId) {
        this.personId = personId;
    }

    
    @Column(name="Gender", length=1)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="NativeCode")
    public Integer getNativeCode() {
        return this.nativeCode;
    }
    
    public void setNativeCode(Integer nativeCode) {
        this.nativeCode = nativeCode;
    }

    
    @Column(name="Native1")
    public Integer getNative1() {
        return this.native1;
    }
    
    public void setNative1(Integer native1) {
        this.native1 = native1;
    }

    
    @Column(name="Native2", length=16)
    public String getNative2() {
        return this.native2;
    }
    
    public void setNative2(String native2) {
        this.native2 = native2;
    }

    
    @Column(name="BirthPlaceCode")
    public Integer getBirthPlaceCode() {
        return this.birthPlaceCode;
    }
    
    public void setBirthPlaceCode(Integer birthPlaceCode) {
        this.birthPlaceCode = birthPlaceCode;
    }

    
    @Column(name="BirthPlace1")
    public Integer getBirthPlace1() {
        return this.birthPlace1;
    }
    
    public void setBirthPlace1(Integer birthPlace1) {
        this.birthPlace1 = birthPlace1;
    }

    
    @Column(name="BirthPlace2", length=16)
    public String getBirthPlace2() {
        return this.birthPlace2;
    }
    
    public void setBirthPlace2(String birthPlace2) {
        this.birthPlace2 = birthPlace2;
    }

    
    @Column(name="ChineseName", length=80)
    public String getChineseName() {
        return this.chineseName;
    }
    
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    
    @Column(name="BirthDate", length=8)
    public String getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="EnglishName", length=50)
    public String getEnglishName() {
        return this.englishName;
    }
    
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    
    @Column(name="ForeignPassportNo", length=15)
    public String getForeignPassportNo() {
        return this.foreignPassportNo;
    }
    
    public void setForeignPassportNo(String foreignPassportNo) {
        this.foreignPassportNo = foreignPassportNo;
    }

    
    @Column(name="OverseaIdNo", length=15)
    public String getOverseaIdNo() {
        return this.overseaIdNo;
    }
    
    public void setOverseaIdNo(String overseaIdNo) {
        this.overseaIdNo = overseaIdNo;
    }

    
    @Column(name="MilitaryNo", length=8)
    public String getMilitaryNo() {
        return this.militaryNo;
    }
    
    public void setMilitaryNo(String militaryNo) {
        this.militaryNo = militaryNo;
    }

    
    @Column(name="FatherName", length=24)
    public String getFatherName() {
        return this.fatherName;
    }
    
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }

    
    @Column(name="MotherName", length=24)
    public String getMotherName() {
        return this.motherName;
    }
    
    public void setMotherName(String motherName) {
        this.motherName = motherName;
    }

    
    @Column(name="LoveName", length=24)
    public String getLoveName() {
        return this.loveName;
    }
    
    public void setLoveName(String loveName) {
        this.loveName = loveName;
    }

    
    @Column(name="PassportNo", length=12)
    public String getPassportNo() {
        return this.passportNo;
    }
    
    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }

    
    @Column(name="MilitaryClass")
    public Integer getMilitaryClass() {
        return this.militaryClass;
    }
    
    public void setMilitaryClass(Integer militaryClass) {
        this.militaryClass = militaryClass;
    }

    
    @Column(name="OverseaResident")
    public Integer getOverseaResident() {
        return this.overseaResident;
    }
    
    public void setOverseaResident(Integer overseaResident) {
        this.overseaResident = overseaResident;
    }

    
    @Column(name="Position")
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }

    
    @Column(name="Occupation")
    public Integer getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(Integer occupation) {
        this.occupation = occupation;
    }

    
    @Column(name="Education")
    public Integer getEducation() {
        return this.education;
    }
    
    public void setEducation(Integer education) {
        this.education = education;
    }

    
    @Column(name="Marry")
    public Integer getMarry() {
        return this.marry;
    }
    
    public void setMarry(Integer marry) {
        this.marry = marry;
    }

    
    @Column(name="ResidentMark")
    public Integer getResidentMark() {
        return this.residentMark;
    }
    
    public void setResidentMark(Integer residentMark) {
        this.residentMark = residentMark;
    }

    
    @Column(name="VIPPosition")
    public Integer getVipposition() {
        return this.vipposition;
    }
    
    public void setVipposition(Integer vipposition) {
        this.vipposition = vipposition;
    }

    
    @Column(name="Mark")
    public Integer getMark() {
        return this.mark;
    }
    
    public void setMark(Integer mark) {
        this.mark = mark;
    }

    
    @Column(name="ResidentDate", length=8)
    public String getResidentDate() {
        return this.residentDate;
    }
    
    public void setResidentDate(String residentDate) {
        this.residentDate = residentDate;
    }

    
    @Column(name="ExitEntryNo")
    public Integer getExitEntryNo() {
        return this.exitEntryNo;
    }
    
    public void setExitEntryNo(Integer exitEntryNo) {
        this.exitEntryNo = exitEntryNo;
    }

    
    @Column(name="ResidentSum")
    public Integer getResidentSum() {
        return this.residentSum;
    }
    
    public void setResidentSum(Integer residentSum) {
        this.residentSum = residentSum;
    }

    
    @Column(name="Rank")
    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    
    @Column(name="TwnMainland0")
    public Integer getTwnMainland0() {
        return this.twnMainland0;
    }
    
    public void setTwnMainland0(Integer twnMainland0) {
        this.twnMainland0 = twnMainland0;
    }

    
    @Column(name="TwnMainland1")
    public Integer getTwnMainland1() {
        return this.twnMainland1;
    }
    
    public void setTwnMainland1(Integer twnMainland1) {
        this.twnMainland1 = twnMainland1;
    }

    
    @Column(name="TwnMainland2")
    public Integer getTwnMainland2() {
        return this.twnMainland2;
    }
    
    public void setTwnMainland2(Integer twnMainland2) {
        this.twnMainland2 = twnMainland2;
    }

    
    @Column(name="TwnMainland3")
    public Integer getTwnMainland3() {
        return this.twnMainland3;
    }
    
    public void setTwnMainland3(Integer twnMainland3) {
        this.twnMainland3 = twnMainland3;
    }

    
    @Column(name="TwnMainland4")
    public Integer getTwnMainland4() {
        return this.twnMainland4;
    }
    
    public void setTwnMainland4(Integer twnMainland4) {
        this.twnMainland4 = twnMainland4;
    }

    
    @Column(name="GeneralPermitNoYTD")
    public Integer getGeneralPermitNoYtd() {
        return this.generalPermitNoYtd;
    }
    
    public void setGeneralPermitNoYtd(Integer generalPermitNoYtd) {
        this.generalPermitNoYtd = generalPermitNoYtd;
    }

    
    @Column(name="PSightNoYTD")
    public Integer getPsightNoYtd() {
        return this.psightNoYtd;
    }
    
    public void setPsightNoYtd(Integer psightNoYtd) {
        this.psightNoYtd = psightNoYtd;
    }

    
    @Column(name="LastestSightDays")
    public Integer getLastestSightDays() {
        return this.lastestSightDays;
    }
    
    public void setLastestSightDays(Integer lastestSightDays) {
        this.lastestSightDays = lastestSightDays;
    }

    
    @Column(name="ExitNoYTD")
    public Long getExitNoYtd() {
        return this.exitNoYtd;
    }
    
    public void setExitNoYtd(Long exitNoYtd) {
        this.exitNoYtd = exitNoYtd;
    }

    
    @Column(name="EntryNoYTD")
    public Long getEntryNoYtd() {
        return this.entryNoYtd;
    }
    
    public void setEntryNoYtd(Long entryNoYtd) {
        this.entryNoYtd = entryNoYtd;
    }

    
    @Column(name="ExitDate", length=8)
    public String getExitDate() {
        return this.exitDate;
    }
    
    public void setExitDate(String exitDate) {
        this.exitDate = exitDate;
    }

    
    @Column(name="EntryDate", length=8)
    public String getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(String entryDate) {
        this.entryDate = entryDate;
    }

    
    @Column(name="ExitNo")
    public Long getExitNo() {
        return this.exitNo;
    }
    
    public void setExitNo(Long exitNo) {
        this.exitNo = exitNo;
    }

    
    @Column(name="EntryNo")
    public Integer getEntryNo() {
        return this.entryNo;
    }
    
    public void setEntryNo(Integer entryNo) {
        this.entryNo = entryNo;
    }

    
    @Column(name="LastestFilmNo", length=11)
    public String getLastestFilmNo() {
        return this.lastestFilmNo;
    }
    
    public void setLastestFilmNo(String lastestFilmNo) {
        this.lastestFilmNo = lastestFilmNo;
    }

    
    @Column(name="NationOversea", length=1)
    public String getNationOversea() {
        return this.nationOversea;
    }
    
    public void setNationOversea(String nationOversea) {
        this.nationOversea = nationOversea;
    }

    
    @Column(name="LastestRejectStatus", length=11)
    public String getLastestRejectStatus() {
        return this.lastestRejectStatus;
    }
    
    public void setLastestRejectStatus(String lastestRejectStatus) {
        this.lastestRejectStatus = lastestRejectStatus;
    }

    
    @Column(name="ControlMark", length=1)
    public String getControlMark() {
        return this.controlMark;
    }
    
    public void setControlMark(String controlMark) {
        this.controlMark = controlMark;
    }

    
    @Column(name="PostNoA")
    public Integer getPostNoA() {
        return this.postNoA;
    }
    
    public void setPostNoA(Integer postNoA) {
        this.postNoA = postNoA;
    }

    
    @Column(name="PostNoB")
    public Integer getPostNoB() {
        return this.postNoB;
    }
    
    public void setPostNoB(Integer postNoB) {
        this.postNoB = postNoB;
    }

    
    @Column(name="AddrTypeA", length=1)
    public String getAddrTypeA() {
        return this.addrTypeA;
    }
    
    public void setAddrTypeA(String addrTypeA) {
        this.addrTypeA = addrTypeA;
    }

    
    @Column(name="AddrTypeB", length=1)
    public String getAddrTypeB() {
        return this.addrTypeB;
    }
    
    public void setAddrTypeB(String addrTypeB) {
        this.addrTypeB = addrTypeB;
    }

    
    @Column(name="AddrBMark", length=1)
    public String getAddrBmark() {
        return this.addrBmark;
    }
    
    public void setAddrBmark(String addrBmark) {
        this.addrBmark = addrBmark;
    }

    
    @Column(name="Addr1A", length=16)
    public String getAddr1a() {
        return this.addr1a;
    }
    
    public void setAddr1a(String addr1a) {
        this.addr1a = addr1a;
    }

    
    @Column(name="Addr2A", length=4)
    public String getAddr2a() {
        return this.addr2a;
    }
    
    public void setAddr2a(String addr2a) {
        this.addr2a = addr2a;
    }

    
    @Column(name="Addr3A", length=4)
    public String getAddr3a() {
        return this.addr3a;
    }
    
    public void setAddr3a(String addr3a) {
        this.addr3a = addr3a;
    }

    
    @Column(name="Addr4A", length=100)
    public String getAddr4a() {
        return this.addr4a;
    }
    
    public void setAddr4a(String addr4a) {
        this.addr4a = addr4a;
    }

    
    @Column(name="Addr1B", length=16)
    public String getAddr1b() {
        return this.addr1b;
    }
    
    public void setAddr1b(String addr1b) {
        this.addr1b = addr1b;
    }

    
    @Column(name="Addr2B", length=4)
    public String getAddr2b() {
        return this.addr2b;
    }
    
    public void setAddr2b(String addr2b) {
        this.addr2b = addr2b;
    }

    
    @Column(name="Addr3B", length=4)
    public String getAddr3b() {
        return this.addr3b;
    }
    
    public void setAddr3b(String addr3b) {
        this.addr3b = addr3b;
    }

    
    @Column(name="Addr4B", length=100)
    public String getAddr4b() {
        return this.addr4b;
    }
    
    public void setAddr4b(String addr4b) {
        this.addr4b = addr4b;
    }

    
    @Column(name="PSightNoNext")
    public Integer getPsightNoNext() {
        return this.psightNoNext;
    }
    
    public void setPsightNoNext(Integer psightNoNext) {
        this.psightNoNext = psightNoNext;
    }

    
    @Column(name="LastestReceiveNo", length=12)
    public String getLastestReceiveNo() {
        return this.lastestReceiveNo;
    }
    
    public void setLastestReceiveNo(String lastestReceiveNo) {
        this.lastestReceiveNo = lastestReceiveNo;
    }

    
    @Column(name="MainlandIdNo", length=20)
    public String getMainlandIdNo() {
        return this.mainlandIdNo;
    }
    
    public void setMainlandIdNo(String mainlandIdNo) {
        this.mainlandIdNo = mainlandIdNo;
    }

    
    @Column(name="Commie", length=1)
    public String getCommie() {
        return this.commie;
    }
    
    public void setCommie(String commie) {
        this.commie = commie;
    }

    
    @Column(name="MilitaryNumber", length=1)
    public String getMilitaryNumber() {
        return this.militaryNumber;
    }
    
    public void setMilitaryNumber(String militaryNumber) {
        this.militaryNumber = militaryNumber;
    }

    
    @Column(name="DeadMark", length=1)
    public String getDeadMark() {
        return this.deadMark;
    }
    
    public void setDeadMark(String deadMark) {
        this.deadMark = deadMark;
    }

    
    @Column(name="MilitaryMark", length=1)
    public String getMilitaryMark() {
        return this.militaryMark;
    }
    
    public void setMilitaryMark(String militaryMark) {
        this.militaryMark = militaryMark;
    }

    
    @Column(name="NotSameone", length=1)
    public String getNotSameone() {
        return this.notSameone;
    }
    
    public void setNotSameone(String notSameone) {
        this.notSameone = notSameone;
    }

    
    @Column(name="ResidentIdNo", length=10)
    public String getResidentIdNo() {
        return this.residentIdNo;
    }
    
    public void setResidentIdNo(String residentIdNo) {
        this.residentIdNo = residentIdNo;
    }

    
    @Column(name="MarriedDate", length=8)
    public String getMarriedDate() {
        return this.marriedDate;
    }
    
    public void setMarriedDate(String marriedDate) {
        this.marriedDate = marriedDate;
    }

    
    @Column(name="CreateUserId", length=10)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDate", length=23)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="MainUserId", length=10)
    public String getMainUserId() {
        return this.mainUserId;
    }
    
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }

    
    @Column(name="MaintainProgramId", length=10)
    public String getMaintainProgramId() {
        return this.maintainProgramId;
    }
    
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdateTime", length=23)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    
    @Column(name="MaintainHost", length=24)
    public String getMaintainHost() {
        return this.maintainHost;
    }
    
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    
    @Column(name="Reserved")
    public String getReserved() {
        return this.reserved;
    }
    
    public void setReserved(String reserved) {
        this.reserved = reserved;
    }

    
    @Column(name="DeleteFlag", length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    
    @Column(name="CreateBy", length=6)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    
    @Column(name="AlleyA", length=20)
    public String getAlleyA() {
        return this.alleyA;
    }
    
    public void setAlleyA(String alleyA) {
        this.alleyA = alleyA;
    }

    
    @Column(name="AlleyB", length=12)
    public String getAlleyB() {
        return this.alleyB;
    }
    
    public void setAlleyB(String alleyB) {
        this.alleyB = alleyB;
    }

    
    @Column(name="ARCID", length=12)
    public String getArcid() {
        return this.arcid;
    }
    
    public void setArcid(String arcid) {
        this.arcid = arcid;
    }

    
    @Column(name="BelongCity", length=4)
    public String getBelongCity() {
        return this.belongCity;
    }
    
    public void setBelongCity(String belongCity) {
        this.belongCity = belongCity;
    }

    
    @Column(name="BelongDept", length=4)
    public String getBelongDept() {
        return this.belongDept;
    }
    
    public void setBelongDept(String belongDept) {
        this.belongDept = belongDept;
    }

    
    @Column(name="CityA", length=5)
    public String getCityA() {
        return this.cityA;
    }
    
    public void setCityA(String cityA) {
        this.cityA = cityA;
    }

    
    @Column(name="Name2", length=8)
    public String getName2() {
        return this.name2;
    }
    
    public void setName2(String name2) {
        this.name2 = name2;
    }

    
    @Column(name="CreateDeptId", length=4)
    public String getCreateDeptId() {
        return this.createDeptId;
    }
    
    public void setCreateDeptId(String createDeptId) {
        this.createDeptId = createDeptId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateTime", length=23)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="DistrictA", length=18)
    public String getDistrictA() {
        return this.districtA;
    }
    
    public void setDistrictA(String districtA) {
        this.districtA = districtA;
    }

    
    @Column(name="DistrictB", length=18)
    public String getDistrictB() {
        return this.districtB;
    }
    
    public void setDistrictB(String districtB) {
        this.districtB = districtB;
    }

    
    @Column(name="Email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="ForeignSpouseMark", length=1)
    public String getForeignSpouseMark() {
        return this.foreignSpouseMark;
    }
    
    public void setForeignSpouseMark(String foreignSpouseMark) {
        this.foreignSpouseMark = foreignSpouseMark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ImportTime", length=23)
    public Date getImportTime() {
        return this.importTime;
    }
    
    public void setImportTime(Date importTime) {
        this.importTime = importTime;
    }

    
    @Column(name="JobTitle", length=120)
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    
    @Column(name="LaneA", length=24)
    public String getLaneA() {
        return this.laneA;
    }
    
    public void setLaneA(String laneA) {
        this.laneA = laneA;
    }

    
    @Column(name="LaneB", length=18)
    public String getLaneB() {
        return this.laneB;
    }
    
    public void setLaneB(String laneB) {
        this.laneB = laneB;
    }

    
    @Column(name="MaintainDeptId", length=4)
    public String getMaintainDeptId() {
        return this.maintainDeptId;
    }
    
    public void setMaintainDeptId(String maintainDeptId) {
        this.maintainDeptId = maintainDeptId;
    }

    
    @Column(name="Mobile", length=20)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="MultiCitizenMark", length=1)
    public String getMultiCitizenMark() {
        return this.multiCitizenMark;
    }
    
    public void setMultiCitizenMark(String multiCitizenMark) {
        this.multiCitizenMark = multiCitizenMark;
    }

    
    @Column(name="NeighborhoodA", length=20)
    public String getNeighborhoodA() {
        return this.neighborhoodA;
    }
    
    public void setNeighborhoodA(String neighborhoodA) {
        this.neighborhoodA = neighborhoodA;
    }

    
    @Column(name="Name1", length=4)
    public String getName1() {
        return this.name1;
    }
    
    public void setName1(String name1) {
        this.name1 = name1;
    }

    
    @Column(name="NumberA", length=200)
    public String getNumberA() {
        return this.numberA;
    }
    
    public void setNumberA(String numberA) {
        this.numberA = numberA;
    }

    
    @Column(name="Name0", length=68)
    public String getName0() {
        return this.name0;
    }
    
    public void setName0(String name0) {
        this.name0 = name0;
    }

    
    @Column(name="OverseaAddress", length=200)
    public String getOverseaAddress() {
        return this.overseaAddress;
    }
    
    public void setOverseaAddress(String overseaAddress) {
        this.overseaAddress = overseaAddress;
    }

    
    @Column(name="OverseaContact", length=50)
    public String getOverseaContact() {
        return this.overseaContact;
    }
    
    public void setOverseaContact(String overseaContact) {
        this.overseaContact = overseaContact;
    }

    
    @Column(name="OverseaContactMobile", length=20)
    public String getOverseaContactMobile() {
        return this.overseaContactMobile;
    }
    
    public void setOverseaContactMobile(String overseaContactMobile) {
        this.overseaContactMobile = overseaContactMobile;
    }

    
    @Column(name="OverseaContactTel", length=20)
    public String getOverseaContactTel() {
        return this.overseaContactTel;
    }
    
    public void setOverseaContactTel(String overseaContactTel) {
        this.overseaContactTel = overseaContactTel;
    }

    
    @Column(name="OverseaTel", length=40)
    public String getOverseaTel() {
        return this.overseaTel;
    }
    
    public void setOverseaTel(String overseaTel) {
        this.overseaTel = overseaTel;
    }

    
    @Column(name="RoadA", length=40)
    public String getRoadA() {
        return this.roadA;
    }
    
    public void setRoadA(String roadA) {
        this.roadA = roadA;
    }

    
    @Column(name="RoadB", length=30)
    public String getRoadB() {
        return this.roadB;
    }
    
    public void setRoadB(String roadB) {
        this.roadB = roadB;
    }

    
    @Column(name="ServiceOfficeCode", length=4)
    public String getServiceOfficeCode() {
        return this.serviceOfficeCode;
    }
    
    public void setServiceOfficeCode(String serviceOfficeCode) {
        this.serviceOfficeCode = serviceOfficeCode;
    }

    
    @Column(name="ServiceOfficeName", length=120)
    public String getServiceOfficeName() {
        return this.serviceOfficeName;
    }
    
    public void setServiceOfficeName(String serviceOfficeName) {
        this.serviceOfficeName = serviceOfficeName;
    }

    
    @Column(name="ServiceOfficeSName", length=40)
    public String getServiceOfficeSname() {
        return this.serviceOfficeSname;
    }
    
    public void setServiceOfficeSname(String serviceOfficeSname) {
        this.serviceOfficeSname = serviceOfficeSname;
    }

    
    @Column(name="ServiceOfficeTel", length=15)
    public String getServiceOfficeTel() {
        return this.serviceOfficeTel;
    }
    
    public void setServiceOfficeTel(String serviceOfficeTel) {
        this.serviceOfficeTel = serviceOfficeTel;
    }

    
    @Column(name="SourceTable", length=24)
    public String getSourceTable() {
        return this.sourceTable;
    }
    
    public void setSourceTable(String sourceTable) {
        this.sourceTable = sourceTable;
    }

    
    @Column(name="TelA", length=20)
    public String getTelA() {
        return this.telA;
    }
    
    public void setTelA(String telA) {
        this.telA = telA;
    }

    
    @Column(name="TelB", length=20)
    public String getTelB() {
        return this.telB;
    }
    
    public void setTelB(String telB) {
        this.telB = telB;
    }

    
    @Column(name="TownshipA", length=3)
    public String getTownshipA() {
        return this.townshipA;
    }
    
    public void setTownshipA(String townshipA) {
        this.townshipA = townshipA;
    }

    
    @Column(name="TownshipB", length=3)
    public String getTownshipB() {
        return this.townshipB;
    }
    
    public void setTownshipB(String townshipB) {
        this.townshipB = townshipB;
    }

    
    @Column(name="TransferMark", length=2)
    public String getTransferMark() {
        return this.transferMark;
    }
    
    public void setTransferMark(String transferMark) {
        this.transferMark = transferMark;
    }

    
    @Column(name="VillageA", length=20)
    public String getVillageA() {
        return this.villageA;
    }
    
    public void setVillageA(String villageA) {
        this.villageA = villageA;
    }

    
    @Column(name="VillageB", length=16)
    public String getVillageB() {
        return this.villageB;
    }
    
    public void setVillageB(String villageB) {
        this.villageB = villageB;
    }

    
    @Column(name="ZipCodeA", length=5)
    public String getZipCodeA() {
        return this.zipCodeA;
    }
    
    public void setZipCodeA(String zipCodeA) {
        this.zipCodeA = zipCodeA;
    }

    
    @Column(name="ZipCodeB", length=5)
    public String getZipCodeB() {
        return this.zipCodeB;
    }
    
    public void setZipCodeB(String zipCodeB) {
        this.zipCodeB = zipCodeB;
    }

    
    @Column(name="ApplicantType", length=1)
    public String getApplicantType() {
        return this.applicantType;
    }
    
    public void setApplicantType(String applicantType) {
        this.applicantType = applicantType;
    }

    
    @Column(name="FatherBirthDate", length=8)
    public String getFatherBirthDate() {
        return this.fatherBirthDate;
    }
    
    public void setFatherBirthDate(String fatherBirthDate) {
        this.fatherBirthDate = fatherBirthDate;
    }

    
    @Column(name="FatherMark", length=1)
    public String getFatherMark() {
        return this.fatherMark;
    }
    
    public void setFatherMark(String fatherMark) {
        this.fatherMark = fatherMark;
    }

    
    @Column(name="FatherPersonId", length=15)
    public String getFatherPersonId() {
        return this.fatherPersonId;
    }
    
    public void setFatherPersonId(String fatherPersonId) {
        this.fatherPersonId = fatherPersonId;
    }

    
    @Column(name="LoveMark", length=1)
    public String getLoveMark() {
        return this.loveMark;
    }
    
    public void setLoveMark(String loveMark) {
        this.loveMark = loveMark;
    }

    
    @Column(name="MotherBirthDate", length=8)
    public String getMotherBirthDate() {
        return this.motherBirthDate;
    }
    
    public void setMotherBirthDate(String motherBirthDate) {
        this.motherBirthDate = motherBirthDate;
    }

    
    @Column(name="MotherMark", length=1)
    public String getMotherMark() {
        return this.motherMark;
    }
    
    public void setMotherMark(String motherMark) {
        this.motherMark = motherMark;
    }

    
    @Column(name="MotherPersonId", length=15)
    public String getMotherPersonId() {
        return this.motherPersonId;
    }
    
    public void setMotherPersonId(String motherPersonId) {
        this.motherPersonId = motherPersonId;
    }

    
    @Column(name="ReMark", length=2000)
    public String getReMark() {
        return this.reMark;
    }
    
    public void setReMark(String reMark) {
        this.reMark = reMark;
    }

    
    @Column(name="ETLFlag", length=1)
    public String getEtlflag() {
        return this.etlflag;
    }
    
    public void setEtlflag(String etlflag) {
        this.etlflag = etlflag;
    }

    
    @Column(name="TxnMark")
    public Long getTxnMark() {
        return this.txnMark;
    }
    
    public void setTxnMark(Long txnMark) {
        this.txnMark = txnMark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SyncTime", length=23)
    public Date getSyncTime() {
        return this.syncTime;
    }
    
    public void setSyncTime(Date syncTime) {
        this.syncTime = syncTime;
    }

    
    @Column(name="SortEnglishName", length=50)
    public String getSortEnglishName() {
        return this.sortEnglishName;
    }
    
    public void setSortEnglishName(String sortEnglishName) {
        this.sortEnglishName = sortEnglishName;
    }

    
    @Column(name="WriteBackFlag", length=1)
    public String getWriteBackFlag() {
        return this.writeBackFlag;
    }
    
    public void setWriteBackFlag(String writeBackFlag) {
        this.writeBackFlag = writeBackFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="WriteBackTime", length=23)
    public Date getWriteBackTime() {
        return this.writeBackTime;
    }
    
    public void setWriteBackTime(Date writeBackTime) {
        this.writeBackTime = writeBackTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EntryInspectTime", length=23)
    public Date getEntryInspectTime() {
        return this.entryInspectTime;
    }
    
    public void setEntryInspectTime(Date entryInspectTime) {
        this.entryInspectTime = entryInspectTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ExitInspectTime", length=23)
    public Date getExitInspectTime() {
        return this.exitInspectTime;
    }
    
    public void setExitInspectTime(Date exitInspectTime) {
        this.exitInspectTime = exitInspectTime;
    }




}


