package gov.nia.nrs.domain.iis;



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * DataSetting generated by hbm2java
 */
@Entity
@Table(name="DataSetting"
    , uniqueConstraints = @UniqueConstraint(columnNames={"CodeId", "CodeDataValue"}) 
)
public class DataSetting  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private Long version;
    private String codeId;
    private String codeDataValue;
    private String codeDataValueDesc;
    private String activeStatus;
    private String parentDataId;
    private String comments;
    private String createUserId;
    private Date createDate;
    private String mainUserId;
    private String maintainProgramId;
    private String maintainHost;
    private Date lastUpdateTime;
    private String codeDataValueDesc2;
    private String flag;
    private Long orderList;
    private String filter1;
    private String filter2;
    private String filter3;
    private String dataFlag;
    private Long txnMark;
    private Date syncTime;

    public DataSetting() {}

	
    public DataSetting(String id) {
        this.id = id;
    }
    public DataSetting(String id, String codeId, String codeDataValue, String codeDataValueDesc, String activeStatus, String parentDataId, String comments, String createUserId, Date createDate, String mainUserId, String maintainProgramId, String maintainHost, Date lastUpdateTime, String codeDataValueDesc2, String flag, Long orderList, String filter1, String filter2, String filter3, String dataFlag, Long txnMark, Date syncTime) {
        this.id = id;
        this.codeId = codeId;
        this.codeDataValue = codeDataValue;
        this.codeDataValueDesc = codeDataValueDesc;
        this.activeStatus = activeStatus;
        this.parentDataId = parentDataId;
        this.comments = comments;
        this.createUserId = createUserId;
        this.createDate = createDate;
        this.mainUserId = mainUserId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
        this.codeDataValueDesc2 = codeDataValueDesc2;
        this.flag = flag;
        this.orderList = orderList;
        this.filter1 = filter1;
        this.filter2 = filter2;
        this.filter3 = filter3;
        this.dataFlag = dataFlag;
        this.txnMark = txnMark;
        this.syncTime = syncTime;
    }
   
    @Id 

    
    @Column(name="Id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    @Version
    @Column(name="Version", scale=0)
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

    
    @Column(name="CodeId", length=32)
    public String getCodeId() {
        return this.codeId;
    }
    
    public void setCodeId(String codeId) {
        this.codeId = codeId;
    }

    
    @Column(name="CodeDataValue", length=64)
    public String getCodeDataValue() {
        return this.codeDataValue;
    }
    
    public void setCodeDataValue(String codeDataValue) {
        this.codeDataValue = codeDataValue;
    }

    
    @Column(name="CodeDataValueDesc", length=512)
    public String getCodeDataValueDesc() {
        return this.codeDataValueDesc;
    }
    
    public void setCodeDataValueDesc(String codeDataValueDesc) {
        this.codeDataValueDesc = codeDataValueDesc;
    }

    
    @Column(name="ActiveStatus", length=1)
    public String getActiveStatus() {
        return this.activeStatus;
    }
    
    public void setActiveStatus(String activeStatus) {
        this.activeStatus = activeStatus;
    }

    
    @Column(name="ParentDataId", length=32)
    public String getParentDataId() {
        return this.parentDataId;
    }
    
    public void setParentDataId(String parentDataId) {
        this.parentDataId = parentDataId;
    }

    
    @Column(name="Comments", length=512)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="CreateUserId", length=10)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDate", length=23)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="MainUserId", length=10)
    public String getMainUserId() {
        return this.mainUserId;
    }
    
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }

    
    @Column(name="MaintainProgramId", length=10)
    public String getMaintainProgramId() {
        return this.maintainProgramId;
    }
    
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    
    @Column(name="MaintainHost", length=24)
    public String getMaintainHost() {
        return this.maintainHost;
    }
    
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdateTime", length=23)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    
    @Column(name="CodeDataValueDesc2", length=512)
    public String getCodeDataValueDesc2() {
        return this.codeDataValueDesc2;
    }
    
    public void setCodeDataValueDesc2(String codeDataValueDesc2) {
        this.codeDataValueDesc2 = codeDataValueDesc2;
    }

    
    @Column(name="Flag", length=1)
    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }

    
    @Column(name="OrderList")
    public Long getOrderList() {
        return this.orderList;
    }
    
    public void setOrderList(Long orderList) {
        this.orderList = orderList;
    }

    
    @Column(name="Filter1", length=10)
    public String getFilter1() {
        return this.filter1;
    }
    
    public void setFilter1(String filter1) {
        this.filter1 = filter1;
    }

    
    @Column(name="Filter2", length=10)
    public String getFilter2() {
        return this.filter2;
    }
    
    public void setFilter2(String filter2) {
        this.filter2 = filter2;
    }

    
    @Column(name="Filter3", length=10)
    public String getFilter3() {
        return this.filter3;
    }
    
    public void setFilter3(String filter3) {
        this.filter3 = filter3;
    }

    
    @Column(name="DataFlag", length=1)
    public String getDataFlag() {
        return this.dataFlag;
    }
    
    public void setDataFlag(String dataFlag) {
        this.dataFlag = dataFlag;
    }

    
    @Column(name="TxnMark")
    public Long getTxnMark() {
        return this.txnMark;
    }
    
    public void setTxnMark(Long txnMark) {
        this.txnMark = txnMark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SyncTime", length=23)
    public Date getSyncTime() {
        return this.syncTime;
    }
    
    public void setSyncTime(Date syncTime) {
        this.syncTime = syncTime;
    }




}


