package gov.nia.nrs.domain.iis;



import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DeptRelationId generated by hbm2java
 */
@Embeddable
public class DeptRelationId  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private String deptId;
    private String station;

    public DeptRelationId() {}

    public DeptRelationId(String deptId, String station) {
        this.deptId = deptId;
        this.station = station;
    }
   


    @Column(name="DeptId", nullable=false, length=4)
    public String getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }


    @Column(name="Station", nullable=false, length=4)
    public String getStation() {
        return this.station;
    }
    
    public void setStation(String station) {
        this.station = station;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof DeptRelationId) ) return false;
		DeptRelationId castOther = ( DeptRelationId ) other; 
         
		return ( (this.getDeptId()==castOther.getDeptId()) || ( this.getDeptId()!=null && castOther.getDeptId()!=null && this.getDeptId().equals(castOther.getDeptId()) ) )
 && ( (this.getStation()==castOther.getStation()) || ( this.getStation()!=null && castOther.getStation()!=null && this.getStation().equals(castOther.getStation()) ) );
    }
   
    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getDeptId() == null ? 0 : this.getDeptId().hashCode() );
        result = 37 * result + ( getStation() == null ? 0 : this.getStation().hashCode() );
        return result;
    }   


}


