package gov.nia.nrs.domain.iis;



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dept generated by hbm2java
 */
@Entity
@Table(name="Dept"
)
public class Dept  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Long deptSeq;
    private String deptTreeCode;
    private String deptId;
    private String deptName;
    private String deptBriefName;
    private String deptLevel;
    private String domiCity;
    private String domiServiceStation;
    private String address;
    private String area;
    private String phoneNo;
    private String deptFlag;
    private String deptName2;
    private String signFlag;
    private Long acceptManCount;
    private Long acceptGirlCount;
    private String deleteFlag;
    private String memo;
    private String redTel;
    private String cityCode;
    private Long managerCount;
    private String contractorsName;
    private Long parlorTimes;
    private String titleCode;
    private String shelterId;
    private Long groupId;
    private String createUserId;
    private String createDeptId;
    private Date createTime;
    private String mainUserId;
    private String maintainDeptId;
    private String maintainProgramId;
    private String maintainHost;
    private Date lastUpdateTime;
    private Long txnMark;
    private Date syncTime;
    private String fax;
    private String deptEngName;
    private Long appointManCount;
    private Long appointGirlCount;
    private String zipCode;

    public Dept() {}

	
    public Dept(Long deptSeq, String deptTreeCode, String deptId, String deleteFlag) {
        this.deptSeq = deptSeq;
        this.deptTreeCode = deptTreeCode;
        this.deptId = deptId;
        this.deleteFlag = deleteFlag;
    }
    public Dept(Long deptSeq, String deptTreeCode, String deptId, String deptName, String deptBriefName, String deptLevel, String domiCity, String domiServiceStation, String address, String area, String phoneNo, String deptFlag, String deptName2, String signFlag, Long acceptManCount, Long acceptGirlCount, String deleteFlag, String memo, String redTel, String cityCode, Long managerCount, String contractorsName, Long parlorTimes, String titleCode, String shelterId, Long groupId, String createUserId, String createDeptId, Date createTime, String mainUserId, String maintainDeptId, String maintainProgramId, String maintainHost, Date lastUpdateTime, Long txnMark, Date syncTime, String fax, String deptEngName, Long appointManCount, Long appointGirlCount, String zipCode) {
        this.deptSeq = deptSeq;
        this.deptTreeCode = deptTreeCode;
        this.deptId = deptId;
        this.deptName = deptName;
        this.deptBriefName = deptBriefName;
        this.deptLevel = deptLevel;
        this.domiCity = domiCity;
        this.domiServiceStation = domiServiceStation;
        this.address = address;
        this.area = area;
        this.phoneNo = phoneNo;
        this.deptFlag = deptFlag;
        this.deptName2 = deptName2;
        this.signFlag = signFlag;
        this.acceptManCount = acceptManCount;
        this.acceptGirlCount = acceptGirlCount;
        this.deleteFlag = deleteFlag;
        this.memo = memo;
        this.redTel = redTel;
        this.cityCode = cityCode;
        this.managerCount = managerCount;
        this.contractorsName = contractorsName;
        this.parlorTimes = parlorTimes;
        this.titleCode = titleCode;
        this.shelterId = shelterId;
        this.groupId = groupId;
        this.createUserId = createUserId;
        this.createDeptId = createDeptId;
        this.createTime = createTime;
        this.mainUserId = mainUserId;
        this.maintainDeptId = maintainDeptId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
        this.txnMark = txnMark;
        this.syncTime = syncTime;
        this.fax = fax;
        this.deptEngName = deptEngName;
        this.appointManCount = appointManCount;
        this.appointGirlCount = appointGirlCount;
        this.zipCode = zipCode;
    }
   
    @Id 

    
    @Column(name="DeptSeq", unique=true, nullable=false, precision=18, scale=0)
    public Long getDeptSeq() {
        return this.deptSeq;
    }
    
    public void setDeptSeq(Long deptSeq) {
        this.deptSeq = deptSeq;
    }

    
    @Column(name="DeptTreeCode", nullable=false, length=30)
    public String getDeptTreeCode() {
        return this.deptTreeCode;
    }
    
    public void setDeptTreeCode(String deptTreeCode) {
        this.deptTreeCode = deptTreeCode;
    }

    
    @Column(name="DeptId", nullable=false, length=4)
    public String getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    
    @Column(name="DeptName", length=100)
    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    
    @Column(name="DeptBriefName", length=20)
    public String getDeptBriefName() {
        return this.deptBriefName;
    }
    
    public void setDeptBriefName(String deptBriefName) {
        this.deptBriefName = deptBriefName;
    }

    
    @Column(name="DeptLevel", length=1)
    public String getDeptLevel() {
        return this.deptLevel;
    }
    
    public void setDeptLevel(String deptLevel) {
        this.deptLevel = deptLevel;
    }

    
    @Column(name="DomiCity", length=4)
    public String getDomiCity() {
        return this.domiCity;
    }
    
    public void setDomiCity(String domiCity) {
        this.domiCity = domiCity;
    }

    
    @Column(name="DomiServiceStation", length=4)
    public String getDomiServiceStation() {
        return this.domiServiceStation;
    }
    
    public void setDomiServiceStation(String domiServiceStation) {
        this.domiServiceStation = domiServiceStation;
    }

    
    @Column(name="Address", length=200)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="Area", length=3)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }

    
    @Column(name="PhoneNo", length=15)
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    
    @Column(name="DeptFlag", length=1)
    public String getDeptFlag() {
        return this.deptFlag;
    }
    
    public void setDeptFlag(String deptFlag) {
        this.deptFlag = deptFlag;
    }

    
    @Column(name="DeptName2", length=30)
    public String getDeptName2() {
        return this.deptName2;
    }
    
    public void setDeptName2(String deptName2) {
        this.deptName2 = deptName2;
    }

    
    @Column(name="SignFlag", length=1)
    public String getSignFlag() {
        return this.signFlag;
    }
    
    public void setSignFlag(String signFlag) {
        this.signFlag = signFlag;
    }

    
    @Column(name="AcceptManCount")
    public Long getAcceptManCount() {
        return this.acceptManCount;
    }
    
    public void setAcceptManCount(Long acceptManCount) {
        this.acceptManCount = acceptManCount;
    }

    
    @Column(name="AcceptGirlCount")
    public Long getAcceptGirlCount() {
        return this.acceptGirlCount;
    }
    
    public void setAcceptGirlCount(Long acceptGirlCount) {
        this.acceptGirlCount = acceptGirlCount;
    }

    
    @Column(name="DeleteFlag", nullable=false, length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    
    @Column(name="Memo", length=100)
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }

    
    @Column(name="RedTel", length=15)
    public String getRedTel() {
        return this.redTel;
    }
    
    public void setRedTel(String redTel) {
        this.redTel = redTel;
    }

    
    @Column(name="CityCode", length=4)
    public String getCityCode() {
        return this.cityCode;
    }
    
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    
    @Column(name="ManagerCount")
    public Long getManagerCount() {
        return this.managerCount;
    }
    
    public void setManagerCount(Long managerCount) {
        this.managerCount = managerCount;
    }

    
    @Column(name="ContractorsName", length=80)
    public String getContractorsName() {
        return this.contractorsName;
    }
    
    public void setContractorsName(String contractorsName) {
        this.contractorsName = contractorsName;
    }

    
    @Column(name="ParlorTimes")
    public Long getParlorTimes() {
        return this.parlorTimes;
    }
    
    public void setParlorTimes(Long parlorTimes) {
        this.parlorTimes = parlorTimes;
    }

    
    @Column(name="TitleCode", length=3)
    public String getTitleCode() {
        return this.titleCode;
    }
    
    public void setTitleCode(String titleCode) {
        this.titleCode = titleCode;
    }

    
    @Column(name="ShelterId", length=4)
    public String getShelterId() {
        return this.shelterId;
    }
    
    public void setShelterId(String shelterId) {
        this.shelterId = shelterId;
    }

    
    @Column(name="GroupId")
    public Long getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    
    @Column(name="CreateUserId", length=10)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CreateDeptId", length=4)
    public String getCreateDeptId() {
        return this.createDeptId;
    }
    
    public void setCreateDeptId(String createDeptId) {
        this.createDeptId = createDeptId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateTime", length=23)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="MainUserId", length=10)
    public String getMainUserId() {
        return this.mainUserId;
    }
    
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }

    
    @Column(name="MaintainDeptId", length=4)
    public String getMaintainDeptId() {
        return this.maintainDeptId;
    }
    
    public void setMaintainDeptId(String maintainDeptId) {
        this.maintainDeptId = maintainDeptId;
    }

    
    @Column(name="MaintainProgramId", length=20)
    public String getMaintainProgramId() {
        return this.maintainProgramId;
    }
    
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    
    @Column(name="MaintainHost", length=25)
    public String getMaintainHost() {
        return this.maintainHost;
    }
    
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdateTime", length=23)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    
    @Column(name="TxnMark")
    public Long getTxnMark() {
        return this.txnMark;
    }
    
    public void setTxnMark(Long txnMark) {
        this.txnMark = txnMark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SyncTime", length=23)
    public Date getSyncTime() {
        return this.syncTime;
    }
    
    public void setSyncTime(Date syncTime) {
        this.syncTime = syncTime;
    }

    
    @Column(name="Fax", length=15)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="DeptEngName", length=50)
    public String getDeptEngName() {
        return this.deptEngName;
    }
    
    public void setDeptEngName(String deptEngName) {
        this.deptEngName = deptEngName;
    }

    
    @Column(name="AppointManCount")
    public Long getAppointManCount() {
        return this.appointManCount;
    }
    
    public void setAppointManCount(Long appointManCount) {
        this.appointManCount = appointManCount;
    }

    
    @Column(name="AppointGirlCount")
    public Long getAppointGirlCount() {
        return this.appointGirlCount;
    }
    
    public void setAppointGirlCount(Long appointGirlCount) {
        this.appointGirlCount = appointGirlCount;
    }

    
    @Column(name="ZipCode", length=5)
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }




}


