package gov.nia.nrs.domain.iis;



import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeptRelation generated by hbm2java
 */
@Entity
@Table(name="DeptRelation"
)
public class DeptRelation  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private DeptRelationId id;
    private String stationName;
    private String superiorDeptId;
    private String applyCaseUnitId;
    private Long permitPermission;
    private String receiptUnitId;
    private String createUserId;
    private String createDeptId;
    private Date createTime;
    private String mainUserId;
    private String maintainDeptId;
    private String maintainProgramId;
    private String maintainHost;
    private Date lastUpdateTime;
    private Integer feeCollectMethod;

    public DeptRelation() {}

	
    public DeptRelation(DeptRelationId id, Long permitPermission, String createUserId, String createDeptId, Date createTime, String mainUserId, String maintainDeptId, String maintainProgramId, String maintainHost, Date lastUpdateTime, Integer feeCollectMethod) {
        this.id = id;
        this.permitPermission = permitPermission;
        this.createUserId = createUserId;
        this.createDeptId = createDeptId;
        this.createTime = createTime;
        this.mainUserId = mainUserId;
        this.maintainDeptId = maintainDeptId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
        this.feeCollectMethod = feeCollectMethod;
    }
    public DeptRelation(DeptRelationId id, String stationName, String superiorDeptId, String applyCaseUnitId, Long permitPermission, String receiptUnitId, String createUserId, String createDeptId, Date createTime, String mainUserId, String maintainDeptId, String maintainProgramId, String maintainHost, Date lastUpdateTime, Integer feeCollectMethod) {
        this.id = id;
        this.stationName = stationName;
        this.superiorDeptId = superiorDeptId;
        this.applyCaseUnitId = applyCaseUnitId;
        this.permitPermission = permitPermission;
        this.receiptUnitId = receiptUnitId;
        this.createUserId = createUserId;
        this.createDeptId = createDeptId;
        this.createTime = createTime;
        this.mainUserId = mainUserId;
        this.maintainDeptId = maintainDeptId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
        this.feeCollectMethod = feeCollectMethod;
    }
   
    @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="deptId", column=@Column(name="DeptId", nullable=false, length=4) ), 
        @AttributeOverride(name="station", column=@Column(name="Station", nullable=false, length=4) ) } )
    public DeptRelationId getId() {
        return this.id;
    }
    
    public void setId(DeptRelationId id) {
        this.id = id;
    }

    
    @Column(name="StationName", length=100)
    public String getStationName() {
        return this.stationName;
    }
    
    public void setStationName(String stationName) {
        this.stationName = stationName;
    }

    
    @Column(name="SuperiorDeptId", length=4)
    public String getSuperiorDeptId() {
        return this.superiorDeptId;
    }
    
    public void setSuperiorDeptId(String superiorDeptId) {
        this.superiorDeptId = superiorDeptId;
    }

    
    @Column(name="ApplyCaseUnitId", length=4)
    public String getApplyCaseUnitId() {
        return this.applyCaseUnitId;
    }
    
    public void setApplyCaseUnitId(String applyCaseUnitId) {
        this.applyCaseUnitId = applyCaseUnitId;
    }

    
    @Column(name="PermitPermission", nullable=false)
    public Long getPermitPermission() {
        return this.permitPermission;
    }
    
    public void setPermitPermission(Long permitPermission) {
        this.permitPermission = permitPermission;
    }

    
    @Column(name="ReceiptUnitId", length=4)
    public String getReceiptUnitId() {
        return this.receiptUnitId;
    }
    
    public void setReceiptUnitId(String receiptUnitId) {
        this.receiptUnitId = receiptUnitId;
    }

    
    @Column(name="CreateUserId", nullable=false, length=10)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CreateDeptId", nullable=false, length=4)
    public String getCreateDeptId() {
        return this.createDeptId;
    }
    
    public void setCreateDeptId(String createDeptId) {
        this.createDeptId = createDeptId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateTime", nullable=false, length=23)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="MainUserId", nullable=false, length=10)
    public String getMainUserId() {
        return this.mainUserId;
    }
    
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }

    
    @Column(name="MaintainDeptId", nullable=false, length=4)
    public String getMaintainDeptId() {
        return this.maintainDeptId;
    }
    
    public void setMaintainDeptId(String maintainDeptId) {
        this.maintainDeptId = maintainDeptId;
    }

    
    @Column(name="MaintainProgramId", nullable=false, length=20)
    public String getMaintainProgramId() {
        return this.maintainProgramId;
    }
    
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    
    @Column(name="MaintainHost", nullable=false, length=25)
    public String getMaintainHost() {
        return this.maintainHost;
    }
    
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdateTime", nullable=false, length=23)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    
    @Column(name="FeeCollectMethod", nullable=false)
    public Integer getFeeCollectMethod() {
        return this.feeCollectMethod;
    }
    
    public void setFeeCollectMethod(Integer feeCollectMethod) {
        this.feeCollectMethod = feeCollectMethod;
    }




}


