package gov.nia.nrs.domain.iis;



import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * EntryExitRecords generated by hbm2java
 */
@Entity
@Table(name="EntryExitRecords"
)
public class EntryExitRecords  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private EntryExitRecordsId id;
    private Long version;
    private String firstReceiveNo;
    private String decideDate;
    private String decideDateResign;
    private String exitDate;
    private String exitTime;
    private String entryDate;
    private String entryTime;
    private Integer exitEdcardReason;
    private Integer entryEdcardReason;
    private Integer exitEdcardOccupation;
    private Integer entryEdcardOccupation;
    private Integer exitFromTo;
    private Integer entryFromTo;
    private Integer exitPort;
    private Integer entryPort;
    private String exitFlyNo;
    private String entryFlyNo;
    private String notSameoneExit;
    private String notSameoneEntry;
    private Date lastUpdateTime;
    private String maintainHost;
    private String reserved;
    private String deleteFlag;
    private String createBy;
    private String createDeptId;
    private Date createTime;
    private String createUserId;
    private String entryBarcode;
    private String exitBarcode;
    private String maintainDeptId;
    private String maintainProgramId;
    private String mainUserId;
    private String nation;
    private String otherBarcode;
    private String passengerId;
    private String passportNo;
    private String sourceTable;
    private String writeBackFlag;
    private Date writeBackTime;
    private String entryDailyImmigrationsPk1;
    private Integer entryDailyImmigrationsPk2;
    private String entryDailyImmigrationsPk3;
    private Integer entryDailyImmigrationsPk4;
    private String exitDailyImmigrationsPk1;
    private Integer exitDailyImmigrationsPk2;
    private String exitDailyImmigrationsPk3;
    private Integer exitDailyImmigrationsPk4;
    private Date entryInspectTime;
    private Date exitInspectTime;

    public EntryExitRecords() {}

	
    public EntryExitRecords(EntryExitRecordsId id) {
        this.id = id;
    }
    public EntryExitRecords(EntryExitRecordsId id, String firstReceiveNo, String decideDate, String decideDateResign, String exitDate, String exitTime, String entryDate, String entryTime, Integer exitEdcardReason, Integer entryEdcardReason, Integer exitEdcardOccupation, Integer entryEdcardOccupation, Integer exitFromTo, Integer entryFromTo, Integer exitPort, Integer entryPort, String exitFlyNo, String entryFlyNo, String notSameoneExit, String notSameoneEntry, Date lastUpdateTime, String maintainHost, String reserved, String deleteFlag, String createBy, String createDeptId, Date createTime, String createUserId, String entryBarcode, String exitBarcode, String maintainDeptId, String maintainProgramId, String mainUserId, String nation, String otherBarcode, String passengerId, String passportNo, String sourceTable, String writeBackFlag, Date writeBackTime, String entryDailyImmigrationsPk1, Integer entryDailyImmigrationsPk2, String entryDailyImmigrationsPk3, Integer entryDailyImmigrationsPk4, String exitDailyImmigrationsPk1, Integer exitDailyImmigrationsPk2, String exitDailyImmigrationsPk3, Integer exitDailyImmigrationsPk4, Date entryInspectTime, Date exitInspectTime) {
        this.id = id;
        this.firstReceiveNo = firstReceiveNo;
        this.decideDate = decideDate;
        this.decideDateResign = decideDateResign;
        this.exitDate = exitDate;
        this.exitTime = exitTime;
        this.entryDate = entryDate;
        this.entryTime = entryTime;
        this.exitEdcardReason = exitEdcardReason;
        this.entryEdcardReason = entryEdcardReason;
        this.exitEdcardOccupation = exitEdcardOccupation;
        this.entryEdcardOccupation = entryEdcardOccupation;
        this.exitFromTo = exitFromTo;
        this.entryFromTo = entryFromTo;
        this.exitPort = exitPort;
        this.entryPort = entryPort;
        this.exitFlyNo = exitFlyNo;
        this.entryFlyNo = entryFlyNo;
        this.notSameoneExit = notSameoneExit;
        this.notSameoneEntry = notSameoneEntry;
        this.lastUpdateTime = lastUpdateTime;
        this.maintainHost = maintainHost;
        this.reserved = reserved;
        this.deleteFlag = deleteFlag;
        this.createBy = createBy;
        this.createDeptId = createDeptId;
        this.createTime = createTime;
        this.createUserId = createUserId;
        this.entryBarcode = entryBarcode;
        this.exitBarcode = exitBarcode;
        this.maintainDeptId = maintainDeptId;
        this.maintainProgramId = maintainProgramId;
        this.mainUserId = mainUserId;
        this.nation = nation;
        this.otherBarcode = otherBarcode;
        this.passengerId = passengerId;
        this.passportNo = passportNo;
        this.sourceTable = sourceTable;
        this.writeBackFlag = writeBackFlag;
        this.writeBackTime = writeBackTime;
        this.entryDailyImmigrationsPk1 = entryDailyImmigrationsPk1;
        this.entryDailyImmigrationsPk2 = entryDailyImmigrationsPk2;
        this.entryDailyImmigrationsPk3 = entryDailyImmigrationsPk3;
        this.entryDailyImmigrationsPk4 = entryDailyImmigrationsPk4;
        this.exitDailyImmigrationsPk1 = exitDailyImmigrationsPk1;
        this.exitDailyImmigrationsPk2 = exitDailyImmigrationsPk2;
        this.exitDailyImmigrationsPk3 = exitDailyImmigrationsPk3;
        this.exitDailyImmigrationsPk4 = exitDailyImmigrationsPk4;
        this.entryInspectTime = entryInspectTime;
        this.exitInspectTime = exitInspectTime;
    }
   
    @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="receiveNo", column=@Column(name="ReceiveNo", nullable=false, length=12) ), 
        @AttributeOverride(name="resignNo", column=@Column(name="ResignNo", nullable=false) ) } )
    public EntryExitRecordsId getId() {
        return this.id;
    }
    
    public void setId(EntryExitRecordsId id) {
        this.id = id;
    }

    @Version
    @Column(name="Version", scale=0)
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

    
    @Column(name="FirstReceiveNo", length=12)
    public String getFirstReceiveNo() {
        return this.firstReceiveNo;
    }
    
    public void setFirstReceiveNo(String firstReceiveNo) {
        this.firstReceiveNo = firstReceiveNo;
    }

    
    @Column(name="DecideDate", length=8)
    public String getDecideDate() {
        return this.decideDate;
    }
    
    public void setDecideDate(String decideDate) {
        this.decideDate = decideDate;
    }

    
    @Column(name="DecideDateResign", length=8)
    public String getDecideDateResign() {
        return this.decideDateResign;
    }
    
    public void setDecideDateResign(String decideDateResign) {
        this.decideDateResign = decideDateResign;
    }

    
    @Column(name="ExitDate", length=8)
    public String getExitDate() {
        return this.exitDate;
    }
    
    public void setExitDate(String exitDate) {
        this.exitDate = exitDate;
    }

    
    @Column(name="ExitTime", length=8)
    public String getExitTime() {
        return this.exitTime;
    }
    
    public void setExitTime(String exitTime) {
        this.exitTime = exitTime;
    }

    
    @Column(name="EntryDate", length=8)
    public String getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(String entryDate) {
        this.entryDate = entryDate;
    }

    
    @Column(name="EntryTime", length=8)
    public String getEntryTime() {
        return this.entryTime;
    }
    
    public void setEntryTime(String entryTime) {
        this.entryTime = entryTime;
    }

    
    @Column(name="ExitEDCardReason")
    public Integer getExitEdcardReason() {
        return this.exitEdcardReason;
    }
    
    public void setExitEdcardReason(Integer exitEdcardReason) {
        this.exitEdcardReason = exitEdcardReason;
    }

    
    @Column(name="EntryEDCardReason")
    public Integer getEntryEdcardReason() {
        return this.entryEdcardReason;
    }
    
    public void setEntryEdcardReason(Integer entryEdcardReason) {
        this.entryEdcardReason = entryEdcardReason;
    }

    
    @Column(name="ExitEDCardOccupation")
    public Integer getExitEdcardOccupation() {
        return this.exitEdcardOccupation;
    }
    
    public void setExitEdcardOccupation(Integer exitEdcardOccupation) {
        this.exitEdcardOccupation = exitEdcardOccupation;
    }

    
    @Column(name="EntryEDCardOccupation")
    public Integer getEntryEdcardOccupation() {
        return this.entryEdcardOccupation;
    }
    
    public void setEntryEdcardOccupation(Integer entryEdcardOccupation) {
        this.entryEdcardOccupation = entryEdcardOccupation;
    }

    
    @Column(name="ExitFromTo")
    public Integer getExitFromTo() {
        return this.exitFromTo;
    }
    
    public void setExitFromTo(Integer exitFromTo) {
        this.exitFromTo = exitFromTo;
    }

    
    @Column(name="EntryFromTo")
    public Integer getEntryFromTo() {
        return this.entryFromTo;
    }
    
    public void setEntryFromTo(Integer entryFromTo) {
        this.entryFromTo = entryFromTo;
    }

    
    @Column(name="ExitPort")
    public Integer getExitPort() {
        return this.exitPort;
    }
    
    public void setExitPort(Integer exitPort) {
        this.exitPort = exitPort;
    }

    
    @Column(name="EntryPort")
    public Integer getEntryPort() {
        return this.entryPort;
    }
    
    public void setEntryPort(Integer entryPort) {
        this.entryPort = entryPort;
    }

    
    @Column(name="ExitFlyNo", length=6)
    public String getExitFlyNo() {
        return this.exitFlyNo;
    }
    
    public void setExitFlyNo(String exitFlyNo) {
        this.exitFlyNo = exitFlyNo;
    }

    
    @Column(name="EntryFlyNo", length=6)
    public String getEntryFlyNo() {
        return this.entryFlyNo;
    }
    
    public void setEntryFlyNo(String entryFlyNo) {
        this.entryFlyNo = entryFlyNo;
    }

    
    @Column(name="NotSameoneExit", length=1)
    public String getNotSameoneExit() {
        return this.notSameoneExit;
    }
    
    public void setNotSameoneExit(String notSameoneExit) {
        this.notSameoneExit = notSameoneExit;
    }

    
    @Column(name="NotSameoneEntry", length=1)
    public String getNotSameoneEntry() {
        return this.notSameoneEntry;
    }
    
    public void setNotSameoneEntry(String notSameoneEntry) {
        this.notSameoneEntry = notSameoneEntry;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdateTime", length=23)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    
    @Column(name="MaintainHost", length=24)
    public String getMaintainHost() {
        return this.maintainHost;
    }
    
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    
    @Column(name="Reserved", length=30)
    public String getReserved() {
        return this.reserved;
    }
    
    public void setReserved(String reserved) {
        this.reserved = reserved;
    }

    
    @Column(name="DeleteFlag", length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    
    @Column(name="CreateBy", length=6)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    
    @Column(name="CreateDeptId", length=4)
    public String getCreateDeptId() {
        return this.createDeptId;
    }
    
    public void setCreateDeptId(String createDeptId) {
        this.createDeptId = createDeptId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateTime", length=23)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="CreateUserId", length=10)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="EntryBarcode", length=3)
    public String getEntryBarcode() {
        return this.entryBarcode;
    }
    
    public void setEntryBarcode(String entryBarcode) {
        this.entryBarcode = entryBarcode;
    }

    
    @Column(name="ExitBarcode", length=15)
    public String getExitBarcode() {
        return this.exitBarcode;
    }
    
    public void setExitBarcode(String exitBarcode) {
        this.exitBarcode = exitBarcode;
    }

    
    @Column(name="MaintainDeptId", length=4)
    public String getMaintainDeptId() {
        return this.maintainDeptId;
    }
    
    public void setMaintainDeptId(String maintainDeptId) {
        this.maintainDeptId = maintainDeptId;
    }

    
    @Column(name="MaintainProgramId", length=20)
    public String getMaintainProgramId() {
        return this.maintainProgramId;
    }
    
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    
    @Column(name="MainUserId", length=10)
    public String getMainUserId() {
        return this.mainUserId;
    }
    
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }

    
    @Column(name="Nation", length=3)
    public String getNation() {
        return this.nation;
    }
    
    public void setNation(String nation) {
        this.nation = nation;
    }

    
    @Column(name="OtherBarcode", length=15)
    public String getOtherBarcode() {
        return this.otherBarcode;
    }
    
    public void setOtherBarcode(String otherBarcode) {
        this.otherBarcode = otherBarcode;
    }

    
    @Column(name="PassengerId", length=10)
    public String getPassengerId() {
        return this.passengerId;
    }
    
    public void setPassengerId(String passengerId) {
        this.passengerId = passengerId;
    }

    
    @Column(name="PassportNo", length=15)
    public String getPassportNo() {
        return this.passportNo;
    }
    
    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }

    
    @Column(name="SourceTable", length=10)
    public String getSourceTable() {
        return this.sourceTable;
    }
    
    public void setSourceTable(String sourceTable) {
        this.sourceTable = sourceTable;
    }

    
    @Column(name="WriteBackFlag", length=1)
    public String getWriteBackFlag() {
        return this.writeBackFlag;
    }
    
    public void setWriteBackFlag(String writeBackFlag) {
        this.writeBackFlag = writeBackFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="WriteBackTime", length=23)
    public Date getWriteBackTime() {
        return this.writeBackTime;
    }
    
    public void setWriteBackTime(Date writeBackTime) {
        this.writeBackTime = writeBackTime;
    }

    
    @Column(name="EntryDailyImmigrationsPK1", length=10)
    public String getEntryDailyImmigrationsPk1() {
        return this.entryDailyImmigrationsPk1;
    }
    
    public void setEntryDailyImmigrationsPk1(String entryDailyImmigrationsPk1) {
        this.entryDailyImmigrationsPk1 = entryDailyImmigrationsPk1;
    }

    
    @Column(name="EntryDailyImmigrationsPK2", precision=2, scale=0)
    public Integer getEntryDailyImmigrationsPk2() {
        return this.entryDailyImmigrationsPk2;
    }
    
    public void setEntryDailyImmigrationsPk2(Integer entryDailyImmigrationsPk2) {
        this.entryDailyImmigrationsPk2 = entryDailyImmigrationsPk2;
    }

    
    @Column(name="EntryDailyImmigrationsPK3", length=8)
    public String getEntryDailyImmigrationsPk3() {
        return this.entryDailyImmigrationsPk3;
    }
    
    public void setEntryDailyImmigrationsPk3(String entryDailyImmigrationsPk3) {
        this.entryDailyImmigrationsPk3 = entryDailyImmigrationsPk3;
    }

    
    @Column(name="EntryDailyImmigrationsPK4", precision=5, scale=0)
    public Integer getEntryDailyImmigrationsPk4() {
        return this.entryDailyImmigrationsPk4;
    }
    
    public void setEntryDailyImmigrationsPk4(Integer entryDailyImmigrationsPk4) {
        this.entryDailyImmigrationsPk4 = entryDailyImmigrationsPk4;
    }

    
    @Column(name="ExitDailyImmigrationsPK1", length=10)
    public String getExitDailyImmigrationsPk1() {
        return this.exitDailyImmigrationsPk1;
    }
    
    public void setExitDailyImmigrationsPk1(String exitDailyImmigrationsPk1) {
        this.exitDailyImmigrationsPk1 = exitDailyImmigrationsPk1;
    }

    
    @Column(name="ExitDailyImmigrationsPK2", precision=2, scale=0)
    public Integer getExitDailyImmigrationsPk2() {
        return this.exitDailyImmigrationsPk2;
    }
    
    public void setExitDailyImmigrationsPk2(Integer exitDailyImmigrationsPk2) {
        this.exitDailyImmigrationsPk2 = exitDailyImmigrationsPk2;
    }

    
    @Column(name="ExitDailyImmigrationsPK3", length=8)
    public String getExitDailyImmigrationsPk3() {
        return this.exitDailyImmigrationsPk3;
    }
    
    public void setExitDailyImmigrationsPk3(String exitDailyImmigrationsPk3) {
        this.exitDailyImmigrationsPk3 = exitDailyImmigrationsPk3;
    }

    
    @Column(name="ExitDailyImmigrationsPK4", precision=5, scale=0)
    public Integer getExitDailyImmigrationsPk4() {
        return this.exitDailyImmigrationsPk4;
    }
    
    public void setExitDailyImmigrationsPk4(Integer exitDailyImmigrationsPk4) {
        this.exitDailyImmigrationsPk4 = exitDailyImmigrationsPk4;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EntryInspectTime", length=23)
    public Date getEntryInspectTime() {
        return this.entryInspectTime;
    }
    
    public void setEntryInspectTime(Date entryInspectTime) {
        this.entryInspectTime = entryInspectTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ExitInspectTime", length=23)
    public Date getExitInspectTime() {
        return this.exitInspectTime;
    }
    
    public void setExitInspectTime(Date exitInspectTime) {
        this.exitInspectTime = exitInspectTime;
    }




}


