package gov.nia.nrs.domain.iis;



import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EntryExitRecordsId generated by hbm2java
 */
@Embeddable
public class EntryExitRecordsId  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private String receiveNo;
    private Integer resignNo;

    public EntryExitRecordsId() {}

    public EntryExitRecordsId(String receiveNo, Integer resignNo) {
        this.receiveNo = receiveNo;
        this.resignNo = resignNo;
    }
   


    @Column(name="ReceiveNo", nullable=false, length=12)
    public String getReceiveNo() {
        return this.receiveNo;
    }
    
    public void setReceiveNo(String receiveNo) {
        this.receiveNo = receiveNo;
    }


    @Column(name="ResignNo", nullable=false)
    public Integer getResignNo() {
        return this.resignNo;
    }
    
    public void setResignNo(Integer resignNo) {
        this.resignNo = resignNo;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof EntryExitRecordsId) ) return false;
		EntryExitRecordsId castOther = ( EntryExitRecordsId ) other; 
         
		return ( (this.getReceiveNo()==castOther.getReceiveNo()) || ( this.getReceiveNo()!=null && castOther.getReceiveNo()!=null && this.getReceiveNo().equals(castOther.getReceiveNo()) ) )
 && ( (this.getResignNo()==castOther.getResignNo()) || ( this.getResignNo()!=null && castOther.getResignNo()!=null && this.getResignNo().equals(castOther.getResignNo()) ) );
    }
   
    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getReceiveNo() == null ? 0 : this.getReceiveNo().hashCode() );
        result = 37 * result + ( getResignNo() == null ? 0 : this.getResignNo().hashCode() );
        return result;
    }   


}


