package gov.nia.nrs.domain.iis;



import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ForeignStayNewId generated by hbm2java
 */
@Embeddable
public class ForeignStayNewId  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private String passengerId;
    private Long serialNo;

    public ForeignStayNewId() {}

    public ForeignStayNewId(String passengerId, Long serialNo) {
        this.passengerId = passengerId;
        this.serialNo = serialNo;
    }
   


    @Column(name="PassengerId", nullable=false, length=10)
    public String getPassengerId() {
        return this.passengerId;
    }
    
    public void setPassengerId(String passengerId) {
        this.passengerId = passengerId;
    }


    @Column(name="SerialNo", nullable=false, precision=12, scale=0)
    public Long getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(Long serialNo) {
        this.serialNo = serialNo;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof ForeignStayNewId) ) return false;
		ForeignStayNewId castOther = ( ForeignStayNewId ) other; 
         
		return ( (this.getPassengerId()==castOther.getPassengerId()) || ( this.getPassengerId()!=null && castOther.getPassengerId()!=null && this.getPassengerId().equals(castOther.getPassengerId()) ) )
 && ( (this.getSerialNo()==castOther.getSerialNo()) || ( this.getSerialNo()!=null && castOther.getSerialNo()!=null && this.getSerialNo().equals(castOther.getSerialNo()) ) );
    }
   
    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getPassengerId() == null ? 0 : this.getPassengerId().hashCode() );
        result = 37 * result + ( getSerialNo() == null ? 0 : this.getSerialNo().hashCode() );
        return result;
    }   


}


