package gov.nia.nrs.domain.iis;



import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ForeignStayNew generated by hbm2java
 */
@Entity
@Table(name="ForeignStayNew"
)
public class ForeignStayNew  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private ForeignStayNewId id;
    private String passportNo;
    private String englishName;
    private String birthDate;
    private String gender;
    private Integer nation;
    private String residenceId;
    private String expiryDate;
    private String reserved;
    private Date establishTime;
    private Date importTime;
    private String deleteFlag;
    private String mainUserId;
    private String maintainProgramId;
    private String maintainHost;
    private Date lastUpdateTime;
    private String chineseName;
    private String chineseNameB;
    private String statusCode;
    private String multiCitizenMark;
    private String visaKind;
    private String occupation;
    private String issueLoc;
    private String personId;
    private String edCardNo;
    private String entryDate;
    private String entrySerialNo;
    private String entryFlightNo;
    private String departFrom;
    private String entryPort;
    private String reason;
    private String rcLoc;
    private String zipCode;
    private String addr;
    private String addrB;
    private String hotelMark;
    private String exitDate;
    private String exitSerialNo;
    private String exitFlightNo;
    private String arriveTo;
    private String exitPort;
    private String nationalityChangeMark;
    private String deadMark;
    private String citizenMark;
    private String remark;
    private String passportExpiryDate;
    private String process;
    private String stayDays;
    private String entryBarcode;
    private String exitBarcode;
    private String deadBarcode;
    private String exitKeyinUserId2;
    private String exitKeyinDate2;
    private String entryKeyinUserId2;
    private String date3;
    private String entryKeyinDate2;
    private String deadlineDate;
    private String reserved2;
    private String reserved3;
    private String reserved4;
    private String reserved5;
    private String reserved6;
    private String entryDailyImmigrationsPk1;
    private Integer entryDailyImmigrationsPk2;
    private String entryDailyImmigrationsPk3;
    private Integer entryDailyImmigrationsPk4;
    private String exitDailyImmigrationsPk1;
    private Integer exitDailyImmigrationsPk2;
    private String exitDailyImmigrationsPk3;
    private Integer exitDailyImmigrationsPk4;
    private String exitTime;
    private String entryTime;
    private String sortEnglishName;
    private Long txnMark;
    private Date syncTime;
    private String etlflag;
    private String exitNo;
    private Long seq;
    private Date batchTime;
    private Date acardTime;
    private Date seqUpdateTime;
    private String entrySecondDocType;
    private String exitSecondDocType;
    private Date entryInspectTime;
    private Date exitInspectTime;
    private Date batchUpdTime;
    private Date uiUpdTime;
    private String positionChange;
    private String visaZipCode;
    private String visaAddr;
    private String positionChangeReceiveNo;

    public ForeignStayNew() {}

	
    public ForeignStayNew(ForeignStayNewId id) {
        this.id = id;
    }
    public ForeignStayNew(ForeignStayNewId id, String passportNo, String englishName, String birthDate, String gender, Integer nation, String residenceId, String expiryDate, String reserved, Date establishTime, Date importTime, String deleteFlag, String mainUserId, String maintainProgramId, String maintainHost, Date lastUpdateTime, String chineseName, String chineseNameB, String statusCode, String multiCitizenMark, String visaKind, String occupation, String issueLoc, String personId, String edCardNo, String entryDate, String entrySerialNo, String entryFlightNo, String departFrom, String entryPort, String reason, String rcLoc, String zipCode, String addr, String addrB, String hotelMark, String exitDate, String exitSerialNo, String exitFlightNo, String arriveTo, String exitPort, String nationalityChangeMark, String deadMark, String citizenMark, String remark, String passportExpiryDate, String process, String stayDays, String entryBarcode, String exitBarcode, String deadBarcode, String exitKeyinUserId2, String exitKeyinDate2, String entryKeyinUserId2, String date3, String entryKeyinDate2, String deadlineDate, String reserved2, String reserved3, String reserved4, String reserved5, String reserved6, String entryDailyImmigrationsPk1, Integer entryDailyImmigrationsPk2, String entryDailyImmigrationsPk3, Integer entryDailyImmigrationsPk4, String exitDailyImmigrationsPk1, Integer exitDailyImmigrationsPk2, String exitDailyImmigrationsPk3, Integer exitDailyImmigrationsPk4, String exitTime, String entryTime, String sortEnglishName, Long txnMark, Date syncTime, String etlflag, String exitNo, Long seq, Date batchTime, Date acardTime, Date seqUpdateTime, String entrySecondDocType, String exitSecondDocType, Date entryInspectTime, Date exitInspectTime, Date batchUpdTime, Date uiUpdTime, String positionChange, String visaZipCode, String visaAddr, String positionChangeReceiveNo) {
        this.id = id;
        this.passportNo = passportNo;
        this.englishName = englishName;
        this.birthDate = birthDate;
        this.gender = gender;
        this.nation = nation;
        this.residenceId = residenceId;
        this.expiryDate = expiryDate;
        this.reserved = reserved;
        this.establishTime = establishTime;
        this.importTime = importTime;
        this.deleteFlag = deleteFlag;
        this.mainUserId = mainUserId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
        this.chineseName = chineseName;
        this.chineseNameB = chineseNameB;
        this.statusCode = statusCode;
        this.multiCitizenMark = multiCitizenMark;
        this.visaKind = visaKind;
        this.occupation = occupation;
        this.issueLoc = issueLoc;
        this.personId = personId;
        this.edCardNo = edCardNo;
        this.entryDate = entryDate;
        this.entrySerialNo = entrySerialNo;
        this.entryFlightNo = entryFlightNo;
        this.departFrom = departFrom;
        this.entryPort = entryPort;
        this.reason = reason;
        this.rcLoc = rcLoc;
        this.zipCode = zipCode;
        this.addr = addr;
        this.addrB = addrB;
        this.hotelMark = hotelMark;
        this.exitDate = exitDate;
        this.exitSerialNo = exitSerialNo;
        this.exitFlightNo = exitFlightNo;
        this.arriveTo = arriveTo;
        this.exitPort = exitPort;
        this.nationalityChangeMark = nationalityChangeMark;
        this.deadMark = deadMark;
        this.citizenMark = citizenMark;
        this.remark = remark;
        this.passportExpiryDate = passportExpiryDate;
        this.process = process;
        this.stayDays = stayDays;
        this.entryBarcode = entryBarcode;
        this.exitBarcode = exitBarcode;
        this.deadBarcode = deadBarcode;
        this.exitKeyinUserId2 = exitKeyinUserId2;
        this.exitKeyinDate2 = exitKeyinDate2;
        this.entryKeyinUserId2 = entryKeyinUserId2;
        this.date3 = date3;
        this.entryKeyinDate2 = entryKeyinDate2;
        this.deadlineDate = deadlineDate;
        this.reserved2 = reserved2;
        this.reserved3 = reserved3;
        this.reserved4 = reserved4;
        this.reserved5 = reserved5;
        this.reserved6 = reserved6;
        this.entryDailyImmigrationsPk1 = entryDailyImmigrationsPk1;
        this.entryDailyImmigrationsPk2 = entryDailyImmigrationsPk2;
        this.entryDailyImmigrationsPk3 = entryDailyImmigrationsPk3;
        this.entryDailyImmigrationsPk4 = entryDailyImmigrationsPk4;
        this.exitDailyImmigrationsPk1 = exitDailyImmigrationsPk1;
        this.exitDailyImmigrationsPk2 = exitDailyImmigrationsPk2;
        this.exitDailyImmigrationsPk3 = exitDailyImmigrationsPk3;
        this.exitDailyImmigrationsPk4 = exitDailyImmigrationsPk4;
        this.exitTime = exitTime;
        this.entryTime = entryTime;
        this.sortEnglishName = sortEnglishName;
        this.txnMark = txnMark;
        this.syncTime = syncTime;
        this.etlflag = etlflag;
        this.exitNo = exitNo;
        this.seq = seq;
        this.batchTime = batchTime;
        this.acardTime = acardTime;
        this.seqUpdateTime = seqUpdateTime;
        this.entrySecondDocType = entrySecondDocType;
        this.exitSecondDocType = exitSecondDocType;
        this.entryInspectTime = entryInspectTime;
        this.exitInspectTime = exitInspectTime;
        this.batchUpdTime = batchUpdTime;
        this.uiUpdTime = uiUpdTime;
        this.positionChange = positionChange;
        this.visaZipCode = visaZipCode;
        this.visaAddr = visaAddr;
        this.positionChangeReceiveNo = positionChangeReceiveNo;
    }
   
    @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="passengerId", column=@Column(name="PassengerId", nullable=false, length=10) ), 
        @AttributeOverride(name="serialNo", column=@Column(name="SerialNo", nullable=false, precision=12, scale=0) ) } )
    public ForeignStayNewId getId() {
        return this.id;
    }
    
    public void setId(ForeignStayNewId id) {
        this.id = id;
    }

    
    @Column(name="PassportNo", length=15)
    public String getPassportNo() {
        return this.passportNo;
    }
    
    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }

    
    @Column(name="EnglishName", length=50)
    public String getEnglishName() {
        return this.englishName;
    }
    
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    
    @Column(name="BirthDate", length=8)
    public String getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="Gender", length=1)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="Nation", precision=3, scale=0)
    public Integer getNation() {
        return this.nation;
    }
    
    public void setNation(Integer nation) {
        this.nation = nation;
    }

    
    @Column(name="ResidenceId", length=10)
    public String getResidenceId() {
        return this.residenceId;
    }
    
    public void setResidenceId(String residenceId) {
        this.residenceId = residenceId;
    }

    
    @Column(name="ExpiryDate", length=8)
    public String getExpiryDate() {
        return this.expiryDate;
    }
    
    public void setExpiryDate(String expiryDate) {
        this.expiryDate = expiryDate;
    }

    
    @Column(name="Reserved", length=60)
    public String getReserved() {
        return this.reserved;
    }
    
    public void setReserved(String reserved) {
        this.reserved = reserved;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EstablishTime", length=23)
    public Date getEstablishTime() {
        return this.establishTime;
    }
    
    public void setEstablishTime(Date establishTime) {
        this.establishTime = establishTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ImportTime", length=23)
    public Date getImportTime() {
        return this.importTime;
    }
    
    public void setImportTime(Date importTime) {
        this.importTime = importTime;
    }

    
    @Column(name="DeleteFlag", length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    
    @Column(name="MainUserId", length=10)
    public String getMainUserId() {
        return this.mainUserId;
    }
    
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }

    
    @Column(name="MaintainProgramId", length=10)
    public String getMaintainProgramId() {
        return this.maintainProgramId;
    }
    
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    
    @Column(name="MaintainHost", length=2)
    public String getMaintainHost() {
        return this.maintainHost;
    }
    
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdateTime", length=23)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    
    @Column(name="ChineseName", length=24)
    public String getChineseName() {
        return this.chineseName;
    }
    
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    
    @Column(name="ChineseNameB", length=24)
    public String getChineseNameB() {
        return this.chineseNameB;
    }
    
    public void setChineseNameB(String chineseNameB) {
        this.chineseNameB = chineseNameB;
    }

    
    @Column(name="StatusCode", length=1)
    public String getStatusCode() {
        return this.statusCode;
    }
    
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }

    
    @Column(name="MultiCitizenMark", length=1)
    public String getMultiCitizenMark() {
        return this.multiCitizenMark;
    }
    
    public void setMultiCitizenMark(String multiCitizenMark) {
        this.multiCitizenMark = multiCitizenMark;
    }

    
    @Column(name="VisaKind", length=1)
    public String getVisaKind() {
        return this.visaKind;
    }
    
    public void setVisaKind(String visaKind) {
        this.visaKind = visaKind;
    }

    
    @Column(name="Occupation", length=2)
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    
    @Column(name="IssueLoc", length=3)
    public String getIssueLoc() {
        return this.issueLoc;
    }
    
    public void setIssueLoc(String issueLoc) {
        this.issueLoc = issueLoc;
    }

    
    @Column(name="PersonId", length=10)
    public String getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(String personId) {
        this.personId = personId;
    }

    
    @Column(name="EdCardNo", length=10)
    public String getEdCardNo() {
        return this.edCardNo;
    }
    
    public void setEdCardNo(String edCardNo) {
        this.edCardNo = edCardNo;
    }

    
    @Column(name="EntryDate", length=8)
    public String getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(String entryDate) {
        this.entryDate = entryDate;
    }

    
    @Column(name="EntrySerialNo", length=10)
    public String getEntrySerialNo() {
        return this.entrySerialNo;
    }
    
    public void setEntrySerialNo(String entrySerialNo) {
        this.entrySerialNo = entrySerialNo;
    }

    
    @Column(name="EntryFlightNo", length=6)
    public String getEntryFlightNo() {
        return this.entryFlightNo;
    }
    
    public void setEntryFlightNo(String entryFlightNo) {
        this.entryFlightNo = entryFlightNo;
    }

    
    @Column(name="DepartFrom", length=3)
    public String getDepartFrom() {
        return this.departFrom;
    }
    
    public void setDepartFrom(String departFrom) {
        this.departFrom = departFrom;
    }

    
    @Column(name="EntryPort", length=2)
    public String getEntryPort() {
        return this.entryPort;
    }
    
    public void setEntryPort(String entryPort) {
        this.entryPort = entryPort;
    }

    
    @Column(name="Reason", length=3)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    
    @Column(name="RcLoc", length=3)
    public String getRcLoc() {
        return this.rcLoc;
    }
    
    public void setRcLoc(String rcLoc) {
        this.rcLoc = rcLoc;
    }

    
    @Column(name="ZipCode", length=3)
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    
    @Column(name="Addr", length=200)
    public String getAddr() {
        return this.addr;
    }
    
    public void setAddr(String addr) {
        this.addr = addr;
    }

    
    @Column(name="AddrB", length=100)
    public String getAddrB() {
        return this.addrB;
    }
    
    public void setAddrB(String addrB) {
        this.addrB = addrB;
    }

    
    @Column(name="HotelMark", length=1)
    public String getHotelMark() {
        return this.hotelMark;
    }
    
    public void setHotelMark(String hotelMark) {
        this.hotelMark = hotelMark;
    }

    
    @Column(name="ExitDate", length=8)
    public String getExitDate() {
        return this.exitDate;
    }
    
    public void setExitDate(String exitDate) {
        this.exitDate = exitDate;
    }

    
    @Column(name="ExitSerialNo", length=10)
    public String getExitSerialNo() {
        return this.exitSerialNo;
    }
    
    public void setExitSerialNo(String exitSerialNo) {
        this.exitSerialNo = exitSerialNo;
    }

    
    @Column(name="ExitFlightNo", length=6)
    public String getExitFlightNo() {
        return this.exitFlightNo;
    }
    
    public void setExitFlightNo(String exitFlightNo) {
        this.exitFlightNo = exitFlightNo;
    }

    
    @Column(name="ArriveTo", length=3)
    public String getArriveTo() {
        return this.arriveTo;
    }
    
    public void setArriveTo(String arriveTo) {
        this.arriveTo = arriveTo;
    }

    
    @Column(name="ExitPort", length=2)
    public String getExitPort() {
        return this.exitPort;
    }
    
    public void setExitPort(String exitPort) {
        this.exitPort = exitPort;
    }

    
    @Column(name="NationalityChangeMark", length=100)
    public String getNationalityChangeMark() {
        return this.nationalityChangeMark;
    }
    
    public void setNationalityChangeMark(String nationalityChangeMark) {
        this.nationalityChangeMark = nationalityChangeMark;
    }

    
    @Column(name="DeadMark", length=100)
    public String getDeadMark() {
        return this.deadMark;
    }
    
    public void setDeadMark(String deadMark) {
        this.deadMark = deadMark;
    }

    
    @Column(name="CitizenMark", length=100)
    public String getCitizenMark() {
        return this.citizenMark;
    }
    
    public void setCitizenMark(String citizenMark) {
        this.citizenMark = citizenMark;
    }

    
    @Column(name="Remark")
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="PassportExpiryDate", length=8)
    public String getPassportExpiryDate() {
        return this.passportExpiryDate;
    }
    
    public void setPassportExpiryDate(String passportExpiryDate) {
        this.passportExpiryDate = passportExpiryDate;
    }

    
    @Column(name="Process", length=1)
    public String getProcess() {
        return this.process;
    }
    
    public void setProcess(String process) {
        this.process = process;
    }

    
    @Column(name="StayDays", length=30)
    public String getStayDays() {
        return this.stayDays;
    }
    
    public void setStayDays(String stayDays) {
        this.stayDays = stayDays;
    }

    
    @Column(name="EntryBarcode", length=15)
    public String getEntryBarcode() {
        return this.entryBarcode;
    }
    
    public void setEntryBarcode(String entryBarcode) {
        this.entryBarcode = entryBarcode;
    }

    
    @Column(name="ExitBarcode", length=15)
    public String getExitBarcode() {
        return this.exitBarcode;
    }
    
    public void setExitBarcode(String exitBarcode) {
        this.exitBarcode = exitBarcode;
    }

    
    @Column(name="DeadBarcode", length=15)
    public String getDeadBarcode() {
        return this.deadBarcode;
    }
    
    public void setDeadBarcode(String deadBarcode) {
        this.deadBarcode = deadBarcode;
    }

    
    @Column(name="ExitKeyinUserId2", length=10)
    public String getExitKeyinUserId2() {
        return this.exitKeyinUserId2;
    }
    
    public void setExitKeyinUserId2(String exitKeyinUserId2) {
        this.exitKeyinUserId2 = exitKeyinUserId2;
    }

    
    @Column(name="ExitKeyinDate2", length=14)
    public String getExitKeyinDate2() {
        return this.exitKeyinDate2;
    }
    
    public void setExitKeyinDate2(String exitKeyinDate2) {
        this.exitKeyinDate2 = exitKeyinDate2;
    }

    
    @Column(name="EntryKeyinUserId2", length=10)
    public String getEntryKeyinUserId2() {
        return this.entryKeyinUserId2;
    }
    
    public void setEntryKeyinUserId2(String entryKeyinUserId2) {
        this.entryKeyinUserId2 = entryKeyinUserId2;
    }

    
    @Column(name="Date3", length=10)
    public String getDate3() {
        return this.date3;
    }
    
    public void setDate3(String date3) {
        this.date3 = date3;
    }

    
    @Column(name="EntryKeyinDate2", length=14)
    public String getEntryKeyinDate2() {
        return this.entryKeyinDate2;
    }
    
    public void setEntryKeyinDate2(String entryKeyinDate2) {
        this.entryKeyinDate2 = entryKeyinDate2;
    }

    
    @Column(name="DeadlineDate", length=3)
    public String getDeadlineDate() {
        return this.deadlineDate;
    }
    
    public void setDeadlineDate(String deadlineDate) {
        this.deadlineDate = deadlineDate;
    }

    
    @Column(name="Reserved2", length=30)
    public String getReserved2() {
        return this.reserved2;
    }
    
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2;
    }

    
    @Column(name="Reserved3", length=30)
    public String getReserved3() {
        return this.reserved3;
    }
    
    public void setReserved3(String reserved3) {
        this.reserved3 = reserved3;
    }

    
    @Column(name="Reserved4", length=30)
    public String getReserved4() {
        return this.reserved4;
    }
    
    public void setReserved4(String reserved4) {
        this.reserved4 = reserved4;
    }

    
    @Column(name="Reserved5", length=30)
    public String getReserved5() {
        return this.reserved5;
    }
    
    public void setReserved5(String reserved5) {
        this.reserved5 = reserved5;
    }

    
    @Column(name="Reserved6", length=30)
    public String getReserved6() {
        return this.reserved6;
    }
    
    public void setReserved6(String reserved6) {
        this.reserved6 = reserved6;
    }

    
    @Column(name="EntryDailyImmigrationsPK1", length=10)
    public String getEntryDailyImmigrationsPk1() {
        return this.entryDailyImmigrationsPk1;
    }
    
    public void setEntryDailyImmigrationsPk1(String entryDailyImmigrationsPk1) {
        this.entryDailyImmigrationsPk1 = entryDailyImmigrationsPk1;
    }

    
    @Column(name="EntryDailyImmigrationsPK2", precision=2, scale=0)
    public Integer getEntryDailyImmigrationsPk2() {
        return this.entryDailyImmigrationsPk2;
    }
    
    public void setEntryDailyImmigrationsPk2(Integer entryDailyImmigrationsPk2) {
        this.entryDailyImmigrationsPk2 = entryDailyImmigrationsPk2;
    }

    
    @Column(name="EntryDailyImmigrationsPK3", length=8)
    public String getEntryDailyImmigrationsPk3() {
        return this.entryDailyImmigrationsPk3;
    }
    
    public void setEntryDailyImmigrationsPk3(String entryDailyImmigrationsPk3) {
        this.entryDailyImmigrationsPk3 = entryDailyImmigrationsPk3;
    }

    
    @Column(name="EntryDailyImmigrationsPK4", precision=5, scale=0)
    public Integer getEntryDailyImmigrationsPk4() {
        return this.entryDailyImmigrationsPk4;
    }
    
    public void setEntryDailyImmigrationsPk4(Integer entryDailyImmigrationsPk4) {
        this.entryDailyImmigrationsPk4 = entryDailyImmigrationsPk4;
    }

    
    @Column(name="ExitDailyImmigrationsPK1", length=10)
    public String getExitDailyImmigrationsPk1() {
        return this.exitDailyImmigrationsPk1;
    }
    
    public void setExitDailyImmigrationsPk1(String exitDailyImmigrationsPk1) {
        this.exitDailyImmigrationsPk1 = exitDailyImmigrationsPk1;
    }

    
    @Column(name="ExitDailyImmigrationsPK2", precision=2, scale=0)
    public Integer getExitDailyImmigrationsPk2() {
        return this.exitDailyImmigrationsPk2;
    }
    
    public void setExitDailyImmigrationsPk2(Integer exitDailyImmigrationsPk2) {
        this.exitDailyImmigrationsPk2 = exitDailyImmigrationsPk2;
    }

    
    @Column(name="ExitDailyImmigrationsPK3", length=8)
    public String getExitDailyImmigrationsPk3() {
        return this.exitDailyImmigrationsPk3;
    }
    
    public void setExitDailyImmigrationsPk3(String exitDailyImmigrationsPk3) {
        this.exitDailyImmigrationsPk3 = exitDailyImmigrationsPk3;
    }

    
    @Column(name="ExitDailyImmigrationsPK4", precision=5, scale=0)
    public Integer getExitDailyImmigrationsPk4() {
        return this.exitDailyImmigrationsPk4;
    }
    
    public void setExitDailyImmigrationsPk4(Integer exitDailyImmigrationsPk4) {
        this.exitDailyImmigrationsPk4 = exitDailyImmigrationsPk4;
    }

    
    @Column(name="ExitTime", length=8)
    public String getExitTime() {
        return this.exitTime;
    }
    
    public void setExitTime(String exitTime) {
        this.exitTime = exitTime;
    }

    
    @Column(name="EntryTime", length=8)
    public String getEntryTime() {
        return this.entryTime;
    }
    
    public void setEntryTime(String entryTime) {
        this.entryTime = entryTime;
    }

    
    @Column(name="SortEnglishName", length=50)
    public String getSortEnglishName() {
        return this.sortEnglishName;
    }
    
    public void setSortEnglishName(String sortEnglishName) {
        this.sortEnglishName = sortEnglishName;
    }

    
    @Column(name="TxnMark")
    public Long getTxnMark() {
        return this.txnMark;
    }
    
    public void setTxnMark(Long txnMark) {
        this.txnMark = txnMark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SyncTime", length=23)
    public Date getSyncTime() {
        return this.syncTime;
    }
    
    public void setSyncTime(Date syncTime) {
        this.syncTime = syncTime;
    }

    
    @Column(name="ETLFlag", length=1)
    public String getEtlflag() {
        return this.etlflag;
    }
    
    public void setEtlflag(String etlflag) {
        this.etlflag = etlflag;
    }

    
    @Column(name="ExitNo", length=15)
    public String getExitNo() {
        return this.exitNo;
    }
    
    public void setExitNo(String exitNo) {
        this.exitNo = exitNo;
    }

    
    @Column(name="Seq", precision=12, scale=0)
    public Long getSeq() {
        return this.seq;
    }
    
    public void setSeq(Long seq) {
        this.seq = seq;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BatchTime", length=23)
    public Date getBatchTime() {
        return this.batchTime;
    }
    
    public void setBatchTime(Date batchTime) {
        this.batchTime = batchTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="AcardTime", length=23)
    public Date getAcardTime() {
        return this.acardTime;
    }
    
    public void setAcardTime(Date acardTime) {
        this.acardTime = acardTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SeqUpdateTime", length=23)
    public Date getSeqUpdateTime() {
        return this.seqUpdateTime;
    }
    
    public void setSeqUpdateTime(Date seqUpdateTime) {
        this.seqUpdateTime = seqUpdateTime;
    }

    
    @Column(name="EntrySecondDocType", length=1)
    public String getEntrySecondDocType() {
        return this.entrySecondDocType;
    }
    
    public void setEntrySecondDocType(String entrySecondDocType) {
        this.entrySecondDocType = entrySecondDocType;
    }

    
    @Column(name="ExitSecondDocType", length=1)
    public String getExitSecondDocType() {
        return this.exitSecondDocType;
    }
    
    public void setExitSecondDocType(String exitSecondDocType) {
        this.exitSecondDocType = exitSecondDocType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EntryInspectTime", length=23)
    public Date getEntryInspectTime() {
        return this.entryInspectTime;
    }
    
    public void setEntryInspectTime(Date entryInspectTime) {
        this.entryInspectTime = entryInspectTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ExitInspectTime", length=23)
    public Date getExitInspectTime() {
        return this.exitInspectTime;
    }
    
    public void setExitInspectTime(Date exitInspectTime) {
        this.exitInspectTime = exitInspectTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BatchUpdTime", length=23)
    public Date getBatchUpdTime() {
        return this.batchUpdTime;
    }
    
    public void setBatchUpdTime(Date batchUpdTime) {
        this.batchUpdTime = batchUpdTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UiUpdTime", length=23)
    public Date getUiUpdTime() {
        return this.uiUpdTime;
    }
    
    public void setUiUpdTime(Date uiUpdTime) {
        this.uiUpdTime = uiUpdTime;
    }

    
    @Column(name="PositionChange", length=1)
    public String getPositionChange() {
        return this.positionChange;
    }
    
    public void setPositionChange(String positionChange) {
        this.positionChange = positionChange;
    }

    
    @Column(name="VisaZipCode", length=3)
    public String getVisaZipCode() {
        return this.visaZipCode;
    }
    
    public void setVisaZipCode(String visaZipCode) {
        this.visaZipCode = visaZipCode;
    }

    
    @Column(name="VisaAddr", length=200)
    public String getVisaAddr() {
        return this.visaAddr;
    }
    
    public void setVisaAddr(String visaAddr) {
        this.visaAddr = visaAddr;
    }

    
    @Column(name="PositionChangeReceiveNo", length=12)
    public String getPositionChangeReceiveNo() {
        return this.positionChangeReceiveNo;
    }
    
    public void setPositionChangeReceiveNo(String positionChangeReceiveNo) {
        this.positionChangeReceiveNo = positionChangeReceiveNo;
    }




}


