package gov.nia.nrs.domain.iis;



import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IdNoIndexId generated by hbm2java
 */
@Embeddable
public class IdNoIndexId  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private String idNo;
    private Integer dup;

    public IdNoIndexId() {}

    public IdNoIndexId(String idNo, Integer dup) {
        this.idNo = idNo;
        this.dup = dup;
    }
   


    @Column(name="IdNo", nullable=false, length=20)
    public String getIdNo() {
        return this.idNo;
    }
    
    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }


    @Column(name="Dup", nullable=false)
    public Integer getDup() {
        return this.dup;
    }
    
    public void setDup(Integer dup) {
        this.dup = dup;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof IdNoIndexId) ) return false;
		IdNoIndexId castOther = ( IdNoIndexId ) other; 
         
		return ( (this.getIdNo()==castOther.getIdNo()) || ( this.getIdNo()!=null && castOther.getIdNo()!=null && this.getIdNo().equals(castOther.getIdNo()) ) )
 && ( (this.getDup()==castOther.getDup()) || ( this.getDup()!=null && castOther.getDup()!=null && this.getDup().equals(castOther.getDup()) ) );
    }
   
    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getIdNo() == null ? 0 : this.getIdNo().hashCode() );
        result = 37 * result + ( getDup() == null ? 0 : this.getDup().hashCode() );
        return result;
    }   


}


