package gov.nia.nrs.domain.iis;



import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * IdNoIndex generated by hbm2java
 */
@Entity
@Table(name="IdNoIndex"
)
public class IdNoIndex  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private IdNoIndexId id;
    private Long version;
    private String firstReceiveNo;
    private Date lastUpdateTime;
    private String maintainHost;
    private String deleteFlag;
    private String createBy;
    private String createDeptId;
    private Date createTime;
    private String createUserId;
    private String maintainDeptId;
    private String maintainProgramId;
    private String mainUserId;

    public IdNoIndex() {}

	
    public IdNoIndex(IdNoIndexId id) {
        this.id = id;
    }
    public IdNoIndex(IdNoIndexId id, String firstReceiveNo, Date lastUpdateTime, String maintainHost, String deleteFlag, String createBy, String createDeptId, Date createTime, String createUserId, String maintainDeptId, String maintainProgramId, String mainUserId) {
        this.id = id;
        this.firstReceiveNo = firstReceiveNo;
        this.lastUpdateTime = lastUpdateTime;
        this.maintainHost = maintainHost;
        this.deleteFlag = deleteFlag;
        this.createBy = createBy;
        this.createDeptId = createDeptId;
        this.createTime = createTime;
        this.createUserId = createUserId;
        this.maintainDeptId = maintainDeptId;
        this.maintainProgramId = maintainProgramId;
        this.mainUserId = mainUserId;
    }
   
    @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idNo", column=@Column(name="IdNo", nullable=false, length=20) ), 
        @AttributeOverride(name="dup", column=@Column(name="Dup", nullable=false) ) } )
    public IdNoIndexId getId() {
        return this.id;
    }
    
    public void setId(IdNoIndexId id) {
        this.id = id;
    }

    @Version
    @Column(name="Version", scale=0)
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

    
    @Column(name="FirstReceiveNo", length=12)
    public String getFirstReceiveNo() {
        return this.firstReceiveNo;
    }
    
    public void setFirstReceiveNo(String firstReceiveNo) {
        this.firstReceiveNo = firstReceiveNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdateTime", length=23)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    
    @Column(name="MaintainHost", length=24)
    public String getMaintainHost() {
        return this.maintainHost;
    }
    
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    
    @Column(name="DeleteFlag", length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    
    @Column(name="CreateBy", length=6)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    
    @Column(name="CreateDeptId", length=4)
    public String getCreateDeptId() {
        return this.createDeptId;
    }
    
    public void setCreateDeptId(String createDeptId) {
        this.createDeptId = createDeptId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateTime", length=23)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="CreateUserId", length=10)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="MaintainDeptId", length=4)
    public String getMaintainDeptId() {
        return this.maintainDeptId;
    }
    
    public void setMaintainDeptId(String maintainDeptId) {
        this.maintainDeptId = maintainDeptId;
    }

    
    @Column(name="MaintainProgramId", length=20)
    public String getMaintainProgramId() {
        return this.maintainProgramId;
    }
    
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    
    @Column(name="MainUserId", length=10)
    public String getMainUserId() {
        return this.mainUserId;
    }
    
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }




}


