package gov.nia.nrs.domain.iis;



import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NoMatchImmigrations generated by hbm2java
 */
@Entity
@Table(name="NoMatchImmigrations"
)
public class NoMatchImmigrations  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private NoMatchImmigrationsId id;
    private String gender;
    private Integer birthPlaceCode;
    private Integer birthPlace1;
    private String birthPlace2;
    private String chineseName;
    private String birthDate;
    private String passportNo;
    private String permitNo;
    private Integer permitWord;
    private Integer fromTo;
    private Integer immigrateType;
    private String flightNo;
    private String permitWordId;
    private String fromToId;
    private String issueNo;
    private String prePermitNo;
    private String firstRecvNo;
    private Integer edCardOccupation;
    private String nationOversea;
    private Integer overseaResident;
    private Integer entryReason;
    private Integer immigrateType2;
    private String followNo;
    private String chiPersonId;
    private Integer militaryType;
    private String militaryNo;
    private String keyinUserId;
    private String keyinDate;
    private String edCardMark;
    private String remark;
    private String reserved;
    private Date establishTime;
    private Date importTime;
    private String deleteFlag;
    private String mainUserId;
    private String maintainProgramId;
    private String maintainHost;
    private Date lastUpdateTime;
    private String englishName;
    private String nation;
    private String status;
    private String sourceTable;
    private String etlflag;
    private String writeBackFlag;
    private Date writeBackTime;
    private Long serialNoLoginPk;
    private String reason;
    private String personId;

    public NoMatchImmigrations() {}

	
    public NoMatchImmigrations(NoMatchImmigrationsId id, String gender, Integer birthPlaceCode, Integer birthPlace1, String chineseName, String birthDate, String flightNo, String deleteFlag, String mainUserId, String maintainProgramId, String maintainHost, Date lastUpdateTime) {
        this.id = id;
        this.gender = gender;
        this.birthPlaceCode = birthPlaceCode;
        this.birthPlace1 = birthPlace1;
        this.chineseName = chineseName;
        this.birthDate = birthDate;
        this.flightNo = flightNo;
        this.deleteFlag = deleteFlag;
        this.mainUserId = mainUserId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
    }
    public NoMatchImmigrations(NoMatchImmigrationsId id, String gender, Integer birthPlaceCode, Integer birthPlace1, String birthPlace2, String chineseName, String birthDate, String passportNo, String permitNo, Integer permitWord, Integer fromTo, Integer immigrateType, String flightNo, String permitWordId, String fromToId, String issueNo, String prePermitNo, String firstRecvNo, Integer edCardOccupation, String nationOversea, Integer overseaResident, Integer entryReason, Integer immigrateType2, String followNo, String chiPersonId, Integer militaryType, String militaryNo, String keyinUserId, String keyinDate, String edCardMark, String remark, String reserved, Date establishTime, Date importTime, String deleteFlag, String mainUserId, String maintainProgramId, String maintainHost, Date lastUpdateTime, String englishName, String nation, String status, String sourceTable, String etlflag, String writeBackFlag, Date writeBackTime, Long serialNoLoginPk, String reason, String personId) {
        this.id = id;
        this.gender = gender;
        this.birthPlaceCode = birthPlaceCode;
        this.birthPlace1 = birthPlace1;
        this.birthPlace2 = birthPlace2;
        this.chineseName = chineseName;
        this.birthDate = birthDate;
        this.passportNo = passportNo;
        this.permitNo = permitNo;
        this.permitWord = permitWord;
        this.fromTo = fromTo;
        this.immigrateType = immigrateType;
        this.flightNo = flightNo;
        this.permitWordId = permitWordId;
        this.fromToId = fromToId;
        this.issueNo = issueNo;
        this.prePermitNo = prePermitNo;
        this.firstRecvNo = firstRecvNo;
        this.edCardOccupation = edCardOccupation;
        this.nationOversea = nationOversea;
        this.overseaResident = overseaResident;
        this.entryReason = entryReason;
        this.immigrateType2 = immigrateType2;
        this.followNo = followNo;
        this.chiPersonId = chiPersonId;
        this.militaryType = militaryType;
        this.militaryNo = militaryNo;
        this.keyinUserId = keyinUserId;
        this.keyinDate = keyinDate;
        this.edCardMark = edCardMark;
        this.remark = remark;
        this.reserved = reserved;
        this.establishTime = establishTime;
        this.importTime = importTime;
        this.deleteFlag = deleteFlag;
        this.mainUserId = mainUserId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
        this.englishName = englishName;
        this.nation = nation;
        this.status = status;
        this.sourceTable = sourceTable;
        this.etlflag = etlflag;
        this.writeBackFlag = writeBackFlag;
        this.writeBackTime = writeBackTime;
        this.serialNoLoginPk = serialNoLoginPk;
        this.reason = reason;
        this.personId = personId;
    }
   
    @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="immigrateDate", column=@Column(name="ImmigrateDate", nullable=false, length=8) ), 
        @AttributeOverride(name="edCardNo", column=@Column(name="EdCardNo", nullable=false, length=10) ), 
        @AttributeOverride(name="immigrateSeq", column=@Column(name="ImmigrateSeq", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="port", column=@Column(name="Port", nullable=false, length=2) ), 
        @AttributeOverride(name="serialNo", column=@Column(name="SerialNo", nullable=false, precision=10, scale=0) ) } )
    public NoMatchImmigrationsId getId() {
        return this.id;
    }
    
    public void setId(NoMatchImmigrationsId id) {
        this.id = id;
    }

    
    @Column(name="Gender", nullable=false, length=1)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="BirthPlaceCode", nullable=false, precision=1, scale=0)
    public Integer getBirthPlaceCode() {
        return this.birthPlaceCode;
    }
    
    public void setBirthPlaceCode(Integer birthPlaceCode) {
        this.birthPlaceCode = birthPlaceCode;
    }

    
    @Column(name="BirthPlace1", nullable=false, precision=3, scale=0)
    public Integer getBirthPlace1() {
        return this.birthPlace1;
    }
    
    public void setBirthPlace1(Integer birthPlace1) {
        this.birthPlace1 = birthPlace1;
    }

    
    @Column(name="BirthPlace2", length=16)
    public String getBirthPlace2() {
        return this.birthPlace2;
    }
    
    public void setBirthPlace2(String birthPlace2) {
        this.birthPlace2 = birthPlace2;
    }

    
    @Column(name="ChineseName", nullable=false, length=80)
    public String getChineseName() {
        return this.chineseName;
    }
    
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    
    @Column(name="BirthDate", nullable=false, length=8)
    public String getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="PassportNo", length=15)
    public String getPassportNo() {
        return this.passportNo;
    }
    
    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }

    
    @Column(name="PermitNo", length=12)
    public String getPermitNo() {
        return this.permitNo;
    }
    
    public void setPermitNo(String permitNo) {
        this.permitNo = permitNo;
    }

    
    @Column(name="PermitWord", precision=2, scale=0)
    public Integer getPermitWord() {
        return this.permitWord;
    }
    
    public void setPermitWord(Integer permitWord) {
        this.permitWord = permitWord;
    }

    
    @Column(name="FromTo", precision=3, scale=0)
    public Integer getFromTo() {
        return this.fromTo;
    }
    
    public void setFromTo(Integer fromTo) {
        this.fromTo = fromTo;
    }

    
    @Column(name="ImmigrateType", precision=1, scale=0)
    public Integer getImmigrateType() {
        return this.immigrateType;
    }
    
    public void setImmigrateType(Integer immigrateType) {
        this.immigrateType = immigrateType;
    }

    
    @Column(name="FlightNo", nullable=false, length=20)
    public String getFlightNo() {
        return this.flightNo;
    }
    
    public void setFlightNo(String flightNo) {
        this.flightNo = flightNo;
    }

    
    @Column(name="PermitWordId", length=12)
    public String getPermitWordId() {
        return this.permitWordId;
    }
    
    public void setPermitWordId(String permitWordId) {
        this.permitWordId = permitWordId;
    }

    
    @Column(name="FromToId", length=12)
    public String getFromToId() {
        return this.fromToId;
    }
    
    public void setFromToId(String fromToId) {
        this.fromToId = fromToId;
    }

    
    @Column(name="IssueNo", length=11)
    public String getIssueNo() {
        return this.issueNo;
    }
    
    public void setIssueNo(String issueNo) {
        this.issueNo = issueNo;
    }

    
    @Column(name="PrePermitNo", length=12)
    public String getPrePermitNo() {
        return this.prePermitNo;
    }
    
    public void setPrePermitNo(String prePermitNo) {
        this.prePermitNo = prePermitNo;
    }

    
    @Column(name="FirstRecvNo", length=12)
    public String getFirstRecvNo() {
        return this.firstRecvNo;
    }
    
    public void setFirstRecvNo(String firstRecvNo) {
        this.firstRecvNo = firstRecvNo;
    }

    
    @Column(name="EdCardOccupation", precision=2, scale=0)
    public Integer getEdCardOccupation() {
        return this.edCardOccupation;
    }
    
    public void setEdCardOccupation(Integer edCardOccupation) {
        this.edCardOccupation = edCardOccupation;
    }

    
    @Column(name="NationOversea", length=1)
    public String getNationOversea() {
        return this.nationOversea;
    }
    
    public void setNationOversea(String nationOversea) {
        this.nationOversea = nationOversea;
    }

    
    @Column(name="OverseaResident", precision=3, scale=0)
    public Integer getOverseaResident() {
        return this.overseaResident;
    }
    
    public void setOverseaResident(Integer overseaResident) {
        this.overseaResident = overseaResident;
    }

    
    @Column(name="EntryReason", precision=3, scale=0)
    public Integer getEntryReason() {
        return this.entryReason;
    }
    
    public void setEntryReason(Integer entryReason) {
        this.entryReason = entryReason;
    }

    
    @Column(name="ImmigrateType2", precision=1, scale=0)
    public Integer getImmigrateType2() {
        return this.immigrateType2;
    }
    
    public void setImmigrateType2(Integer immigrateType2) {
        this.immigrateType2 = immigrateType2;
    }

    
    @Column(name="FollowNo", length=1)
    public String getFollowNo() {
        return this.followNo;
    }
    
    public void setFollowNo(String followNo) {
        this.followNo = followNo;
    }

    
    @Column(name="ChiPersonId", length=20)
    public String getChiPersonId() {
        return this.chiPersonId;
    }
    
    public void setChiPersonId(String chiPersonId) {
        this.chiPersonId = chiPersonId;
    }

    
    @Column(name="MilitaryType", precision=2, scale=0)
    public Integer getMilitaryType() {
        return this.militaryType;
    }
    
    public void setMilitaryType(Integer militaryType) {
        this.militaryType = militaryType;
    }

    
    @Column(name="MilitaryNo", length=8)
    public String getMilitaryNo() {
        return this.militaryNo;
    }
    
    public void setMilitaryNo(String militaryNo) {
        this.militaryNo = militaryNo;
    }

    
    @Column(name="KeyinUserId", length=5)
    public String getKeyinUserId() {
        return this.keyinUserId;
    }
    
    public void setKeyinUserId(String keyinUserId) {
        this.keyinUserId = keyinUserId;
    }

    
    @Column(name="KeyinDate", length=8)
    public String getKeyinDate() {
        return this.keyinDate;
    }
    
    public void setKeyinDate(String keyinDate) {
        this.keyinDate = keyinDate;
    }

    
    @Column(name="EdCardMark", length=1)
    public String getEdCardMark() {
        return this.edCardMark;
    }
    
    public void setEdCardMark(String edCardMark) {
        this.edCardMark = edCardMark;
    }

    
    @Column(name="Remark", length=120)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="Reserved", length=20)
    public String getReserved() {
        return this.reserved;
    }
    
    public void setReserved(String reserved) {
        this.reserved = reserved;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EstablishTime", length=23)
    public Date getEstablishTime() {
        return this.establishTime;
    }
    
    public void setEstablishTime(Date establishTime) {
        this.establishTime = establishTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ImportTime", length=23)
    public Date getImportTime() {
        return this.importTime;
    }
    
    public void setImportTime(Date importTime) {
        this.importTime = importTime;
    }

    
    @Column(name="DeleteFlag", nullable=false, length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    
    @Column(name="MainUserId", nullable=false, length=10)
    public String getMainUserId() {
        return this.mainUserId;
    }
    
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }

    
    @Column(name="MaintainProgramId", nullable=false, length=10)
    public String getMaintainProgramId() {
        return this.maintainProgramId;
    }
    
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    
    @Column(name="MaintainHost", nullable=false, length=2)
    public String getMaintainHost() {
        return this.maintainHost;
    }
    
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdateTime", nullable=false, length=23)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    
    @Column(name="EnglishName", length=50)
    public String getEnglishName() {
        return this.englishName;
    }
    
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    
    @Column(name="Nation", length=3)
    public String getNation() {
        return this.nation;
    }
    
    public void setNation(String nation) {
        this.nation = nation;
    }

    
    @Column(name="Status", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="SourceTable", length=24)
    public String getSourceTable() {
        return this.sourceTable;
    }
    
    public void setSourceTable(String sourceTable) {
        this.sourceTable = sourceTable;
    }

    
    @Column(name="ETLFlag", length=1)
    public String getEtlflag() {
        return this.etlflag;
    }
    
    public void setEtlflag(String etlflag) {
        this.etlflag = etlflag;
    }

    
    @Column(name="WriteBackFlag", length=1)
    public String getWriteBackFlag() {
        return this.writeBackFlag;
    }
    
    public void setWriteBackFlag(String writeBackFlag) {
        this.writeBackFlag = writeBackFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="WriteBackTime", length=23)
    public Date getWriteBackTime() {
        return this.writeBackTime;
    }
    
    public void setWriteBackTime(Date writeBackTime) {
        this.writeBackTime = writeBackTime;
    }

    
    @Column(name="SerialNoLoginPK", precision=10, scale=0)
    public Long getSerialNoLoginPk() {
        return this.serialNoLoginPk;
    }
    
    public void setSerialNoLoginPk(Long serialNoLoginPk) {
        this.serialNoLoginPk = serialNoLoginPk;
    }

    
    @Column(name="Reason", length=2)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    
    @Column(name="PersonId", length=20)
    public String getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(String personId) {
        this.personId = personId;
    }




}


