package gov.nia.nrs.domain.iis;



import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NoMatchEntryExitId generated by hbm2java
 */
@Embeddable
public class NoMatchEntryExitId  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private String immigrateDate;
    private String edCardNo;
    private Integer immigrateSeq;
    private String port;
    private Long serialNo;

    public NoMatchEntryExitId() {}

    public NoMatchEntryExitId(String immigrateDate, String edCardNo, Integer immigrateSeq, String port, Long serialNo) {
        this.immigrateDate = immigrateDate;
        this.edCardNo = edCardNo;
        this.immigrateSeq = immigrateSeq;
        this.port = port;
        this.serialNo = serialNo;
    }
   


    @Column(name="ImmigrateDate", nullable=false, length=8)
    public String getImmigrateDate() {
        return this.immigrateDate;
    }
    
    public void setImmigrateDate(String immigrateDate) {
        this.immigrateDate = immigrateDate;
    }


    @Column(name="EdCardNo", nullable=false, length=10)
    public String getEdCardNo() {
        return this.edCardNo;
    }
    
    public void setEdCardNo(String edCardNo) {
        this.edCardNo = edCardNo;
    }


    @Column(name="ImmigrateSeq", nullable=false, precision=5, scale=0)
    public Integer getImmigrateSeq() {
        return this.immigrateSeq;
    }
    
    public void setImmigrateSeq(Integer immigrateSeq) {
        this.immigrateSeq = immigrateSeq;
    }


    @Column(name="Port", nullable=false, length=2)
    public String getPort() {
        return this.port;
    }
    
    public void setPort(String port) {
        this.port = port;
    }


    @Column(name="SerialNo", nullable=false, precision=10, scale=0)
    public Long getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(Long serialNo) {
        this.serialNo = serialNo;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof NoMatchEntryExitId) ) return false;
		NoMatchEntryExitId castOther = ( NoMatchEntryExitId ) other; 
         
		return ( (this.getImmigrateDate()==castOther.getImmigrateDate()) || ( this.getImmigrateDate()!=null && castOther.getImmigrateDate()!=null && this.getImmigrateDate().equals(castOther.getImmigrateDate()) ) )
 && ( (this.getEdCardNo()==castOther.getEdCardNo()) || ( this.getEdCardNo()!=null && castOther.getEdCardNo()!=null && this.getEdCardNo().equals(castOther.getEdCardNo()) ) )
 && ( (this.getImmigrateSeq()==castOther.getImmigrateSeq()) || ( this.getImmigrateSeq()!=null && castOther.getImmigrateSeq()!=null && this.getImmigrateSeq().equals(castOther.getImmigrateSeq()) ) )
 && ( (this.getPort()==castOther.getPort()) || ( this.getPort()!=null && castOther.getPort()!=null && this.getPort().equals(castOther.getPort()) ) )
 && ( (this.getSerialNo()==castOther.getSerialNo()) || ( this.getSerialNo()!=null && castOther.getSerialNo()!=null && this.getSerialNo().equals(castOther.getSerialNo()) ) );
    }
   
    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getImmigrateDate() == null ? 0 : this.getImmigrateDate().hashCode() );
        result = 37 * result + ( getEdCardNo() == null ? 0 : this.getEdCardNo().hashCode() );
        result = 37 * result + ( getImmigrateSeq() == null ? 0 : this.getImmigrateSeq().hashCode() );
        result = 37 * result + ( getPort() == null ? 0 : this.getPort().hashCode() );
        result = 37 * result + ( getSerialNo() == null ? 0 : this.getSerialNo().hashCode() );
        return result;
    }   


}


