package gov.nia.nrs.domain.iis;



import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Slpermit generated by hbm2java
 */
@Entity
@Table(name="SLPermit")
public class Slpermit  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private SlpermitId id;

    public Slpermit() {}

    public Slpermit(SlpermitId id) {
        this.id = id;
    }
   
    @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="serial", column=@Column(name="Serial", nullable=false, length=10) ), 
        @AttributeOverride(name="permitNum", column=@Column(name="PermitNum", nullable=false, length=15) ), 
        @AttributeOverride(name="stockId", column=@Column(name="StockId", nullable=false, length=12) ), 
        @AttributeOverride(name="keeperId", column=@Column(name="KeeperId", nullable=false, length=5) ), 
        @AttributeOverride(name="sstatus", column=@Column(name="Sstatus", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="pstatus", column=@Column(name="Pstatus", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="lastinDate", column=@Column(name="LastinDate", length=23) ), 
        @AttributeOverride(name="lastoutDate", column=@Column(name="LastoutDate", length=23) ), 
        @AttributeOverride(name="printerId", column=@Column(name="PrinterId", length=5) ), 
        @AttributeOverride(name="printTime", column=@Column(name="PrintTime", length=23) ), 
        @AttributeOverride(name="issueUser", column=@Column(name="IssueUser", length=5) ), 
        @AttributeOverride(name="issueTime", column=@Column(name="IssueTime", length=23) ), 
        @AttributeOverride(name="delivery", column=@Column(name="Delivery", length=1) ), 
        @AttributeOverride(name="loseMark", column=@Column(name="LoseMark", length=1) ), 
        @AttributeOverride(name="loseUser", column=@Column(name="LoseUser", length=5) ), 
        @AttributeOverride(name="loseTime", column=@Column(name="LoseTime", length=23) ), 
        @AttributeOverride(name="invalid", column=@Column(name="Invalid", length=1) ), 
        @AttributeOverride(name="invalidUser", column=@Column(name="InvalidUser", length=5) ), 
        @AttributeOverride(name="invalidTime", column=@Column(name="InvalidTime", length=23) ), 
        @AttributeOverride(name="destoryUser", column=@Column(name="DestoryUser", length=5) ), 
        @AttributeOverride(name="destoryTime", column=@Column(name="DestoryTime", length=23) ), 
        @AttributeOverride(name="cname", column=@Column(name="Cname", length=80) ), 
        @AttributeOverride(name="ename", column=@Column(name="Ename", length=50) ), 
        @AttributeOverride(name="passport", column=@Column(name="Passport", length=10) ), 
        @AttributeOverride(name="permitType", column=@Column(name="PermitType", length=5) ), 
        @AttributeOverride(name="receipt", column=@Column(name="Receipt", length=20) ), 
        @AttributeOverride(name="expense", column=@Column(name="Expense", precision=10, scale=0) ), 
        @AttributeOverride(name="permitId", column=@Column(name="PermitId", nullable=false, length=5) ), 
        @AttributeOverride(name="deptId", column=@Column(name="DeptId", length=4) ), 
        @AttributeOverride(name="immi", column=@Column(name="Immi", nullable=false, length=1) ), 
        @AttributeOverride(name="printDeptId", column=@Column(name="PrintDeptId", length=4) ), 
        @AttributeOverride(name="issueDeptId", column=@Column(name="IssueDeptId", length=4) ), 
        @AttributeOverride(name="issueRemark", column=@Column(name="IssueRemark", length=40) ), 
        @AttributeOverride(name="transNum", column=@Column(name="TransNum", length=14) ), 
        @AttributeOverride(name="applyDate", column=@Column(name="ApplyDate", length=8) ), 
        @AttributeOverride(name="takeWay", column=@Column(name="TakeWay", length=1) ), 
        @AttributeOverride(name="maintainProgramId", column=@Column(name="MaintainProgramId", length=20) ), 
        @AttributeOverride(name="importTime", column=@Column(name="ImportTime", length=23) ), 
        @AttributeOverride(name="deleteFlag", column=@Column(name="DeleteFlag", length=1) ), 
        @AttributeOverride(name="verifyId", column=@Column(name="VerifyId", length=10) ), 
        @AttributeOverride(name="verifyTime", column=@Column(name="VerifyTime", length=23) ), 
        @AttributeOverride(name="createUserId", column=@Column(name="CreateUserId", length=10) ), 
        @AttributeOverride(name="createDeptId", column=@Column(name="CreateDeptId", length=4) ), 
        @AttributeOverride(name="createTime", column=@Column(name="CreateTime", length=23) ), 
        @AttributeOverride(name="mainUserId", column=@Column(name="MainUserId", length=10) ), 
        @AttributeOverride(name="maintainDeptId", column=@Column(name="MaintainDeptId", length=4) ), 
        @AttributeOverride(name="maintainHost", column=@Column(name="MaintainHost", length=25) ), 
        @AttributeOverride(name="lastUpdateTime", column=@Column(name="LastUpdateTime", length=23) ), 
        @AttributeOverride(name="receiveNo", column=@Column(name="ReceiveNo", length=12) ), 
        @AttributeOverride(name="revokeMark", column=@Column(name="RevokeMark", length=1) ), 
        @AttributeOverride(name="revokeUser", column=@Column(name="RevokeUser", length=5) ), 
        @AttributeOverride(name="revokeTime", column=@Column(name="RevokeTime", length=23) ), 
        @AttributeOverride(name="txnMark", column=@Column(name="TxnMark") ), 
        @AttributeOverride(name="syncTime", column=@Column(name="SyncTime", length=23) ), 
        @AttributeOverride(name="submitDeptId", column=@Column(name="SubmitDeptId", length=4) ) } )
    public SlpermitId getId() {
        return this.id;
    }
    
    public void setId(SlpermitId id) {
        this.id = id;
    }




}


