package gov.nia.nrs.domain.iis;



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SlpermitId generated by hbm2java
 */
@Embeddable
public class SlpermitId  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private String serial;
    private String permitNum;
    private String stockId;
    private String keeperId;
    private Integer sstatus;
    private Integer pstatus;
    private Date lastinDate;
    private Date lastoutDate;
    private String printerId;
    private Date printTime;
    private String issueUser;
    private Date issueTime;
    private String delivery;
    private String loseMark;
    private String loseUser;
    private Date loseTime;
    private String invalid;
    private String invalidUser;
    private Date invalidTime;
    private String destoryUser;
    private Date destoryTime;
    private String cname;
    private String ename;
    private String passport;
    private String permitType;
    private String receipt;
    private Long expense;
    private String permitId;
    private String deptId;
    private String immi;
    private String printDeptId;
    private String issueDeptId;
    private String issueRemark;
    private String transNum;
    private String applyDate;
    private String takeWay;
    private String maintainProgramId;
    private Date importTime;
    private String deleteFlag;
    private String verifyId;
    private Date verifyTime;
    private String createUserId;
    private String createDeptId;
    private Date createTime;
    private String mainUserId;
    private String maintainDeptId;
    private String maintainHost;
    private Date lastUpdateTime;
    private String receiveNo;
    private String revokeMark;
    private String revokeUser;
    private Date revokeTime;
    private Long txnMark;
    private Date syncTime;
    private String submitDeptId;

    public SlpermitId() {}

	
    public SlpermitId(String serial, String permitNum, String stockId, String keeperId, Integer sstatus, Integer pstatus, String permitId, String immi) {
        this.serial = serial;
        this.permitNum = permitNum;
        this.stockId = stockId;
        this.keeperId = keeperId;
        this.sstatus = sstatus;
        this.pstatus = pstatus;
        this.permitId = permitId;
        this.immi = immi;
    }
    public SlpermitId(String serial, String permitNum, String stockId, String keeperId, Integer sstatus, Integer pstatus, Date lastinDate, Date lastoutDate, String printerId, Date printTime, String issueUser, Date issueTime, String delivery, String loseMark, String loseUser, Date loseTime, String invalid, String invalidUser, Date invalidTime, String destoryUser, Date destoryTime, String cname, String ename, String passport, String permitType, String receipt, Long expense, String permitId, String deptId, String immi, String printDeptId, String issueDeptId, String issueRemark, String transNum, String applyDate, String takeWay, String maintainProgramId, Date importTime, String deleteFlag, String verifyId, Date verifyTime, String createUserId, String createDeptId, Date createTime, String mainUserId, String maintainDeptId, String maintainHost, Date lastUpdateTime, String receiveNo, String revokeMark, String revokeUser, Date revokeTime, Long txnMark, Date syncTime, String submitDeptId) {
        this.serial = serial;
        this.permitNum = permitNum;
        this.stockId = stockId;
        this.keeperId = keeperId;
        this.sstatus = sstatus;
        this.pstatus = pstatus;
        this.lastinDate = lastinDate;
        this.lastoutDate = lastoutDate;
        this.printerId = printerId;
        this.printTime = printTime;
        this.issueUser = issueUser;
        this.issueTime = issueTime;
        this.delivery = delivery;
        this.loseMark = loseMark;
        this.loseUser = loseUser;
        this.loseTime = loseTime;
        this.invalid = invalid;
        this.invalidUser = invalidUser;
        this.invalidTime = invalidTime;
        this.destoryUser = destoryUser;
        this.destoryTime = destoryTime;
        this.cname = cname;
        this.ename = ename;
        this.passport = passport;
        this.permitType = permitType;
        this.receipt = receipt;
        this.expense = expense;
        this.permitId = permitId;
        this.deptId = deptId;
        this.immi = immi;
        this.printDeptId = printDeptId;
        this.issueDeptId = issueDeptId;
        this.issueRemark = issueRemark;
        this.transNum = transNum;
        this.applyDate = applyDate;
        this.takeWay = takeWay;
        this.maintainProgramId = maintainProgramId;
        this.importTime = importTime;
        this.deleteFlag = deleteFlag;
        this.verifyId = verifyId;
        this.verifyTime = verifyTime;
        this.createUserId = createUserId;
        this.createDeptId = createDeptId;
        this.createTime = createTime;
        this.mainUserId = mainUserId;
        this.maintainDeptId = maintainDeptId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
        this.receiveNo = receiveNo;
        this.revokeMark = revokeMark;
        this.revokeUser = revokeUser;
        this.revokeTime = revokeTime;
        this.txnMark = txnMark;
        this.syncTime = syncTime;
        this.submitDeptId = submitDeptId;
    }
   


    @Column(name="Serial", nullable=false, length=10)
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }


    @Column(name="PermitNum", nullable=false, length=15)
    public String getPermitNum() {
        return this.permitNum;
    }
    
    public void setPermitNum(String permitNum) {
        this.permitNum = permitNum;
    }


    @Column(name="StockId", nullable=false, length=12)
    public String getStockId() {
        return this.stockId;
    }
    
    public void setStockId(String stockId) {
        this.stockId = stockId;
    }


    @Column(name="KeeperId", nullable=false, length=5)
    public String getKeeperId() {
        return this.keeperId;
    }
    
    public void setKeeperId(String keeperId) {
        this.keeperId = keeperId;
    }


    @Column(name="Sstatus", nullable=false, precision=1, scale=0)
    public Integer getSstatus() {
        return this.sstatus;
    }
    
    public void setSstatus(Integer sstatus) {
        this.sstatus = sstatus;
    }


    @Column(name="Pstatus", nullable=false, precision=1, scale=0)
    public Integer getPstatus() {
        return this.pstatus;
    }
    
    public void setPstatus(Integer pstatus) {
        this.pstatus = pstatus;
    }


    @Column(name="LastinDate", length=23)
    public Date getLastinDate() {
        return this.lastinDate;
    }
    
    public void setLastinDate(Date lastinDate) {
        this.lastinDate = lastinDate;
    }


    @Column(name="LastoutDate", length=23)
    public Date getLastoutDate() {
        return this.lastoutDate;
    }
    
    public void setLastoutDate(Date lastoutDate) {
        this.lastoutDate = lastoutDate;
    }


    @Column(name="PrinterId", length=5)
    public String getPrinterId() {
        return this.printerId;
    }
    
    public void setPrinterId(String printerId) {
        this.printerId = printerId;
    }


    @Column(name="PrintTime", length=23)
    public Date getPrintTime() {
        return this.printTime;
    }
    
    public void setPrintTime(Date printTime) {
        this.printTime = printTime;
    }


    @Column(name="IssueUser", length=5)
    public String getIssueUser() {
        return this.issueUser;
    }
    
    public void setIssueUser(String issueUser) {
        this.issueUser = issueUser;
    }


    @Column(name="IssueTime", length=23)
    public Date getIssueTime() {
        return this.issueTime;
    }
    
    public void setIssueTime(Date issueTime) {
        this.issueTime = issueTime;
    }


    @Column(name="Delivery", length=1)
    public String getDelivery() {
        return this.delivery;
    }
    
    public void setDelivery(String delivery) {
        this.delivery = delivery;
    }


    @Column(name="LoseMark", length=1)
    public String getLoseMark() {
        return this.loseMark;
    }
    
    public void setLoseMark(String loseMark) {
        this.loseMark = loseMark;
    }


    @Column(name="LoseUser", length=5)
    public String getLoseUser() {
        return this.loseUser;
    }
    
    public void setLoseUser(String loseUser) {
        this.loseUser = loseUser;
    }


    @Column(name="LoseTime", length=23)
    public Date getLoseTime() {
        return this.loseTime;
    }
    
    public void setLoseTime(Date loseTime) {
        this.loseTime = loseTime;
    }


    @Column(name="Invalid", length=1)
    public String getInvalid() {
        return this.invalid;
    }
    
    public void setInvalid(String invalid) {
        this.invalid = invalid;
    }


    @Column(name="InvalidUser", length=5)
    public String getInvalidUser() {
        return this.invalidUser;
    }
    
    public void setInvalidUser(String invalidUser) {
        this.invalidUser = invalidUser;
    }


    @Column(name="InvalidTime", length=23)
    public Date getInvalidTime() {
        return this.invalidTime;
    }
    
    public void setInvalidTime(Date invalidTime) {
        this.invalidTime = invalidTime;
    }


    @Column(name="DestoryUser", length=5)
    public String getDestoryUser() {
        return this.destoryUser;
    }
    
    public void setDestoryUser(String destoryUser) {
        this.destoryUser = destoryUser;
    }


    @Column(name="DestoryTime", length=23)
    public Date getDestoryTime() {
        return this.destoryTime;
    }
    
    public void setDestoryTime(Date destoryTime) {
        this.destoryTime = destoryTime;
    }


    @Column(name="Cname", length=80)
    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }


    @Column(name="Ename", length=50)
    public String getEname() {
        return this.ename;
    }
    
    public void setEname(String ename) {
        this.ename = ename;
    }


    @Column(name="Passport", length=10)
    public String getPassport() {
        return this.passport;
    }
    
    public void setPassport(String passport) {
        this.passport = passport;
    }


    @Column(name="PermitType", length=5)
    public String getPermitType() {
        return this.permitType;
    }
    
    public void setPermitType(String permitType) {
        this.permitType = permitType;
    }


    @Column(name="Receipt", length=20)
    public String getReceipt() {
        return this.receipt;
    }
    
    public void setReceipt(String receipt) {
        this.receipt = receipt;
    }


    @Column(name="Expense", precision=10, scale=0)
    public Long getExpense() {
        return this.expense;
    }
    
    public void setExpense(Long expense) {
        this.expense = expense;
    }


    @Column(name="PermitId", nullable=false, length=5)
    public String getPermitId() {
        return this.permitId;
    }
    
    public void setPermitId(String permitId) {
        this.permitId = permitId;
    }


    @Column(name="DeptId", length=4)
    public String getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }


    @Column(name="Immi", nullable=false, length=1)
    public String getImmi() {
        return this.immi;
    }
    
    public void setImmi(String immi) {
        this.immi = immi;
    }


    @Column(name="PrintDeptId", length=4)
    public String getPrintDeptId() {
        return this.printDeptId;
    }
    
    public void setPrintDeptId(String printDeptId) {
        this.printDeptId = printDeptId;
    }


    @Column(name="IssueDeptId", length=4)
    public String getIssueDeptId() {
        return this.issueDeptId;
    }
    
    public void setIssueDeptId(String issueDeptId) {
        this.issueDeptId = issueDeptId;
    }


    @Column(name="IssueRemark", length=40)
    public String getIssueRemark() {
        return this.issueRemark;
    }
    
    public void setIssueRemark(String issueRemark) {
        this.issueRemark = issueRemark;
    }


    @Column(name="TransNum", length=14)
    public String getTransNum() {
        return this.transNum;
    }
    
    public void setTransNum(String transNum) {
        this.transNum = transNum;
    }


    @Column(name="ApplyDate", length=8)
    public String getApplyDate() {
        return this.applyDate;
    }
    
    public void setApplyDate(String applyDate) {
        this.applyDate = applyDate;
    }


    @Column(name="TakeWay", length=1)
    public String getTakeWay() {
        return this.takeWay;
    }
    
    public void setTakeWay(String takeWay) {
        this.takeWay = takeWay;
    }


    @Column(name="MaintainProgramId", length=20)
    public String getMaintainProgramId() {
        return this.maintainProgramId;
    }
    
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }


    @Column(name="ImportTime", length=23)
    public Date getImportTime() {
        return this.importTime;
    }
    
    public void setImportTime(Date importTime) {
        this.importTime = importTime;
    }


    @Column(name="DeleteFlag", length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }


    @Column(name="VerifyId", length=10)
    public String getVerifyId() {
        return this.verifyId;
    }
    
    public void setVerifyId(String verifyId) {
        this.verifyId = verifyId;
    }


    @Column(name="VerifyTime", length=23)
    public Date getVerifyTime() {
        return this.verifyTime;
    }
    
    public void setVerifyTime(Date verifyTime) {
        this.verifyTime = verifyTime;
    }


    @Column(name="CreateUserId", length=10)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }


    @Column(name="CreateDeptId", length=4)
    public String getCreateDeptId() {
        return this.createDeptId;
    }
    
    public void setCreateDeptId(String createDeptId) {
        this.createDeptId = createDeptId;
    }


    @Column(name="CreateTime", length=23)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }


    @Column(name="MainUserId", length=10)
    public String getMainUserId() {
        return this.mainUserId;
    }
    
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }


    @Column(name="MaintainDeptId", length=4)
    public String getMaintainDeptId() {
        return this.maintainDeptId;
    }
    
    public void setMaintainDeptId(String maintainDeptId) {
        this.maintainDeptId = maintainDeptId;
    }


    @Column(name="MaintainHost", length=25)
    public String getMaintainHost() {
        return this.maintainHost;
    }
    
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }


    @Column(name="LastUpdateTime", length=23)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }


    @Column(name="ReceiveNo", length=12)
    public String getReceiveNo() {
        return this.receiveNo;
    }
    
    public void setReceiveNo(String receiveNo) {
        this.receiveNo = receiveNo;
    }


    @Column(name="RevokeMark", length=1)
    public String getRevokeMark() {
        return this.revokeMark;
    }
    
    public void setRevokeMark(String revokeMark) {
        this.revokeMark = revokeMark;
    }


    @Column(name="RevokeUser", length=5)
    public String getRevokeUser() {
        return this.revokeUser;
    }
    
    public void setRevokeUser(String revokeUser) {
        this.revokeUser = revokeUser;
    }


    @Column(name="RevokeTime", length=23)
    public Date getRevokeTime() {
        return this.revokeTime;
    }
    
    public void setRevokeTime(Date revokeTime) {
        this.revokeTime = revokeTime;
    }


    @Column(name="TxnMark")
    public Long getTxnMark() {
        return this.txnMark;
    }
    
    public void setTxnMark(Long txnMark) {
        this.txnMark = txnMark;
    }


    @Column(name="SyncTime", length=23)
    public Date getSyncTime() {
        return this.syncTime;
    }
    
    public void setSyncTime(Date syncTime) {
        this.syncTime = syncTime;
    }


    @Column(name="SubmitDeptId", length=4)
    public String getSubmitDeptId() {
        return this.submitDeptId;
    }
    
    public void setSubmitDeptId(String submitDeptId) {
        this.submitDeptId = submitDeptId;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof SlpermitId) ) return false;
		SlpermitId castOther = ( SlpermitId ) other; 
         
		return ( (this.getSerial()==castOther.getSerial()) || ( this.getSerial()!=null && castOther.getSerial()!=null && this.getSerial().equals(castOther.getSerial()) ) )
 && ( (this.getPermitNum()==castOther.getPermitNum()) || ( this.getPermitNum()!=null && castOther.getPermitNum()!=null && this.getPermitNum().equals(castOther.getPermitNum()) ) )
 && ( (this.getStockId()==castOther.getStockId()) || ( this.getStockId()!=null && castOther.getStockId()!=null && this.getStockId().equals(castOther.getStockId()) ) )
 && ( (this.getKeeperId()==castOther.getKeeperId()) || ( this.getKeeperId()!=null && castOther.getKeeperId()!=null && this.getKeeperId().equals(castOther.getKeeperId()) ) )
 && ( (this.getSstatus()==castOther.getSstatus()) || ( this.getSstatus()!=null && castOther.getSstatus()!=null && this.getSstatus().equals(castOther.getSstatus()) ) )
 && ( (this.getPstatus()==castOther.getPstatus()) || ( this.getPstatus()!=null && castOther.getPstatus()!=null && this.getPstatus().equals(castOther.getPstatus()) ) )
 && ( (this.getLastinDate()==castOther.getLastinDate()) || ( this.getLastinDate()!=null && castOther.getLastinDate()!=null && this.getLastinDate().equals(castOther.getLastinDate()) ) )
 && ( (this.getLastoutDate()==castOther.getLastoutDate()) || ( this.getLastoutDate()!=null && castOther.getLastoutDate()!=null && this.getLastoutDate().equals(castOther.getLastoutDate()) ) )
 && ( (this.getPrinterId()==castOther.getPrinterId()) || ( this.getPrinterId()!=null && castOther.getPrinterId()!=null && this.getPrinterId().equals(castOther.getPrinterId()) ) )
 && ( (this.getPrintTime()==castOther.getPrintTime()) || ( this.getPrintTime()!=null && castOther.getPrintTime()!=null && this.getPrintTime().equals(castOther.getPrintTime()) ) )
 && ( (this.getIssueUser()==castOther.getIssueUser()) || ( this.getIssueUser()!=null && castOther.getIssueUser()!=null && this.getIssueUser().equals(castOther.getIssueUser()) ) )
 && ( (this.getIssueTime()==castOther.getIssueTime()) || ( this.getIssueTime()!=null && castOther.getIssueTime()!=null && this.getIssueTime().equals(castOther.getIssueTime()) ) )
 && ( (this.getDelivery()==castOther.getDelivery()) || ( this.getDelivery()!=null && castOther.getDelivery()!=null && this.getDelivery().equals(castOther.getDelivery()) ) )
 && ( (this.getLoseMark()==castOther.getLoseMark()) || ( this.getLoseMark()!=null && castOther.getLoseMark()!=null && this.getLoseMark().equals(castOther.getLoseMark()) ) )
 && ( (this.getLoseUser()==castOther.getLoseUser()) || ( this.getLoseUser()!=null && castOther.getLoseUser()!=null && this.getLoseUser().equals(castOther.getLoseUser()) ) )
 && ( (this.getLoseTime()==castOther.getLoseTime()) || ( this.getLoseTime()!=null && castOther.getLoseTime()!=null && this.getLoseTime().equals(castOther.getLoseTime()) ) )
 && ( (this.getInvalid()==castOther.getInvalid()) || ( this.getInvalid()!=null && castOther.getInvalid()!=null && this.getInvalid().equals(castOther.getInvalid()) ) )
 && ( (this.getInvalidUser()==castOther.getInvalidUser()) || ( this.getInvalidUser()!=null && castOther.getInvalidUser()!=null && this.getInvalidUser().equals(castOther.getInvalidUser()) ) )
 && ( (this.getInvalidTime()==castOther.getInvalidTime()) || ( this.getInvalidTime()!=null && castOther.getInvalidTime()!=null && this.getInvalidTime().equals(castOther.getInvalidTime()) ) )
 && ( (this.getDestoryUser()==castOther.getDestoryUser()) || ( this.getDestoryUser()!=null && castOther.getDestoryUser()!=null && this.getDestoryUser().equals(castOther.getDestoryUser()) ) )
 && ( (this.getDestoryTime()==castOther.getDestoryTime()) || ( this.getDestoryTime()!=null && castOther.getDestoryTime()!=null && this.getDestoryTime().equals(castOther.getDestoryTime()) ) )
 && ( (this.getCname()==castOther.getCname()) || ( this.getCname()!=null && castOther.getCname()!=null && this.getCname().equals(castOther.getCname()) ) )
 && ( (this.getEname()==castOther.getEname()) || ( this.getEname()!=null && castOther.getEname()!=null && this.getEname().equals(castOther.getEname()) ) )
 && ( (this.getPassport()==castOther.getPassport()) || ( this.getPassport()!=null && castOther.getPassport()!=null && this.getPassport().equals(castOther.getPassport()) ) )
 && ( (this.getPermitType()==castOther.getPermitType()) || ( this.getPermitType()!=null && castOther.getPermitType()!=null && this.getPermitType().equals(castOther.getPermitType()) ) )
 && ( (this.getReceipt()==castOther.getReceipt()) || ( this.getReceipt()!=null && castOther.getReceipt()!=null && this.getReceipt().equals(castOther.getReceipt()) ) )
 && ( (this.getExpense()==castOther.getExpense()) || ( this.getExpense()!=null && castOther.getExpense()!=null && this.getExpense().equals(castOther.getExpense()) ) )
 && ( (this.getPermitId()==castOther.getPermitId()) || ( this.getPermitId()!=null && castOther.getPermitId()!=null && this.getPermitId().equals(castOther.getPermitId()) ) )
 && ( (this.getDeptId()==castOther.getDeptId()) || ( this.getDeptId()!=null && castOther.getDeptId()!=null && this.getDeptId().equals(castOther.getDeptId()) ) )
 && ( (this.getImmi()==castOther.getImmi()) || ( this.getImmi()!=null && castOther.getImmi()!=null && this.getImmi().equals(castOther.getImmi()) ) )
 && ( (this.getPrintDeptId()==castOther.getPrintDeptId()) || ( this.getPrintDeptId()!=null && castOther.getPrintDeptId()!=null && this.getPrintDeptId().equals(castOther.getPrintDeptId()) ) )
 && ( (this.getIssueDeptId()==castOther.getIssueDeptId()) || ( this.getIssueDeptId()!=null && castOther.getIssueDeptId()!=null && this.getIssueDeptId().equals(castOther.getIssueDeptId()) ) )
 && ( (this.getIssueRemark()==castOther.getIssueRemark()) || ( this.getIssueRemark()!=null && castOther.getIssueRemark()!=null && this.getIssueRemark().equals(castOther.getIssueRemark()) ) )
 && ( (this.getTransNum()==castOther.getTransNum()) || ( this.getTransNum()!=null && castOther.getTransNum()!=null && this.getTransNum().equals(castOther.getTransNum()) ) )
 && ( (this.getApplyDate()==castOther.getApplyDate()) || ( this.getApplyDate()!=null && castOther.getApplyDate()!=null && this.getApplyDate().equals(castOther.getApplyDate()) ) )
 && ( (this.getTakeWay()==castOther.getTakeWay()) || ( this.getTakeWay()!=null && castOther.getTakeWay()!=null && this.getTakeWay().equals(castOther.getTakeWay()) ) )
 && ( (this.getMaintainProgramId()==castOther.getMaintainProgramId()) || ( this.getMaintainProgramId()!=null && castOther.getMaintainProgramId()!=null && this.getMaintainProgramId().equals(castOther.getMaintainProgramId()) ) )
 && ( (this.getImportTime()==castOther.getImportTime()) || ( this.getImportTime()!=null && castOther.getImportTime()!=null && this.getImportTime().equals(castOther.getImportTime()) ) )
 && ( (this.getDeleteFlag()==castOther.getDeleteFlag()) || ( this.getDeleteFlag()!=null && castOther.getDeleteFlag()!=null && this.getDeleteFlag().equals(castOther.getDeleteFlag()) ) )
 && ( (this.getVerifyId()==castOther.getVerifyId()) || ( this.getVerifyId()!=null && castOther.getVerifyId()!=null && this.getVerifyId().equals(castOther.getVerifyId()) ) )
 && ( (this.getVerifyTime()==castOther.getVerifyTime()) || ( this.getVerifyTime()!=null && castOther.getVerifyTime()!=null && this.getVerifyTime().equals(castOther.getVerifyTime()) ) )
 && ( (this.getCreateUserId()==castOther.getCreateUserId()) || ( this.getCreateUserId()!=null && castOther.getCreateUserId()!=null && this.getCreateUserId().equals(castOther.getCreateUserId()) ) )
 && ( (this.getCreateDeptId()==castOther.getCreateDeptId()) || ( this.getCreateDeptId()!=null && castOther.getCreateDeptId()!=null && this.getCreateDeptId().equals(castOther.getCreateDeptId()) ) )
 && ( (this.getCreateTime()==castOther.getCreateTime()) || ( this.getCreateTime()!=null && castOther.getCreateTime()!=null && this.getCreateTime().equals(castOther.getCreateTime()) ) )
 && ( (this.getMainUserId()==castOther.getMainUserId()) || ( this.getMainUserId()!=null && castOther.getMainUserId()!=null && this.getMainUserId().equals(castOther.getMainUserId()) ) )
 && ( (this.getMaintainDeptId()==castOther.getMaintainDeptId()) || ( this.getMaintainDeptId()!=null && castOther.getMaintainDeptId()!=null && this.getMaintainDeptId().equals(castOther.getMaintainDeptId()) ) )
 && ( (this.getMaintainHost()==castOther.getMaintainHost()) || ( this.getMaintainHost()!=null && castOther.getMaintainHost()!=null && this.getMaintainHost().equals(castOther.getMaintainHost()) ) )
 && ( (this.getLastUpdateTime()==castOther.getLastUpdateTime()) || ( this.getLastUpdateTime()!=null && castOther.getLastUpdateTime()!=null && this.getLastUpdateTime().equals(castOther.getLastUpdateTime()) ) )
 && ( (this.getReceiveNo()==castOther.getReceiveNo()) || ( this.getReceiveNo()!=null && castOther.getReceiveNo()!=null && this.getReceiveNo().equals(castOther.getReceiveNo()) ) )
 && ( (this.getRevokeMark()==castOther.getRevokeMark()) || ( this.getRevokeMark()!=null && castOther.getRevokeMark()!=null && this.getRevokeMark().equals(castOther.getRevokeMark()) ) )
 && ( (this.getRevokeUser()==castOther.getRevokeUser()) || ( this.getRevokeUser()!=null && castOther.getRevokeUser()!=null && this.getRevokeUser().equals(castOther.getRevokeUser()) ) )
 && ( (this.getRevokeTime()==castOther.getRevokeTime()) || ( this.getRevokeTime()!=null && castOther.getRevokeTime()!=null && this.getRevokeTime().equals(castOther.getRevokeTime()) ) )
 && ( (this.getTxnMark()==castOther.getTxnMark()) || ( this.getTxnMark()!=null && castOther.getTxnMark()!=null && this.getTxnMark().equals(castOther.getTxnMark()) ) )
 && ( (this.getSyncTime()==castOther.getSyncTime()) || ( this.getSyncTime()!=null && castOther.getSyncTime()!=null && this.getSyncTime().equals(castOther.getSyncTime()) ) )
 && ( (this.getSubmitDeptId()==castOther.getSubmitDeptId()) || ( this.getSubmitDeptId()!=null && castOther.getSubmitDeptId()!=null && this.getSubmitDeptId().equals(castOther.getSubmitDeptId()) ) );
    }
   
    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getSerial() == null ? 0 : this.getSerial().hashCode() );
        result = 37 * result + ( getPermitNum() == null ? 0 : this.getPermitNum().hashCode() );
        result = 37 * result + ( getStockId() == null ? 0 : this.getStockId().hashCode() );
        result = 37 * result + ( getKeeperId() == null ? 0 : this.getKeeperId().hashCode() );
        result = 37 * result + ( getSstatus() == null ? 0 : this.getSstatus().hashCode() );
        result = 37 * result + ( getPstatus() == null ? 0 : this.getPstatus().hashCode() );
        result = 37 * result + ( getLastinDate() == null ? 0 : this.getLastinDate().hashCode() );
        result = 37 * result + ( getLastoutDate() == null ? 0 : this.getLastoutDate().hashCode() );
        result = 37 * result + ( getPrinterId() == null ? 0 : this.getPrinterId().hashCode() );
        result = 37 * result + ( getPrintTime() == null ? 0 : this.getPrintTime().hashCode() );
        result = 37 * result + ( getIssueUser() == null ? 0 : this.getIssueUser().hashCode() );
        result = 37 * result + ( getIssueTime() == null ? 0 : this.getIssueTime().hashCode() );
        result = 37 * result + ( getDelivery() == null ? 0 : this.getDelivery().hashCode() );
        result = 37 * result + ( getLoseMark() == null ? 0 : this.getLoseMark().hashCode() );
        result = 37 * result + ( getLoseUser() == null ? 0 : this.getLoseUser().hashCode() );
        result = 37 * result + ( getLoseTime() == null ? 0 : this.getLoseTime().hashCode() );
        result = 37 * result + ( getInvalid() == null ? 0 : this.getInvalid().hashCode() );
        result = 37 * result + ( getInvalidUser() == null ? 0 : this.getInvalidUser().hashCode() );
        result = 37 * result + ( getInvalidTime() == null ? 0 : this.getInvalidTime().hashCode() );
        result = 37 * result + ( getDestoryUser() == null ? 0 : this.getDestoryUser().hashCode() );
        result = 37 * result + ( getDestoryTime() == null ? 0 : this.getDestoryTime().hashCode() );
        result = 37 * result + ( getCname() == null ? 0 : this.getCname().hashCode() );
        result = 37 * result + ( getEname() == null ? 0 : this.getEname().hashCode() );
        result = 37 * result + ( getPassport() == null ? 0 : this.getPassport().hashCode() );
        result = 37 * result + ( getPermitType() == null ? 0 : this.getPermitType().hashCode() );
        result = 37 * result + ( getReceipt() == null ? 0 : this.getReceipt().hashCode() );
        result = 37 * result + ( getExpense() == null ? 0 : this.getExpense().hashCode() );
        result = 37 * result + ( getPermitId() == null ? 0 : this.getPermitId().hashCode() );
        result = 37 * result + ( getDeptId() == null ? 0 : this.getDeptId().hashCode() );
        result = 37 * result + ( getImmi() == null ? 0 : this.getImmi().hashCode() );
        result = 37 * result + ( getPrintDeptId() == null ? 0 : this.getPrintDeptId().hashCode() );
        result = 37 * result + ( getIssueDeptId() == null ? 0 : this.getIssueDeptId().hashCode() );
        result = 37 * result + ( getIssueRemark() == null ? 0 : this.getIssueRemark().hashCode() );
        result = 37 * result + ( getTransNum() == null ? 0 : this.getTransNum().hashCode() );
        result = 37 * result + ( getApplyDate() == null ? 0 : this.getApplyDate().hashCode() );
        result = 37 * result + ( getTakeWay() == null ? 0 : this.getTakeWay().hashCode() );
        result = 37 * result + ( getMaintainProgramId() == null ? 0 : this.getMaintainProgramId().hashCode() );
        result = 37 * result + ( getImportTime() == null ? 0 : this.getImportTime().hashCode() );
        result = 37 * result + ( getDeleteFlag() == null ? 0 : this.getDeleteFlag().hashCode() );
        result = 37 * result + ( getVerifyId() == null ? 0 : this.getVerifyId().hashCode() );
        result = 37 * result + ( getVerifyTime() == null ? 0 : this.getVerifyTime().hashCode() );
        result = 37 * result + ( getCreateUserId() == null ? 0 : this.getCreateUserId().hashCode() );
        result = 37 * result + ( getCreateDeptId() == null ? 0 : this.getCreateDeptId().hashCode() );
        result = 37 * result + ( getCreateTime() == null ? 0 : this.getCreateTime().hashCode() );
        result = 37 * result + ( getMainUserId() == null ? 0 : this.getMainUserId().hashCode() );
        result = 37 * result + ( getMaintainDeptId() == null ? 0 : this.getMaintainDeptId().hashCode() );
        result = 37 * result + ( getMaintainHost() == null ? 0 : this.getMaintainHost().hashCode() );
        result = 37 * result + ( getLastUpdateTime() == null ? 0 : this.getLastUpdateTime().hashCode() );
        result = 37 * result + ( getReceiveNo() == null ? 0 : this.getReceiveNo().hashCode() );
        result = 37 * result + ( getRevokeMark() == null ? 0 : this.getRevokeMark().hashCode() );
        result = 37 * result + ( getRevokeUser() == null ? 0 : this.getRevokeUser().hashCode() );
        result = 37 * result + ( getRevokeTime() == null ? 0 : this.getRevokeTime().hashCode() );
        result = 37 * result + ( getTxnMark() == null ? 0 : this.getTxnMark().hashCode() );
        result = 37 * result + ( getSyncTime() == null ? 0 : this.getSyncTime().hashCode() );
        result = 37 * result + ( getSubmitDeptId() == null ? 0 : this.getSubmitDeptId().hashCode() );
        return result;
    }   


}


