package gov.nia.nrs.domain.iis;



import java.sql.Clob;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SoldierApprove generated by hbm2java
 */
@Entity
@Table(name="SoldierApprove"
)
public class SoldierApprove  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private SoldierApproveId id;
    private String personId;
    private String chineseName;
    private String birthDate;
    private String receiptNo;
    private String approvalDate;
    private String expiredDate;
    private Integer mark;
    private String displayMark;
    private String filmNo;
    private String keyinUserId;
    private String keyinLoc;
    private String entrySchoolDate;
    private String exitSchoolDate;
    private Integer militaryType;
    private String netApplyType;
    private String netCaseNo;
    private String reserved;
    private Date establishTime;
    private Date importTime;
    private String deleteFlag;
    private String mainUserId;
    private String maintainProgramId;
    private String maintainHost;
    private Date lastUpdateTime;
    private String additional1;
    private String additional2;
    private String additional3;
    private Clob residentExcludeDateReason;
    private String remark;
    private String station;

    public SoldierApprove() {}

	
    public SoldierApprove(SoldierApproveId id, String personId, String chineseName, String receiptNo, String approvalDate, String expiredDate, Integer mark, String displayMark, String filmNo, String keyinUserId, String keyinLoc, String entrySchoolDate, String exitSchoolDate, Integer militaryType, String netApplyType, String netCaseNo, String deleteFlag, String mainUserId, String maintainProgramId, String maintainHost, Date lastUpdateTime) {
        this.id = id;
        this.personId = personId;
        this.chineseName = chineseName;
        this.receiptNo = receiptNo;
        this.approvalDate = approvalDate;
        this.expiredDate = expiredDate;
        this.mark = mark;
        this.displayMark = displayMark;
        this.filmNo = filmNo;
        this.keyinUserId = keyinUserId;
        this.keyinLoc = keyinLoc;
        this.entrySchoolDate = entrySchoolDate;
        this.exitSchoolDate = exitSchoolDate;
        this.militaryType = militaryType;
        this.netApplyType = netApplyType;
        this.netCaseNo = netCaseNo;
        this.deleteFlag = deleteFlag;
        this.mainUserId = mainUserId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
    }
    public SoldierApprove(SoldierApproveId id, String personId, String chineseName, String birthDate, String receiptNo, String approvalDate, String expiredDate, Integer mark, String displayMark, String filmNo, String keyinUserId, String keyinLoc, String entrySchoolDate, String exitSchoolDate, Integer militaryType, String netApplyType, String netCaseNo, String reserved, Date establishTime, Date importTime, String deleteFlag, String mainUserId, String maintainProgramId, String maintainHost, Date lastUpdateTime, String additional1, String additional2, String additional3, Clob residentExcludeDateReason, String remark, String station) {
        this.id = id;
        this.personId = personId;
        this.chineseName = chineseName;
        this.birthDate = birthDate;
        this.receiptNo = receiptNo;
        this.approvalDate = approvalDate;
        this.expiredDate = expiredDate;
        this.mark = mark;
        this.displayMark = displayMark;
        this.filmNo = filmNo;
        this.keyinUserId = keyinUserId;
        this.keyinLoc = keyinLoc;
        this.entrySchoolDate = entrySchoolDate;
        this.exitSchoolDate = exitSchoolDate;
        this.militaryType = militaryType;
        this.netApplyType = netApplyType;
        this.netCaseNo = netCaseNo;
        this.reserved = reserved;
        this.establishTime = establishTime;
        this.importTime = importTime;
        this.deleteFlag = deleteFlag;
        this.mainUserId = mainUserId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
        this.additional1 = additional1;
        this.additional2 = additional2;
        this.additional3 = additional3;
        this.residentExcludeDateReason = residentExcludeDateReason;
        this.remark = remark;
        this.station = station;
    }
   
    @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="passportNo", column=@Column(name="PassportNo", nullable=false, length=12) ), 
        @AttributeOverride(name="serialNo", column=@Column(name="SerialNo", nullable=false, precision=3, scale=0) ) } )
    public SoldierApproveId getId() {
        return this.id;
    }
    
    public void setId(SoldierApproveId id) {
        this.id = id;
    }

    
    @Column(name="PersonId", nullable=false, length=10)
    public String getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(String personId) {
        this.personId = personId;
    }

    
    @Column(name="ChineseName", nullable=false, length=80)
    public String getChineseName() {
        return this.chineseName;
    }
    
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    
    @Column(name="BirthDate", nullable=false, length=8)
    public String getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="ReceiptNo", nullable=false, length=12)
    public String getReceiptNo() {
        return this.receiptNo;
    }
    
    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo;
    }

    
    @Column(name="ApprovalDate", nullable=false, length=8)
    public String getApprovalDate() {
        return this.approvalDate;
    }
    
    public void setApprovalDate(String approvalDate) {
        this.approvalDate = approvalDate;
    }

    
    @Column(name="ExpiredDate", nullable=false, length=8)
    public String getExpiredDate() {
        return this.expiredDate;
    }
    
    public void setExpiredDate(String expiredDate) {
        this.expiredDate = expiredDate;
    }

    
    @Column(name="Mark", nullable=false, precision=3, scale=0)
    public Integer getMark() {
        return this.mark;
    }
    
    public void setMark(Integer mark) {
        this.mark = mark;
    }

    
    @Column(name="DisplayMark", nullable=false, length=1)
    public String getDisplayMark() {
        return this.displayMark;
    }
    
    public void setDisplayMark(String displayMark) {
        this.displayMark = displayMark;
    }

    
    @Column(name="FilmNo", nullable=false, length=11)
    public String getFilmNo() {
        return this.filmNo;
    }
    
    public void setFilmNo(String filmNo) {
        this.filmNo = filmNo;
    }

    
    @Column(name="KeyinUserId", nullable=false, length=5)
    public String getKeyinUserId() {
        return this.keyinUserId;
    }
    
    public void setKeyinUserId(String keyinUserId) {
        this.keyinUserId = keyinUserId;
    }

    
    @Column(name="KeyinLoc", nullable=false, length=2)
    public String getKeyinLoc() {
        return this.keyinLoc;
    }
    
    public void setKeyinLoc(String keyinLoc) {
        this.keyinLoc = keyinLoc;
    }

    
    @Column(name="EntrySchoolDate", nullable=false, length=8)
    public String getEntrySchoolDate() {
        return this.entrySchoolDate;
    }
    
    public void setEntrySchoolDate(String entrySchoolDate) {
        this.entrySchoolDate = entrySchoolDate;
    }

    
    @Column(name="ExitSchoolDate", nullable=false, length=8)
    public String getExitSchoolDate() {
        return this.exitSchoolDate;
    }
    
    public void setExitSchoolDate(String exitSchoolDate) {
        this.exitSchoolDate = exitSchoolDate;
    }

    
    @Column(name="MilitaryType", nullable=false, precision=2, scale=0)
    public Integer getMilitaryType() {
        return this.militaryType;
    }
    
    public void setMilitaryType(Integer militaryType) {
        this.militaryType = militaryType;
    }

    
    @Column(name="NetApplyType", nullable=false, length=1)
    public String getNetApplyType() {
        return this.netApplyType;
    }
    
    public void setNetApplyType(String netApplyType) {
        this.netApplyType = netApplyType;
    }

    
    @Column(name="NetCaseNo", nullable=false, length=18)
    public String getNetCaseNo() {
        return this.netCaseNo;
    }
    
    public void setNetCaseNo(String netCaseNo) {
        this.netCaseNo = netCaseNo;
    }

    
    @Column(name="Reserved", length=30)
    public String getReserved() {
        return this.reserved;
    }
    
    public void setReserved(String reserved) {
        this.reserved = reserved;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EstablishTime", length=23)
    public Date getEstablishTime() {
        return this.establishTime;
    }
    
    public void setEstablishTime(Date establishTime) {
        this.establishTime = establishTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ImportTime", length=23)
    public Date getImportTime() {
        return this.importTime;
    }
    
    public void setImportTime(Date importTime) {
        this.importTime = importTime;
    }

    
    @Column(name="DeleteFlag", nullable=false, length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    
    @Column(name="MainUserId", nullable=false, length=10)
    public String getMainUserId() {
        return this.mainUserId;
    }
    
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }

    
    @Column(name="MaintainProgramId", nullable=false, length=10)
    public String getMaintainProgramId() {
        return this.maintainProgramId;
    }
    
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    
    @Column(name="MaintainHost", nullable=false, length=2)
    public String getMaintainHost() {
        return this.maintainHost;
    }
    
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdateTime", nullable=false, length=23)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    
    @Column(name="Additional1", length=3)
    public String getAdditional1() {
        return this.additional1;
    }
    
    public void setAdditional1(String additional1) {
        this.additional1 = additional1;
    }

    
    @Column(name="Additional2", length=3)
    public String getAdditional2() {
        return this.additional2;
    }
    
    public void setAdditional2(String additional2) {
        this.additional2 = additional2;
    }

    
    @Column(name="Additional3", length=3)
    public String getAdditional3() {
        return this.additional3;
    }
    
    public void setAdditional3(String additional3) {
        this.additional3 = additional3;
    }

    
    @Column(name="ResidentExcludeDateReason")
    public Clob getResidentExcludeDateReason() {
        return this.residentExcludeDateReason;
    }
    
    public void setResidentExcludeDateReason(Clob residentExcludeDateReason) {
        this.residentExcludeDateReason = residentExcludeDateReason;
    }

    
    @Column(name="Remark", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="Station", length=4)
    public String getStation() {
        return this.station;
    }
    
    public void setStation(String station) {
        this.station = station;
    }




}


