package gov.nia.nrs.domain.iis;



import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SoldierApproveId generated by hbm2java
 */
@Embeddable
public class SoldierApproveId  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private String passportNo;
    private Integer serialNo;

    public SoldierApproveId() {}

    public SoldierApproveId(String passportNo, Integer serialNo) {
        this.passportNo = passportNo;
        this.serialNo = serialNo;
    }
   


    @Column(name="PassportNo", nullable=false, length=12)
    public String getPassportNo() {
        return this.passportNo;
    }
    
    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }


    @Column(name="SerialNo", nullable=false, precision=3, scale=0)
    public Integer getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(Integer serialNo) {
        this.serialNo = serialNo;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof SoldierApproveId) ) return false;
		SoldierApproveId castOther = ( SoldierApproveId ) other; 
         
		return ( (this.getPassportNo()==castOther.getPassportNo()) || ( this.getPassportNo()!=null && castOther.getPassportNo()!=null && this.getPassportNo().equals(castOther.getPassportNo()) ) )
 && ( (this.getSerialNo()==castOther.getSerialNo()) || ( this.getSerialNo()!=null && castOther.getSerialNo()!=null && this.getSerialNo().equals(castOther.getSerialNo()) ) );
    }
   
    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getPassportNo() == null ? 0 : this.getPassportNo().hashCode() );
        result = 37 * result + ( getSerialNo() == null ? 0 : this.getSerialNo().hashCode() );
        return result;
    }   


}


