package gov.nia.nrs.utils.codeutils;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CodeSettingDo implements Serializable {
    /**
	 *
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CodeSetting.Id
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CodeSetting.CodeName
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    private String codeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CodeSetting.CodeNameDesc
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    private String codeNameDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CodeSetting.ParentCodeId
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    private String parentCodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CodeSetting.ActiveStatus
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    private String activeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CodeSetting.Comments
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CodeSetting.CreateUserId
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CodeSetting.CreateDate
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CodeSetting.MainUserId
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    private String mainUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CodeSetting.MaintainProgramId
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    private String maintainProgramId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CodeSetting.MaintainHost
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    private String maintainHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CodeSetting.LastUpdateTime
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CodeSetting.Version
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    private BigDecimal version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CodeSetting.Id
     *
     * @return the value of CodeSetting.Id
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CodeSetting.Id
     *
     * @param id the value for CodeSetting.Id
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CodeSetting.CodeName
     *
     * @return the value of CodeSetting.CodeName
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CodeSetting.CodeName
     *
     * @param codeName the value for CodeSetting.CodeName
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CodeSetting.CodeNameDesc
     *
     * @return the value of CodeSetting.CodeNameDesc
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public String getCodeNameDesc() {
        return codeNameDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CodeSetting.CodeNameDesc
     *
     * @param codeNameDesc the value for CodeSetting.CodeNameDesc
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public void setCodeNameDesc(String codeNameDesc) {
        this.codeNameDesc = codeNameDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CodeSetting.ParentCodeId
     *
     * @return the value of CodeSetting.ParentCodeId
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public String getParentCodeId() {
        return parentCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CodeSetting.ParentCodeId
     *
     * @param parentCodeId the value for CodeSetting.ParentCodeId
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public void setParentCodeId(String parentCodeId) {
        this.parentCodeId = parentCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CodeSetting.ActiveStatus
     *
     * @return the value of CodeSetting.ActiveStatus
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public String getActiveStatus() {
        return activeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CodeSetting.ActiveStatus
     *
     * @param activeStatus the value for CodeSetting.ActiveStatus
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public void setActiveStatus(String activeStatus) {
        this.activeStatus = activeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CodeSetting.Comments
     *
     * @return the value of CodeSetting.Comments
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CodeSetting.Comments
     *
     * @param comments the value for CodeSetting.Comments
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CodeSetting.CreateUserId
     *
     * @return the value of CodeSetting.CreateUserId
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CodeSetting.CreateUserId
     *
     * @param createUserId the value for CodeSetting.CreateUserId
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CodeSetting.CreateDate
     *
     * @return the value of CodeSetting.CreateDate
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CodeSetting.CreateDate
     *
     * @param createDate the value for CodeSetting.CreateDate
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CodeSetting.MainUserId
     *
     * @return the value of CodeSetting.MainUserId
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public String getMainUserId() {
        return mainUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CodeSetting.MainUserId
     *
     * @param mainUserId the value for CodeSetting.MainUserId
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CodeSetting.MaintainProgramId
     *
     * @return the value of CodeSetting.MaintainProgramId
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public String getMaintainProgramId() {
        return maintainProgramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CodeSetting.MaintainProgramId
     *
     * @param maintainProgramId the value for CodeSetting.MaintainProgramId
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CodeSetting.MaintainHost
     *
     * @return the value of CodeSetting.MaintainHost
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public String getMaintainHost() {
        return maintainHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CodeSetting.MaintainHost
     *
     * @param maintainHost the value for CodeSetting.MaintainHost
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CodeSetting.LastUpdateTime
     *
     * @return the value of CodeSetting.LastUpdateTime
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CodeSetting.LastUpdateTime
     *
     * @param lastUpdateTime the value for CodeSetting.LastUpdateTime
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CodeSetting.Version
     *
     * @return the value of CodeSetting.Version
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CodeSetting.Version
     *
     * @param version the value for CodeSetting.Version
     *
     * @mbggenerated Thu Jul 26 13:49:29 CST 2012
     */
    public void setVersion(BigDecimal version) {
        this.version = version;
    }
}