
package gov.nia.ssrs.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReportExecutionServiceSoap", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReportExecutionServiceSoap {


    /**
     * 
     * @return
     *     returns gov.nia.ssrs.ws.ArrayOfString
     */
    @WebMethod(operationName = "ListSecureMethods", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ListSecureMethods")
    @WebResult(name = "ListSecureMethodsResult", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "ListSecureMethods", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.ListSecureMethods")
    @ResponseWrapper(localName = "ListSecureMethodsResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.ListSecureMethodsResponse")
    public ArrayOfString listSecureMethods();

    /**
     * 
     * @param historyID
     * @param report
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo
     */
    @WebMethod(operationName = "LoadReport", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReport")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "LoadReport", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadReport")
    @ResponseWrapper(localName = "LoadReportResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadReportResponse")
    public ExecutionInfo loadReport(
        @WebParam(name = "Report", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String report,
        @WebParam(name = "HistoryID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String historyID);

    /**
     * 
     * @param historyID
     * @param report
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo3
     */
    @WebMethod(operationName = "LoadReport3", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReport3")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "LoadReport3", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadReport3")
    @ResponseWrapper(localName = "LoadReport3Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadReport3Response")
    public ExecutionInfo3 loadReport3(
        @WebParam(name = "Report", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String report,
        @WebParam(name = "HistoryID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String historyID);

    /**
     * 
     * @param historyID
     * @param report
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo2
     */
    @WebMethod(operationName = "LoadReport2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReport2")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "LoadReport2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadReport2")
    @ResponseWrapper(localName = "LoadReport2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadReport2Response")
    public ExecutionInfo2 loadReport2(
        @WebParam(name = "Report", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String report,
        @WebParam(name = "HistoryID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String historyID);

    /**
     * 
     * @param definition
     * @param warnings
     * @param executionInfo
     */
    @WebMethod(operationName = "LoadReportDefinition", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReportDefinition")
    @RequestWrapper(localName = "LoadReportDefinition", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadReportDefinition")
    @ResponseWrapper(localName = "LoadReportDefinitionResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadReportDefinitionResponse")
    public void loadReportDefinition(
        @WebParam(name = "Definition", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        byte[] definition,
        @WebParam(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<ExecutionInfo> executionInfo,
        @WebParam(name = "warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<ArrayOfWarning> warnings);

    /**
     * 
     * @param definition
     * @param warnings
     * @param executionInfo
     */
    @WebMethod(operationName = "LoadReportDefinition2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReportDefinition2")
    @RequestWrapper(localName = "LoadReportDefinition2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadReportDefinition2")
    @ResponseWrapper(localName = "LoadReportDefinition2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadReportDefinition2Response")
    public void loadReportDefinition2(
        @WebParam(name = "Definition", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        byte[] definition,
        @WebParam(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<ExecutionInfo2> executionInfo,
        @WebParam(name = "warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<ArrayOfWarning> warnings);

    /**
     * 
     * @param definition
     * @param warnings
     * @param executionInfo
     */
    @WebMethod(operationName = "LoadReportDefinition3", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReportDefinition3")
    @RequestWrapper(localName = "LoadReportDefinition3", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadReportDefinition3")
    @ResponseWrapper(localName = "LoadReportDefinition3Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadReportDefinition3Response")
    public void loadReportDefinition3(
        @WebParam(name = "Definition", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        byte[] definition,
        @WebParam(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<ExecutionInfo3> executionInfo,
        @WebParam(name = "warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<ArrayOfWarning> warnings);

    /**
     * 
     * @param credentials
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo
     */
    @WebMethod(operationName = "SetExecutionCredentials", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionCredentials")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "SetExecutionCredentials", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.SetExecutionCredentials")
    @ResponseWrapper(localName = "SetExecutionCredentialsResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.SetExecutionCredentialsResponse")
    public ExecutionInfo setExecutionCredentials(
        @WebParam(name = "Credentials", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ArrayOfDataSourceCredentials credentials);

    /**
     * 
     * @param credentials
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo2
     */
    @WebMethod(operationName = "SetExecutionCredentials2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionCredentials2")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "SetExecutionCredentials2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.SetExecutionCredentials2")
    @ResponseWrapper(localName = "SetExecutionCredentials2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.SetExecutionCredentials2Response")
    public ExecutionInfo2 setExecutionCredentials2(
        @WebParam(name = "Credentials", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ArrayOfDataSourceCredentials credentials);

    /**
     * 
     * @param credentials
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo3
     */
    @WebMethod(operationName = "SetExecutionCredentials3", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionCredentials3")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "SetExecutionCredentials3", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.SetExecutionCredentials3")
    @ResponseWrapper(localName = "SetExecutionCredentials3Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.SetExecutionCredentials3Response")
    public ExecutionInfo3 setExecutionCredentials3(
        @WebParam(name = "Credentials", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ArrayOfDataSourceCredentials credentials);

    /**
     * 
     * @param parameterLanguage
     * @param parameters
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo
     */
    @WebMethod(operationName = "SetExecutionParameters", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionParameters")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "SetExecutionParameters", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.SetExecutionParameters")
    @ResponseWrapper(localName = "SetExecutionParametersResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.SetExecutionParametersResponse")
    public ExecutionInfo setExecutionParameters(
        @WebParam(name = "Parameters", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ArrayOfParameterValue parameters,
        @WebParam(name = "ParameterLanguage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String parameterLanguage);

    /**
     * 
     * @param parameterLanguage
     * @param parameters
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo2
     */
    @WebMethod(operationName = "SetExecutionParameters2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionParameters2")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "SetExecutionParameters2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.SetExecutionParameters2")
    @ResponseWrapper(localName = "SetExecutionParameters2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.SetExecutionParameters2Response")
    public ExecutionInfo2 setExecutionParameters2(
        @WebParam(name = "Parameters", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ArrayOfParameterValue parameters,
        @WebParam(name = "ParameterLanguage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String parameterLanguage);

    /**
     * 
     * @param parameterLanguage
     * @param parameters
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo3
     */
    @WebMethod(operationName = "SetExecutionParameters3", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionParameters3")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "SetExecutionParameters3", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.SetExecutionParameters3")
    @ResponseWrapper(localName = "SetExecutionParameters3Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.SetExecutionParameters3Response")
    public ExecutionInfo3 setExecutionParameters3(
        @WebParam(name = "Parameters", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ArrayOfParameterValue parameters,
        @WebParam(name = "ParameterLanguage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String parameterLanguage);

    /**
     * 
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo
     */
    @WebMethod(operationName = "ResetExecution", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ResetExecution")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "ResetExecution", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.ResetExecution")
    @ResponseWrapper(localName = "ResetExecutionResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.ResetExecutionResponse")
    public ExecutionInfo resetExecution();

    /**
     * 
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo2
     */
    @WebMethod(operationName = "ResetExecution2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ResetExecution2")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "ResetExecution2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.ResetExecution2")
    @ResponseWrapper(localName = "ResetExecution2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.ResetExecution2Response")
    public ExecutionInfo2 resetExecution2();

    /**
     * 
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo3
     */
    @WebMethod(operationName = "ResetExecution3", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ResetExecution3")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "ResetExecution3", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.ResetExecution3")
    @ResponseWrapper(localName = "ResetExecution3Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.ResetExecution3Response")
    public ExecutionInfo3 resetExecution3();

    /**
     * 
     * @param extension
     * @param result
     * @param streamIds
     * @param encoding
     * @param deviceInfo
     * @param format
     * @param warnings
     * @param mimeType
     */
    @WebMethod(operationName = "Render", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Render")
    @RequestWrapper(localName = "Render", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.Render")
    @ResponseWrapper(localName = "RenderResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.RenderResponse")
    public void render(
        @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String format,
        @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String deviceInfo,
        @WebParam(name = "Result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<byte[]> result,
        @WebParam(name = "Extension", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<String> extension,
        @WebParam(name = "MimeType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<String> mimeType,
        @WebParam(name = "Encoding", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<String> encoding,
        @WebParam(name = "Warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<ArrayOfWarning> warnings,
        @WebParam(name = "StreamIds", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<ArrayOfString> streamIds);

    /**
     * 
     * @param extension
     * @param result
     * @param paginationMode
     * @param streamIds
     * @param encoding
     * @param deviceInfo
     * @param format
     * @param warnings
     * @param mimeType
     */
    @WebMethod(operationName = "Render2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Render2")
    @RequestWrapper(localName = "Render2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.Render2")
    @ResponseWrapper(localName = "Render2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.Render2Response")
    public void render2(
        @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String format,
        @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String deviceInfo,
        @WebParam(name = "PaginationMode", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        PageCountMode paginationMode,
        @WebParam(name = "Result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<byte[]> result,
        @WebParam(name = "Extension", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<String> extension,
        @WebParam(name = "MimeType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<String> mimeType,
        @WebParam(name = "Encoding", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<String> encoding,
        @WebParam(name = "Warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<ArrayOfWarning> warnings,
        @WebParam(name = "StreamIds", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<ArrayOfString> streamIds);

    /**
     * 
     * @param description
     * @param extensionSettings
     * @param eventType
     * @param deviceInfo
     * @param format
     * @param matchData
     */
    @WebMethod(operationName = "DeliverReportItem", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/DeliverReportItem")
    @RequestWrapper(localName = "DeliverReportItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.DeliverReportItem")
    @ResponseWrapper(localName = "DeliverReportItemResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.DeliverReportItemResponse")
    public void deliverReportItem(
        @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String format,
        @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String deviceInfo,
        @WebParam(name = "ExtensionSettings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ExtensionSettings extensionSettings,
        @WebParam(name = "Description", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String description,
        @WebParam(name = "EventType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String eventType,
        @WebParam(name = "MatchData", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String matchData);

    /**
     * 
     * @param streamID
     * @param result
     * @param encoding
     * @param deviceInfo
     * @param format
     * @param mimeType
     */
    @WebMethod(operationName = "RenderStream", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/RenderStream")
    @RequestWrapper(localName = "RenderStream", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.RenderStream")
    @ResponseWrapper(localName = "RenderStreamResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.RenderStreamResponse")
    public void renderStream(
        @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String format,
        @WebParam(name = "StreamID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String streamID,
        @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String deviceInfo,
        @WebParam(name = "Result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<byte[]> result,
        @WebParam(name = "Encoding", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<String> encoding,
        @WebParam(name = "MimeType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<String> mimeType);

    /**
     * 
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo
     */
    @WebMethod(operationName = "GetExecutionInfo", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetExecutionInfo")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "GetExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.GetExecutionInfo")
    @ResponseWrapper(localName = "GetExecutionInfoResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.GetExecutionInfoResponse")
    public ExecutionInfo getExecutionInfo();

    /**
     * 
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo2
     */
    @WebMethod(operationName = "GetExecutionInfo2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetExecutionInfo2")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "GetExecutionInfo2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.GetExecutionInfo2")
    @ResponseWrapper(localName = "GetExecutionInfo2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.GetExecutionInfo2Response")
    public ExecutionInfo2 getExecutionInfo2();

    /**
     * 
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo3
     */
    @WebMethod(operationName = "GetExecutionInfo3", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetExecutionInfo3")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "GetExecutionInfo3", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.GetExecutionInfo3")
    @ResponseWrapper(localName = "GetExecutionInfo3Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.GetExecutionInfo3Response")
    public ExecutionInfo3 getExecutionInfo3();

    /**
     * 
     * @return
     *     returns gov.nia.ssrs.ws.DocumentMapNode
     */
    @WebMethod(operationName = "GetDocumentMap", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetDocumentMap")
    @WebResult(name = "result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "GetDocumentMap", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.GetDocumentMap")
    @ResponseWrapper(localName = "GetDocumentMapResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.GetDocumentMapResponse")
    public DocumentMapNode getDocumentMap();

    /**
     * 
     * @param drillthroughID
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo
     */
    @WebMethod(operationName = "LoadDrillthroughTarget", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadDrillthroughTarget")
    @WebResult(name = "ExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "LoadDrillthroughTarget", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadDrillthroughTarget")
    @ResponseWrapper(localName = "LoadDrillthroughTargetResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadDrillthroughTargetResponse")
    public ExecutionInfo loadDrillthroughTarget(
        @WebParam(name = "DrillthroughID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String drillthroughID);

    /**
     * 
     * @param drillthroughID
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo2
     */
    @WebMethod(operationName = "LoadDrillthroughTarget2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadDrillthroughTarget2")
    @WebResult(name = "ExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "LoadDrillthroughTarget2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadDrillthroughTarget2")
    @ResponseWrapper(localName = "LoadDrillthroughTarget2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadDrillthroughTarget2Response")
    public ExecutionInfo2 loadDrillthroughTarget2(
        @WebParam(name = "DrillthroughID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String drillthroughID);

    /**
     * 
     * @param drillthroughID
     * @return
     *     returns gov.nia.ssrs.ws.ExecutionInfo3
     */
    @WebMethod(operationName = "LoadDrillthroughTarget3", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadDrillthroughTarget3")
    @WebResult(name = "ExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "LoadDrillthroughTarget3", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadDrillthroughTarget3")
    @ResponseWrapper(localName = "LoadDrillthroughTarget3Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LoadDrillthroughTarget3Response")
    public ExecutionInfo3 loadDrillthroughTarget3(
        @WebParam(name = "DrillthroughID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String drillthroughID);

    /**
     * 
     * @param toggleID
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "ToggleItem", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ToggleItem")
    @WebResult(name = "Found", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "ToggleItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.ToggleItem")
    @ResponseWrapper(localName = "ToggleItemResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.ToggleItemResponse")
    public boolean toggleItem(
        @WebParam(name = "ToggleID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String toggleID);

    /**
     * 
     * @param docMapID
     * @return
     *     returns int
     */
    @WebMethod(operationName = "NavigateDocumentMap", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/NavigateDocumentMap")
    @WebResult(name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "NavigateDocumentMap", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.NavigateDocumentMap")
    @ResponseWrapper(localName = "NavigateDocumentMapResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.NavigateDocumentMapResponse")
    public int navigateDocumentMap(
        @WebParam(name = "DocMapID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String docMapID);

    /**
     * 
     * @param pageNumber
     * @param bookmarkID
     * @param uniqueName
     */
    @WebMethod(operationName = "NavigateBookmark", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/NavigateBookmark")
    @RequestWrapper(localName = "NavigateBookmark", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.NavigateBookmark")
    @ResponseWrapper(localName = "NavigateBookmarkResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.NavigateBookmarkResponse")
    public void navigateBookmark(
        @WebParam(name = "BookmarkID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String bookmarkID,
        @WebParam(name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<Integer> pageNumber,
        @WebParam(name = "UniqueName", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<String> uniqueName);

    /**
     * 
     * @param findValue
     * @param endPage
     * @param startPage
     * @return
     *     returns int
     */
    @WebMethod(operationName = "FindString", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/FindString")
    @WebResult(name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "FindString", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.FindString")
    @ResponseWrapper(localName = "FindStringResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.FindStringResponse")
    public int findString(
        @WebParam(name = "StartPage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        int startPage,
        @WebParam(name = "EndPage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        int endPage,
        @WebParam(name = "FindValue", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String findValue);

    /**
     * 
     * @param clear
     * @param direction
     * @param pageNumber
     * @param reportItem
     * @param numPages
     * @param sortItem
     */
    @WebMethod(operationName = "Sort", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Sort")
    @RequestWrapper(localName = "Sort", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.Sort")
    @ResponseWrapper(localName = "SortResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.SortResponse")
    public void sort(
        @WebParam(name = "SortItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String sortItem,
        @WebParam(name = "Direction", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        SortDirectionEnum direction,
        @WebParam(name = "Clear", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        boolean clear,
        @WebParam(name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<Integer> pageNumber,
        @WebParam(name = "ReportItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<String> reportItem,
        @WebParam(name = "NumPages", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<Integer> numPages);

    /**
     * 
     * @param clear
     * @param paginationMode
     * @param direction
     * @param pageNumber
     * @param reportItem
     * @param executionInfo
     * @param sortItem
     */
    @WebMethod(operationName = "Sort2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Sort2")
    @RequestWrapper(localName = "Sort2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.Sort2")
    @ResponseWrapper(localName = "Sort2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.Sort2Response")
    public void sort2(
        @WebParam(name = "SortItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String sortItem,
        @WebParam(name = "Direction", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        SortDirectionEnum direction,
        @WebParam(name = "Clear", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        boolean clear,
        @WebParam(name = "PaginationMode", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        PageCountMode paginationMode,
        @WebParam(name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<Integer> pageNumber,
        @WebParam(name = "ReportItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<String> reportItem,
        @WebParam(name = "ExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<ExecutionInfo2> executionInfo);

    /**
     * 
     * @param clear
     * @param paginationMode
     * @param direction
     * @param pageNumber
     * @param reportItem
     * @param executionInfo
     * @param sortItem
     */
    @WebMethod(operationName = "Sort3", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Sort3")
    @RequestWrapper(localName = "Sort3", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.Sort3")
    @ResponseWrapper(localName = "Sort3Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.Sort3Response")
    public void sort3(
        @WebParam(name = "SortItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String sortItem,
        @WebParam(name = "Direction", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        SortDirectionEnum direction,
        @WebParam(name = "Clear", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        boolean clear,
        @WebParam(name = "PaginationMode", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        PageCountMode paginationMode,
        @WebParam(name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<Integer> pageNumber,
        @WebParam(name = "ReportItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<String> reportItem,
        @WebParam(name = "ExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<ExecutionInfo3> executionInfo);

    /**
     * 
     * @param result
     * @param deviceInfo
     * @param format
     * @param mimeType
     */
    @WebMethod(operationName = "GetRenderResource", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetRenderResource")
    @RequestWrapper(localName = "GetRenderResource", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.GetRenderResource")
    @ResponseWrapper(localName = "GetRenderResourceResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.GetRenderResourceResponse")
    public void getRenderResource(
        @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String format,
        @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String deviceInfo,
        @WebParam(name = "Result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<byte[]> result,
        @WebParam(name = "MimeType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
        Holder<String> mimeType);

    /**
     * 
     * @return
     *     returns gov.nia.ssrs.ws.ArrayOfExtension
     */
    @WebMethod(operationName = "ListRenderingExtensions", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ListRenderingExtensions")
    @WebResult(name = "Extensions", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "ListRenderingExtensions", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.ListRenderingExtensions")
    @ResponseWrapper(localName = "ListRenderingExtensionsResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.ListRenderingExtensionsResponse")
    public ArrayOfExtension listRenderingExtensions();

    /**
     * 
     * @param authority
     * @param userName
     * @param password
     */
    @WebMethod(operationName = "LogonUser", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LogonUser")
    @RequestWrapper(localName = "LogonUser", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LogonUser")
    @ResponseWrapper(localName = "LogonUserResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LogonUserResponse")
    public void logonUser(
        @WebParam(name = "userName", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String password,
        @WebParam(name = "authority", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        String authority);

    /**
     * 
     */
    @WebMethod(operationName = "Logoff", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Logoff")
    @RequestWrapper(localName = "Logoff", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.Logoff")
    @ResponseWrapper(localName = "LogoffResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "gov.nia.ssrs.ws.LogoffResponse")
    public void logoff();

}
