package gov.nia.nrs.domain.imm;



import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImmigrationsId generated by hbm2java
 */
@Embeddable
public class ImmigrationsId  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private String passengerId;
    private String immigrateDate;
    private Integer immigrateSeq;

    public ImmigrationsId() {}

    public ImmigrationsId(String passengerId, String immigrateDate, Integer immigrateSeq) {
        this.passengerId = passengerId;
        this.immigrateDate = immigrateDate;
        this.immigrateSeq = immigrateSeq;
    }
   


    @Column(name="PassengerId", nullable=false, length=10)
    public String getPassengerId() {
        return this.passengerId;
    }
    
    public void setPassengerId(String passengerId) {
        this.passengerId = passengerId;
    }


    @Column(name="ImmigrateDate", nullable=false, length=8)
    public String getImmigrateDate() {
        return this.immigrateDate;
    }
    
    public void setImmigrateDate(String immigrateDate) {
        this.immigrateDate = immigrateDate;
    }


    @Column(name="ImmigrateSeq", nullable=false, precision=5, scale=0)
    public Integer getImmigrateSeq() {
        return this.immigrateSeq;
    }
    
    public void setImmigrateSeq(Integer immigrateSeq) {
        this.immigrateSeq = immigrateSeq;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof ImmigrationsId) ) return false;
		ImmigrationsId castOther = ( ImmigrationsId ) other; 
         
		return ( (this.getPassengerId()==castOther.getPassengerId()) || ( this.getPassengerId()!=null && castOther.getPassengerId()!=null && this.getPassengerId().equals(castOther.getPassengerId()) ) )
 && ( (this.getImmigrateDate()==castOther.getImmigrateDate()) || ( this.getImmigrateDate()!=null && castOther.getImmigrateDate()!=null && this.getImmigrateDate().equals(castOther.getImmigrateDate()) ) )
 && ( (this.getImmigrateSeq()==castOther.getImmigrateSeq()) || ( this.getImmigrateSeq()!=null && castOther.getImmigrateSeq()!=null && this.getImmigrateSeq().equals(castOther.getImmigrateSeq()) ) );
    }
   
    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getPassengerId() == null ? 0 : this.getPassengerId().hashCode() );
        result = 37 * result + ( getImmigrateDate() == null ? 0 : this.getImmigrateDate().hashCode() );
        result = 37 * result + ( getImmigrateSeq() == null ? 0 : this.getImmigrateSeq().hashCode() );
        return result;
    }   


}


