package gov.nia.nrs.domain.imm;



import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MultiCitizenship generated by hbm2java
 */
@Entity
@Table(name="MultiCitizenship"
)
public class MultiCitizenship  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private MultiCitizenshipId id;
    private String passengerId;
    private Integer nation;
    private String personId;
    private String chineseName;
    private String englishName;
    private String gender;
    private String birthDate;
    private Integer birthPlaceCode;
    private Integer birthPlace1;
    private String birthPlace2;
    private String dataType;
    private String dataSource;
    private Integer residentMark;
    private String chinaMark;
    private String filmNo;
    private Integer imagePathNo;
    private String createDate;
    private String reserved;
    private Date establishTime;
    private Date importTime;
    private String deleteFlag;
    private String mainUserId;
    private String maintainProgramId;
    private String maintainHost;
    private Date lastUpdateTime;
    private String inspectorId;
    private Date inspectTime;
    private String writeBackFlag;
    private String writeBackRcode;
    private Date writeBackTime;
    private Integer txnMark;
    private Date syncTime;
    private Integer inspectTermNo;
    private String inspectTermLoc;
    private Date last2updateTime;
    private String sortEnglishName;

    public MultiCitizenship() {}

	
    public MultiCitizenship(MultiCitizenshipId id, Integer nation, String personId, String gender, String birthDate, Integer birthPlaceCode, Integer birthPlace1, String birthPlace2, String dataType, String dataSource, Integer residentMark, String chinaMark, String filmNo, Integer imagePathNo, String createDate, String deleteFlag, String mainUserId, String maintainProgramId, String maintainHost, Date lastUpdateTime) {
        this.id = id;
        this.nation = nation;
        this.personId = personId;
        this.gender = gender;
        this.birthDate = birthDate;
        this.birthPlaceCode = birthPlaceCode;
        this.birthPlace1 = birthPlace1;
        this.birthPlace2 = birthPlace2;
        this.dataType = dataType;
        this.dataSource = dataSource;
        this.residentMark = residentMark;
        this.chinaMark = chinaMark;
        this.filmNo = filmNo;
        this.imagePathNo = imagePathNo;
        this.createDate = createDate;
        this.deleteFlag = deleteFlag;
        this.mainUserId = mainUserId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
    }
    public MultiCitizenship(MultiCitizenshipId id, String passengerId, Integer nation, String personId, String chineseName, String englishName, String gender, String birthDate, Integer birthPlaceCode, Integer birthPlace1, String birthPlace2, String dataType, String dataSource, Integer residentMark, String chinaMark, String filmNo, Integer imagePathNo, String createDate, String reserved, Date establishTime, Date importTime, String deleteFlag, String mainUserId, String maintainProgramId, String maintainHost, Date lastUpdateTime, String inspectorId, Date inspectTime, String writeBackFlag, String writeBackRcode, Date writeBackTime, Integer txnMark, Date syncTime, Integer inspectTermNo, String inspectTermLoc, Date last2updateTime, String sortEnglishName) {
        this.id = id;
        this.passengerId = passengerId;
        this.nation = nation;
        this.personId = personId;
        this.chineseName = chineseName;
        this.englishName = englishName;
        this.gender = gender;
        this.birthDate = birthDate;
        this.birthPlaceCode = birthPlaceCode;
        this.birthPlace1 = birthPlace1;
        this.birthPlace2 = birthPlace2;
        this.dataType = dataType;
        this.dataSource = dataSource;
        this.residentMark = residentMark;
        this.chinaMark = chinaMark;
        this.filmNo = filmNo;
        this.imagePathNo = imagePathNo;
        this.createDate = createDate;
        this.reserved = reserved;
        this.establishTime = establishTime;
        this.importTime = importTime;
        this.deleteFlag = deleteFlag;
        this.mainUserId = mainUserId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
        this.inspectorId = inspectorId;
        this.inspectTime = inspectTime;
        this.writeBackFlag = writeBackFlag;
        this.writeBackRcode = writeBackRcode;
        this.writeBackTime = writeBackTime;
        this.txnMark = txnMark;
        this.syncTime = syncTime;
        this.inspectTermNo = inspectTermNo;
        this.inspectTermLoc = inspectTermLoc;
        this.last2updateTime = last2updateTime;
        this.sortEnglishName = sortEnglishName;
    }
   
    @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="serialNo", column=@Column(name="SerialNo", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="passportNo", column=@Column(name="PassportNo", nullable=false, length=15) ) } )
    public MultiCitizenshipId getId() {
        return this.id;
    }
    
    public void setId(MultiCitizenshipId id) {
        this.id = id;
    }

    
    @Column(name="PassengerId", length=10)
    public String getPassengerId() {
        return this.passengerId;
    }
    
    public void setPassengerId(String passengerId) {
        this.passengerId = passengerId;
    }

    
    @Column(name="Nation", nullable=false, precision=3, scale=0)
    public Integer getNation() {
        return this.nation;
    }
    
    public void setNation(Integer nation) {
        this.nation = nation;
    }

    
    @Column(name="PersonId", nullable=false, length=20)
    public String getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(String personId) {
        this.personId = personId;
    }

    
    @Column(name="ChineseName", length=80)
    public String getChineseName() {
        return this.chineseName;
    }
    
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    
    @Column(name="EnglishName", length=50)
    public String getEnglishName() {
        return this.englishName;
    }
    
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    
    @Column(name="Gender", nullable=false, length=1)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="BirthDate", nullable=false, length=8)
    public String getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="BirthPlaceCode", nullable=false, precision=1, scale=0)
    public Integer getBirthPlaceCode() {
        return this.birthPlaceCode;
    }
    
    public void setBirthPlaceCode(Integer birthPlaceCode) {
        this.birthPlaceCode = birthPlaceCode;
    }

    
    @Column(name="BirthPlace1", nullable=false, precision=3, scale=0)
    public Integer getBirthPlace1() {
        return this.birthPlace1;
    }
    
    public void setBirthPlace1(Integer birthPlace1) {
        this.birthPlace1 = birthPlace1;
    }

    
    @Column(name="BirthPlace2", nullable=false, length=16)
    public String getBirthPlace2() {
        return this.birthPlace2;
    }
    
    public void setBirthPlace2(String birthPlace2) {
        this.birthPlace2 = birthPlace2;
    }

    
    @Column(name="DataType", nullable=false, length=1)
    public String getDataType() {
        return this.dataType;
    }
    
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    
    @Column(name="DataSource", nullable=false, length=1)
    public String getDataSource() {
        return this.dataSource;
    }
    
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }

    
    @Column(name="ResidentMark", nullable=false, precision=1, scale=0)
    public Integer getResidentMark() {
        return this.residentMark;
    }
    
    public void setResidentMark(Integer residentMark) {
        this.residentMark = residentMark;
    }

    
    @Column(name="ChinaMark", nullable=false, length=1)
    public String getChinaMark() {
        return this.chinaMark;
    }
    
    public void setChinaMark(String chinaMark) {
        this.chinaMark = chinaMark;
    }

    
    @Column(name="FilmNo", nullable=false, length=11)
    public String getFilmNo() {
        return this.filmNo;
    }
    
    public void setFilmNo(String filmNo) {
        this.filmNo = filmNo;
    }

    
    @Column(name="ImagePathNo", nullable=false, precision=7, scale=0)
    public Integer getImagePathNo() {
        return this.imagePathNo;
    }
    
    public void setImagePathNo(Integer imagePathNo) {
        this.imagePathNo = imagePathNo;
    }

    
    @Column(name="CreateDate", nullable=false, length=8)
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="Reserved", length=30)
    public String getReserved() {
        return this.reserved;
    }
    
    public void setReserved(String reserved) {
        this.reserved = reserved;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EstablishTime", length=23)
    public Date getEstablishTime() {
        return this.establishTime;
    }
    
    public void setEstablishTime(Date establishTime) {
        this.establishTime = establishTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ImportTime", length=23)
    public Date getImportTime() {
        return this.importTime;
    }
    
    public void setImportTime(Date importTime) {
        this.importTime = importTime;
    }

    
    @Column(name="DeleteFlag", nullable=false, length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    
    @Column(name="MainUserId", nullable=false, length=10)
    public String getMainUserId() {
        return this.mainUserId;
    }
    
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }

    
    @Column(name="MaintainProgramId", nullable=false, length=10)
    public String getMaintainProgramId() {
        return this.maintainProgramId;
    }
    
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    
    @Column(name="MaintainHost", nullable=false, length=2)
    public String getMaintainHost() {
        return this.maintainHost;
    }
    
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdateTime", nullable=false, length=23)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    
    @Column(name="InspectorId", length=5)
    public String getInspectorId() {
        return this.inspectorId;
    }
    
    public void setInspectorId(String inspectorId) {
        this.inspectorId = inspectorId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="InspectTime", length=23)
    public Date getInspectTime() {
        return this.inspectTime;
    }
    
    public void setInspectTime(Date inspectTime) {
        this.inspectTime = inspectTime;
    }

    
    @Column(name="WriteBackFlag", length=1)
    public String getWriteBackFlag() {
        return this.writeBackFlag;
    }
    
    public void setWriteBackFlag(String writeBackFlag) {
        this.writeBackFlag = writeBackFlag;
    }

    
    @Column(name="WriteBackRcode", length=4)
    public String getWriteBackRcode() {
        return this.writeBackRcode;
    }
    
    public void setWriteBackRcode(String writeBackRcode) {
        this.writeBackRcode = writeBackRcode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="WriteBackTime", length=23)
    public Date getWriteBackTime() {
        return this.writeBackTime;
    }
    
    public void setWriteBackTime(Date writeBackTime) {
        this.writeBackTime = writeBackTime;
    }

    
    @Column(name="TxnMark", precision=1, scale=0)
    public Integer getTxnMark() {
        return this.txnMark;
    }
    
    public void setTxnMark(Integer txnMark) {
        this.txnMark = txnMark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SyncTime", length=23)
    public Date getSyncTime() {
        return this.syncTime;
    }
    
    public void setSyncTime(Date syncTime) {
        this.syncTime = syncTime;
    }

    
    @Column(name="InspectTermNo", precision=4, scale=0)
    public Integer getInspectTermNo() {
        return this.inspectTermNo;
    }
    
    public void setInspectTermNo(Integer inspectTermNo) {
        this.inspectTermNo = inspectTermNo;
    }

    
    @Column(name="InspectTermLoc", length=2)
    public String getInspectTermLoc() {
        return this.inspectTermLoc;
    }
    
    public void setInspectTermLoc(String inspectTermLoc) {
        this.inspectTermLoc = inspectTermLoc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Last2UpdateTime", length=23)
    public Date getLast2updateTime() {
        return this.last2updateTime;
    }
    
    public void setLast2updateTime(Date last2updateTime) {
        this.last2updateTime = last2updateTime;
    }

    
    @Column(name="SortEnglishName", length=50)
    public String getSortEnglishName() {
        return this.sortEnglishName;
    }
    
    public void setSortEnglishName(String sortEnglishName) {
        this.sortEnglishName = sortEnglishName;
    }




}


