package gov.nia.nrs.domain.imm;



import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MultiCitizenshipId generated by hbm2java
 */
@Embeddable
public class MultiCitizenshipId  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Long serialNo;
    private String passportNo;

    public MultiCitizenshipId() {}

    public MultiCitizenshipId(Long serialNo, String passportNo) {
        this.serialNo = serialNo;
        this.passportNo = passportNo;
    }
   


    @Column(name="SerialNo", nullable=false, precision=10, scale=0)
    public Long getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(Long serialNo) {
        this.serialNo = serialNo;
    }


    @Column(name="PassportNo", nullable=false, length=15)
    public String getPassportNo() {
        return this.passportNo;
    }
    
    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof MultiCitizenshipId) ) return false;
		MultiCitizenshipId castOther = ( MultiCitizenshipId ) other; 
         
		return ( (this.getSerialNo()==castOther.getSerialNo()) || ( this.getSerialNo()!=null && castOther.getSerialNo()!=null && this.getSerialNo().equals(castOther.getSerialNo()) ) )
 && ( (this.getPassportNo()==castOther.getPassportNo()) || ( this.getPassportNo()!=null && castOther.getPassportNo()!=null && this.getPassportNo().equals(castOther.getPassportNo()) ) );
    }
   
    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getSerialNo() == null ? 0 : this.getSerialNo().hashCode() );
        result = 37 * result + ( getPassportNo() == null ? 0 : this.getPassportNo().hashCode() );
        return result;
    }   


}


