package gov.nia.nrs.domain.imm;



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Passengers generated by hbm2java
 */
@Entity
@Table(name="Passengers"
)
public class Passengers  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private String passengerId;
    private String personId;
    private String passportNo;
    private Integer nationCategory;
    private Integer nation;
    private String immigrateDate;
    private Integer immigrateType;
    private Integer immigratePort;
    private String flightNo;
    private String immigPassportNo;
    private String immigWay;
    private String remark;
    private String reserved;
    private Date establishTime;
    private Date importTime;
    private String deleteFlag;
    private String mainUserId;
    private String maintainProgramId;
    private String maintainHost;
    private Date lastUpdateTime;
    private Date inspectTime;
    private Integer port;
    private Integer inspectTermNo;
    private Date immigrateTime;
    private String stayDays;
    private String departureDueDate;
    private String arrivalDueDate;
    private String immigrateEdCardNo;
    private String remarkTitle;
    private Integer txnMark;
    private Date syncTime;
    private String birthDate;
    private String firstRecvNo;
    private String permitNo;
    private String firstImmigDate;
    private String lastImmigDate;
    private String visaNo;

    public Passengers() {}

	
    public Passengers(String passengerId, String personId, String passportNo, Integer nationCategory, Integer nation, String immigrateDate, Integer immigrateType, Integer immigratePort, String flightNo, String immigPassportNo, String deleteFlag, String mainUserId, String maintainProgramId, String maintainHost, Date lastUpdateTime) {
        this.passengerId = passengerId;
        this.personId = personId;
        this.passportNo = passportNo;
        this.nationCategory = nationCategory;
        this.nation = nation;
        this.immigrateDate = immigrateDate;
        this.immigrateType = immigrateType;
        this.immigratePort = immigratePort;
        this.flightNo = flightNo;
        this.immigPassportNo = immigPassportNo;
        this.deleteFlag = deleteFlag;
        this.mainUserId = mainUserId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
    }
    public Passengers(String passengerId, String personId, String passportNo, Integer nationCategory, Integer nation, String immigrateDate, Integer immigrateType, Integer immigratePort, String flightNo, String immigPassportNo, String immigWay, String remark, String reserved, Date establishTime, Date importTime, String deleteFlag, String mainUserId, String maintainProgramId, String maintainHost, Date lastUpdateTime, Date inspectTime, Integer port, Integer inspectTermNo, Date immigrateTime, String stayDays, String departureDueDate, String arrivalDueDate, String immigrateEdCardNo, String remarkTitle, Integer txnMark, Date syncTime, String birthDate, String firstRecvNo, String permitNo, String firstImmigDate, String lastImmigDate, String visaNo) {
        this.passengerId = passengerId;
        this.personId = personId;
        this.passportNo = passportNo;
        this.nationCategory = nationCategory;
        this.nation = nation;
        this.immigrateDate = immigrateDate;
        this.immigrateType = immigrateType;
        this.immigratePort = immigratePort;
        this.flightNo = flightNo;
        this.immigPassportNo = immigPassportNo;
        this.immigWay = immigWay;
        this.remark = remark;
        this.reserved = reserved;
        this.establishTime = establishTime;
        this.importTime = importTime;
        this.deleteFlag = deleteFlag;
        this.mainUserId = mainUserId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
        this.inspectTime = inspectTime;
        this.port = port;
        this.inspectTermNo = inspectTermNo;
        this.immigrateTime = immigrateTime;
        this.stayDays = stayDays;
        this.departureDueDate = departureDueDate;
        this.arrivalDueDate = arrivalDueDate;
        this.immigrateEdCardNo = immigrateEdCardNo;
        this.remarkTitle = remarkTitle;
        this.txnMark = txnMark;
        this.syncTime = syncTime;
        this.birthDate = birthDate;
        this.firstRecvNo = firstRecvNo;
        this.permitNo = permitNo;
        this.firstImmigDate = firstImmigDate;
        this.lastImmigDate = lastImmigDate;
        this.visaNo = visaNo;
    }
   
    @Id 

    
    @Column(name="PassengerId", unique=true, nullable=false, length=10)
    public String getPassengerId() {
        return this.passengerId;
    }
    
    public void setPassengerId(String passengerId) {
        this.passengerId = passengerId;
    }

    
    @Column(name="PersonId", nullable=false, length=20)
    public String getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(String personId) {
        this.personId = personId;
    }

    
    @Column(name="PassportNo", nullable=false, length=15)
    public String getPassportNo() {
        return this.passportNo;
    }
    
    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }

    
    @Column(name="NationCategory", nullable=false, precision=1, scale=0)
    public Integer getNationCategory() {
        return this.nationCategory;
    }
    
    public void setNationCategory(Integer nationCategory) {
        this.nationCategory = nationCategory;
    }

    
    @Column(name="Nation", nullable=false, precision=3, scale=0)
    public Integer getNation() {
        return this.nation;
    }
    
    public void setNation(Integer nation) {
        this.nation = nation;
    }

    
    @Column(name="ImmigrateDate", nullable=false, length=8)
    public String getImmigrateDate() {
        return this.immigrateDate;
    }
    
    public void setImmigrateDate(String immigrateDate) {
        this.immigrateDate = immigrateDate;
    }

    
    @Column(name="ImmigrateType", nullable=false, precision=1, scale=0)
    public Integer getImmigrateType() {
        return this.immigrateType;
    }
    
    public void setImmigrateType(Integer immigrateType) {
        this.immigrateType = immigrateType;
    }

    
    @Column(name="ImmigratePort", nullable=false, precision=2, scale=0)
    public Integer getImmigratePort() {
        return this.immigratePort;
    }
    
    public void setImmigratePort(Integer immigratePort) {
        this.immigratePort = immigratePort;
    }

    
    @Column(name="FlightNo", nullable=false, length=20)
    public String getFlightNo() {
        return this.flightNo;
    }
    
    public void setFlightNo(String flightNo) {
        this.flightNo = flightNo;
    }

    
    @Column(name="ImmigPassportNo", nullable=false, length=15)
    public String getImmigPassportNo() {
        return this.immigPassportNo;
    }
    
    public void setImmigPassportNo(String immigPassportNo) {
        this.immigPassportNo = immigPassportNo;
    }

    
    @Column(name="ImmigWay", length=1)
    public String getImmigWay() {
        return this.immigWay;
    }
    
    public void setImmigWay(String immigWay) {
        this.immigWay = immigWay;
    }

    
    @Column(name="Remark", length=50)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="Reserved", length=30)
    public String getReserved() {
        return this.reserved;
    }
    
    public void setReserved(String reserved) {
        this.reserved = reserved;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EstablishTime", length=23)
    public Date getEstablishTime() {
        return this.establishTime;
    }
    
    public void setEstablishTime(Date establishTime) {
        this.establishTime = establishTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ImportTime", length=23)
    public Date getImportTime() {
        return this.importTime;
    }
    
    public void setImportTime(Date importTime) {
        this.importTime = importTime;
    }

    
    @Column(name="DeleteFlag", nullable=false, length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    
    @Column(name="MainUserId", nullable=false, length=10)
    public String getMainUserId() {
        return this.mainUserId;
    }
    
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }

    
    @Column(name="MaintainProgramId", nullable=false, length=10)
    public String getMaintainProgramId() {
        return this.maintainProgramId;
    }
    
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    
    @Column(name="MaintainHost", nullable=false, length=2)
    public String getMaintainHost() {
        return this.maintainHost;
    }
    
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdateTime", nullable=false, length=23)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="InspectTime", length=23)
    public Date getInspectTime() {
        return this.inspectTime;
    }
    
    public void setInspectTime(Date inspectTime) {
        this.inspectTime = inspectTime;
    }

    
    @Column(name="Port", precision=2, scale=0)
    public Integer getPort() {
        return this.port;
    }
    
    public void setPort(Integer port) {
        this.port = port;
    }

    
    @Column(name="InspectTermNo", precision=4, scale=0)
    public Integer getInspectTermNo() {
        return this.inspectTermNo;
    }
    
    public void setInspectTermNo(Integer inspectTermNo) {
        this.inspectTermNo = inspectTermNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ImmigrateTime", length=23)
    public Date getImmigrateTime() {
        return this.immigrateTime;
    }
    
    public void setImmigrateTime(Date immigrateTime) {
        this.immigrateTime = immigrateTime;
    }

    
    @Column(name="StayDays", length=3)
    public String getStayDays() {
        return this.stayDays;
    }
    
    public void setStayDays(String stayDays) {
        this.stayDays = stayDays;
    }

    
    @Column(name="DepartureDueDate", length=8)
    public String getDepartureDueDate() {
        return this.departureDueDate;
    }
    
    public void setDepartureDueDate(String departureDueDate) {
        this.departureDueDate = departureDueDate;
    }

    
    @Column(name="ArrivalDueDate", length=8)
    public String getArrivalDueDate() {
        return this.arrivalDueDate;
    }
    
    public void setArrivalDueDate(String arrivalDueDate) {
        this.arrivalDueDate = arrivalDueDate;
    }

    
    @Column(name="ImmigrateEdCardNo", length=10)
    public String getImmigrateEdCardNo() {
        return this.immigrateEdCardNo;
    }
    
    public void setImmigrateEdCardNo(String immigrateEdCardNo) {
        this.immigrateEdCardNo = immigrateEdCardNo;
    }

    
    @Column(name="RemarkTitle", length=20)
    public String getRemarkTitle() {
        return this.remarkTitle;
    }
    
    public void setRemarkTitle(String remarkTitle) {
        this.remarkTitle = remarkTitle;
    }

    
    @Column(name="TxnMark", precision=1, scale=0)
    public Integer getTxnMark() {
        return this.txnMark;
    }
    
    public void setTxnMark(Integer txnMark) {
        this.txnMark = txnMark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SyncTime", length=23)
    public Date getSyncTime() {
        return this.syncTime;
    }
    
    public void setSyncTime(Date syncTime) {
        this.syncTime = syncTime;
    }

    
    @Column(name="BirthDate", length=8)
    public String getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="FirstRecvNo", length=12)
    public String getFirstRecvNo() {
        return this.firstRecvNo;
    }
    
    public void setFirstRecvNo(String firstRecvNo) {
        this.firstRecvNo = firstRecvNo;
    }

    
    @Column(name="PermitNo", length=12)
    public String getPermitNo() {
        return this.permitNo;
    }
    
    public void setPermitNo(String permitNo) {
        this.permitNo = permitNo;
    }

    
    @Column(name="FirstImmigDate", length=8)
    public String getFirstImmigDate() {
        return this.firstImmigDate;
    }
    
    public void setFirstImmigDate(String firstImmigDate) {
        this.firstImmigDate = firstImmigDate;
    }

    
    @Column(name="LastImmigDate", length=8)
    public String getLastImmigDate() {
        return this.lastImmigDate;
    }
    
    public void setLastImmigDate(String lastImmigDate) {
        this.lastImmigDate = lastImmigDate;
    }

    
    @Column(name="VisaNo", length=14)
    public String getVisaNo() {
        return this.visaNo;
    }
    
    public void setVisaNo(String visaNo) {
        this.visaNo = visaNo;
    }




}


