package gov.nia.nrs.domain.imm;



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Permit generated by hbm2java
 */
@Entity
@Table(name="Permit"
)
public class Permit  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private String permitNo;
    private Integer permitCode;
    private String permitType;
    private String passengerId;
    private Integer nation;
    private String chineseName;
    private String englishName;
    private String gender;
    private String birthDate;
    private Integer birthPlaceCode;
    private Integer birthPlace1;
    private String birthPlace2;
    private String personId;
    private String passportNo;
    private String issueDate;
    private String exitExpiryDate;
    private String entryExpiryDate;
    private String militaryMark;
    private Integer position;
    private String commieMark;
    private Integer pathNoInd;
    private String entryDate;
    private String exitDate;
    private String entryCnt;
    private String tourGroupId;
    private String interviewMark;
    private Integer reason;
    private String firstRecvNo;
    private String origName;
    private String deadMark;
    private String addrType;
    private Integer zipCode;
    private String addr1;
    private String addr2;
    private String addr3;
    private String addr4;
    private String followMark;
    private String sittingDate;
    private String autoPassMark;
    private String epassportMark;
    private String reserved;
    private Integer allowImmigTimes;
    private Integer immigTimes;
    private String certificate;
    private String revokeMark;
    private String revokeReason;
    private String comment;
    private String writeBackFlag;
    private String writeBackRcode;
    private Date writeBackTime;
    private Integer txnMark;
    private Date syncTime;
    private Date establishTime;
    private Date importTime;
    private String deleteFlag;
    private String mainUserId;
    private String maintainProgramId;
    private String maintainHost;
    private Date lastUpdateTime;
    private Integer inspectTermNo;
    private String inspectTermLoc;
    private String permitDocType;
    private String applyType;
    private String applyRemark;
    private String trimEngName;
    private String stayDays;
    private String cruisesOrder;
    private String referencePermitNo;
    private String lastestExchangeDate;

    public Permit() {}

	
    public Permit(String permitNo, Integer permitCode, String permitType, String passengerId, Integer nation, String englishName, String gender, String birthDate, Integer birthPlaceCode, Integer birthPlace1, String birthPlace2, String personId, String passportNo, String issueDate, String exitExpiryDate, String entryExpiryDate, String militaryMark, Integer position, String commieMark, Integer pathNoInd, String entryDate, String exitDate, String interviewMark, Integer reason, String firstRecvNo, String origName, String deadMark, String addrType, Integer zipCode, String addr1, String addr2, String addr3, String addr4, String writeBackFlag, String writeBackRcode, String deleteFlag, String mainUserId, String maintainProgramId, String maintainHost, Date lastUpdateTime) {
        this.permitNo = permitNo;
        this.permitCode = permitCode;
        this.permitType = permitType;
        this.passengerId = passengerId;
        this.nation = nation;
        this.englishName = englishName;
        this.gender = gender;
        this.birthDate = birthDate;
        this.birthPlaceCode = birthPlaceCode;
        this.birthPlace1 = birthPlace1;
        this.birthPlace2 = birthPlace2;
        this.personId = personId;
        this.passportNo = passportNo;
        this.issueDate = issueDate;
        this.exitExpiryDate = exitExpiryDate;
        this.entryExpiryDate = entryExpiryDate;
        this.militaryMark = militaryMark;
        this.position = position;
        this.commieMark = commieMark;
        this.pathNoInd = pathNoInd;
        this.entryDate = entryDate;
        this.exitDate = exitDate;
        this.interviewMark = interviewMark;
        this.reason = reason;
        this.firstRecvNo = firstRecvNo;
        this.origName = origName;
        this.deadMark = deadMark;
        this.addrType = addrType;
        this.zipCode = zipCode;
        this.addr1 = addr1;
        this.addr2 = addr2;
        this.addr3 = addr3;
        this.addr4 = addr4;
        this.writeBackFlag = writeBackFlag;
        this.writeBackRcode = writeBackRcode;
        this.deleteFlag = deleteFlag;
        this.mainUserId = mainUserId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
    }
    public Permit(String permitNo, Integer permitCode, String permitType, String passengerId, Integer nation, String chineseName, String englishName, String gender, String birthDate, Integer birthPlaceCode, Integer birthPlace1, String birthPlace2, String personId, String passportNo, String issueDate, String exitExpiryDate, String entryExpiryDate, String militaryMark, Integer position, String commieMark, Integer pathNoInd, String entryDate, String exitDate, String entryCnt, String tourGroupId, String interviewMark, Integer reason, String firstRecvNo, String origName, String deadMark, String addrType, Integer zipCode, String addr1, String addr2, String addr3, String addr4, String followMark, String sittingDate, String autoPassMark, String epassportMark, String reserved, Integer allowImmigTimes, Integer immigTimes, String certificate, String revokeMark, String revokeReason, String comment, String writeBackFlag, String writeBackRcode, Date writeBackTime, Integer txnMark, Date syncTime, Date establishTime, Date importTime, String deleteFlag, String mainUserId, String maintainProgramId, String maintainHost, Date lastUpdateTime, Integer inspectTermNo, String inspectTermLoc, String permitDocType, String applyType, String applyRemark, String trimEngName, String stayDays, String cruisesOrder, String referencePermitNo, String lastestExchangeDate) {
        this.permitNo = permitNo;
        this.permitCode = permitCode;
        this.permitType = permitType;
        this.passengerId = passengerId;
        this.nation = nation;
        this.chineseName = chineseName;
        this.englishName = englishName;
        this.gender = gender;
        this.birthDate = birthDate;
        this.birthPlaceCode = birthPlaceCode;
        this.birthPlace1 = birthPlace1;
        this.birthPlace2 = birthPlace2;
        this.personId = personId;
        this.passportNo = passportNo;
        this.issueDate = issueDate;
        this.exitExpiryDate = exitExpiryDate;
        this.entryExpiryDate = entryExpiryDate;
        this.militaryMark = militaryMark;
        this.position = position;
        this.commieMark = commieMark;
        this.pathNoInd = pathNoInd;
        this.entryDate = entryDate;
        this.exitDate = exitDate;
        this.entryCnt = entryCnt;
        this.tourGroupId = tourGroupId;
        this.interviewMark = interviewMark;
        this.reason = reason;
        this.firstRecvNo = firstRecvNo;
        this.origName = origName;
        this.deadMark = deadMark;
        this.addrType = addrType;
        this.zipCode = zipCode;
        this.addr1 = addr1;
        this.addr2 = addr2;
        this.addr3 = addr3;
        this.addr4 = addr4;
        this.followMark = followMark;
        this.sittingDate = sittingDate;
        this.autoPassMark = autoPassMark;
        this.epassportMark = epassportMark;
        this.reserved = reserved;
        this.allowImmigTimes = allowImmigTimes;
        this.immigTimes = immigTimes;
        this.certificate = certificate;
        this.revokeMark = revokeMark;
        this.revokeReason = revokeReason;
        this.comment = comment;
        this.writeBackFlag = writeBackFlag;
        this.writeBackRcode = writeBackRcode;
        this.writeBackTime = writeBackTime;
        this.txnMark = txnMark;
        this.syncTime = syncTime;
        this.establishTime = establishTime;
        this.importTime = importTime;
        this.deleteFlag = deleteFlag;
        this.mainUserId = mainUserId;
        this.maintainProgramId = maintainProgramId;
        this.maintainHost = maintainHost;
        this.lastUpdateTime = lastUpdateTime;
        this.inspectTermNo = inspectTermNo;
        this.inspectTermLoc = inspectTermLoc;
        this.permitDocType = permitDocType;
        this.applyType = applyType;
        this.applyRemark = applyRemark;
        this.trimEngName = trimEngName;
        this.stayDays = stayDays;
        this.cruisesOrder = cruisesOrder;
        this.referencePermitNo = referencePermitNo;
        this.lastestExchangeDate = lastestExchangeDate;
    }
   
    @Id 

    
    @Column(name="PermitNo", unique=true, nullable=false, length=12)
    public String getPermitNo() {
        return this.permitNo;
    }
    
    public void setPermitNo(String permitNo) {
        this.permitNo = permitNo;
    }

    
    @Column(name="PermitCode", nullable=false, precision=3, scale=0)
    public Integer getPermitCode() {
        return this.permitCode;
    }
    
    public void setPermitCode(Integer permitCode) {
        this.permitCode = permitCode;
    }

    
    @Column(name="PermitType", nullable=false, length=3)
    public String getPermitType() {
        return this.permitType;
    }
    
    public void setPermitType(String permitType) {
        this.permitType = permitType;
    }

    
    @Column(name="PassengerId", nullable=false, length=10)
    public String getPassengerId() {
        return this.passengerId;
    }
    
    public void setPassengerId(String passengerId) {
        this.passengerId = passengerId;
    }

    
    @Column(name="Nation", nullable=false, precision=3, scale=0)
    public Integer getNation() {
        return this.nation;
    }
    
    public void setNation(Integer nation) {
        this.nation = nation;
    }

    
    @Column(name="ChineseName", length=80)
    public String getChineseName() {
        return this.chineseName;
    }
    
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    
    @Column(name="EnglishName", nullable=false, length=50)
    public String getEnglishName() {
        return this.englishName;
    }
    
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    
    @Column(name="Gender", nullable=false, length=1)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="BirthDate", nullable=false, length=8)
    public String getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="BirthPlaceCode", nullable=false, precision=1, scale=0)
    public Integer getBirthPlaceCode() {
        return this.birthPlaceCode;
    }
    
    public void setBirthPlaceCode(Integer birthPlaceCode) {
        this.birthPlaceCode = birthPlaceCode;
    }

    
    @Column(name="BirthPlace1", nullable=false, precision=3, scale=0)
    public Integer getBirthPlace1() {
        return this.birthPlace1;
    }
    
    public void setBirthPlace1(Integer birthPlace1) {
        this.birthPlace1 = birthPlace1;
    }

    
    @Column(name="BirthPlace2", nullable=false, length=16)
    public String getBirthPlace2() {
        return this.birthPlace2;
    }
    
    public void setBirthPlace2(String birthPlace2) {
        this.birthPlace2 = birthPlace2;
    }

    
    @Column(name="PersonId", nullable=false, length=20)
    public String getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(String personId) {
        this.personId = personId;
    }

    
    @Column(name="PassportNo", nullable=false, length=15)
    public String getPassportNo() {
        return this.passportNo;
    }
    
    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }

    
    @Column(name="IssueDate", nullable=false, length=10)
    public String getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(String issueDate) {
        this.issueDate = issueDate;
    }

    
    @Column(name="ExitExpiryDate", nullable=false, length=10)
    public String getExitExpiryDate() {
        return this.exitExpiryDate;
    }
    
    public void setExitExpiryDate(String exitExpiryDate) {
        this.exitExpiryDate = exitExpiryDate;
    }

    
    @Column(name="EntryExpiryDate", nullable=false, length=10)
    public String getEntryExpiryDate() {
        return this.entryExpiryDate;
    }
    
    public void setEntryExpiryDate(String entryExpiryDate) {
        this.entryExpiryDate = entryExpiryDate;
    }

    
    @Column(name="MilitaryMark", nullable=false, length=1)
    public String getMilitaryMark() {
        return this.militaryMark;
    }
    
    public void setMilitaryMark(String militaryMark) {
        this.militaryMark = militaryMark;
    }

    
    @Column(name="Position", nullable=false, precision=5, scale=0)
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }

    
    @Column(name="CommieMark", nullable=false, length=1)
    public String getCommieMark() {
        return this.commieMark;
    }
    
    public void setCommieMark(String commieMark) {
        this.commieMark = commieMark;
    }

    
    @Column(name="PathNoInd", nullable=false, precision=7, scale=0)
    public Integer getPathNoInd() {
        return this.pathNoInd;
    }
    
    public void setPathNoInd(Integer pathNoInd) {
        this.pathNoInd = pathNoInd;
    }

    
    @Column(name="EntryDate", nullable=false, length=8)
    public String getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(String entryDate) {
        this.entryDate = entryDate;
    }

    
    @Column(name="ExitDate", nullable=false, length=8)
    public String getExitDate() {
        return this.exitDate;
    }
    
    public void setExitDate(String exitDate) {
        this.exitDate = exitDate;
    }

    
    @Column(name="EntryCnt", length=1)
    public String getEntryCnt() {
        return this.entryCnt;
    }
    
    public void setEntryCnt(String entryCnt) {
        this.entryCnt = entryCnt;
    }

    
    @Column(name="TourGroupId", length=10)
    public String getTourGroupId() {
        return this.tourGroupId;
    }
    
    public void setTourGroupId(String tourGroupId) {
        this.tourGroupId = tourGroupId;
    }

    
    @Column(name="InterviewMark", nullable=false, length=1)
    public String getInterviewMark() {
        return this.interviewMark;
    }
    
    public void setInterviewMark(String interviewMark) {
        this.interviewMark = interviewMark;
    }

    
    @Column(name="Reason", nullable=false, precision=3, scale=0)
    public Integer getReason() {
        return this.reason;
    }
    
    public void setReason(Integer reason) {
        this.reason = reason;
    }

    
    @Column(name="FirstRecvNo", nullable=false, length=12)
    public String getFirstRecvNo() {
        return this.firstRecvNo;
    }
    
    public void setFirstRecvNo(String firstRecvNo) {
        this.firstRecvNo = firstRecvNo;
    }

    
    @Column(name="OrigName", nullable=false, length=80)
    public String getOrigName() {
        return this.origName;
    }
    
    public void setOrigName(String origName) {
        this.origName = origName;
    }

    
    @Column(name="DeadMark", nullable=false, length=1)
    public String getDeadMark() {
        return this.deadMark;
    }
    
    public void setDeadMark(String deadMark) {
        this.deadMark = deadMark;
    }

    
    @Column(name="AddrType", nullable=false, length=1)
    public String getAddrType() {
        return this.addrType;
    }
    
    public void setAddrType(String addrType) {
        this.addrType = addrType;
    }

    
    @Column(name="ZipCode", nullable=false, precision=5, scale=0)
    public Integer getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(Integer zipCode) {
        this.zipCode = zipCode;
    }

    
    @Column(name="Addr1", nullable=false, length=16)
    public String getAddr1() {
        return this.addr1;
    }
    
    public void setAddr1(String addr1) {
        this.addr1 = addr1;
    }

    
    @Column(name="Addr2", nullable=false, length=4)
    public String getAddr2() {
        return this.addr2;
    }
    
    public void setAddr2(String addr2) {
        this.addr2 = addr2;
    }

    
    @Column(name="Addr3", nullable=false, length=4)
    public String getAddr3() {
        return this.addr3;
    }
    
    public void setAddr3(String addr3) {
        this.addr3 = addr3;
    }

    
    @Column(name="Addr4", nullable=false, length=100)
    public String getAddr4() {
        return this.addr4;
    }
    
    public void setAddr4(String addr4) {
        this.addr4 = addr4;
    }

    
    @Column(name="FollowMark", length=3)
    public String getFollowMark() {
        return this.followMark;
    }
    
    public void setFollowMark(String followMark) {
        this.followMark = followMark;
    }

    
    @Column(name="SittingDate", length=8)
    public String getSittingDate() {
        return this.sittingDate;
    }
    
    public void setSittingDate(String sittingDate) {
        this.sittingDate = sittingDate;
    }

    
    @Column(name="AutoPassMark", length=1)
    public String getAutoPassMark() {
        return this.autoPassMark;
    }
    
    public void setAutoPassMark(String autoPassMark) {
        this.autoPassMark = autoPassMark;
    }

    
    @Column(name="EpassportMark", length=1)
    public String getEpassportMark() {
        return this.epassportMark;
    }
    
    public void setEpassportMark(String epassportMark) {
        this.epassportMark = epassportMark;
    }

    
    @Column(name="Reserved", length=30)
    public String getReserved() {
        return this.reserved;
    }
    
    public void setReserved(String reserved) {
        this.reserved = reserved;
    }

    
    @Column(name="AllowImmigTimes", precision=3, scale=0)
    public Integer getAllowImmigTimes() {
        return this.allowImmigTimes;
    }
    
    public void setAllowImmigTimes(Integer allowImmigTimes) {
        this.allowImmigTimes = allowImmigTimes;
    }

    
    @Column(name="ImmigTimes", precision=3, scale=0)
    public Integer getImmigTimes() {
        return this.immigTimes;
    }
    
    public void setImmigTimes(Integer immigTimes) {
        this.immigTimes = immigTimes;
    }

    
    @Column(name="Certificate", length=512)
    public String getCertificate() {
        return this.certificate;
    }
    
    public void setCertificate(String certificate) {
        this.certificate = certificate;
    }

    
    @Column(name="RevokeMark", length=1)
    public String getRevokeMark() {
        return this.revokeMark;
    }
    
    public void setRevokeMark(String revokeMark) {
        this.revokeMark = revokeMark;
    }

    
    @Column(name="RevokeReason", length=30)
    public String getRevokeReason() {
        return this.revokeReason;
    }
    
    public void setRevokeReason(String revokeReason) {
        this.revokeReason = revokeReason;
    }

    
    @Column(name="Comment", length=512)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    
    @Column(name="WriteBackFlag", nullable=false, length=1)
    public String getWriteBackFlag() {
        return this.writeBackFlag;
    }
    
    public void setWriteBackFlag(String writeBackFlag) {
        this.writeBackFlag = writeBackFlag;
    }

    
    @Column(name="WriteBackRcode", nullable=false, length=4)
    public String getWriteBackRcode() {
        return this.writeBackRcode;
    }
    
    public void setWriteBackRcode(String writeBackRcode) {
        this.writeBackRcode = writeBackRcode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="WriteBackTime", length=23)
    public Date getWriteBackTime() {
        return this.writeBackTime;
    }
    
    public void setWriteBackTime(Date writeBackTime) {
        this.writeBackTime = writeBackTime;
    }

    
    @Column(name="TxnMark", precision=1, scale=0)
    public Integer getTxnMark() {
        return this.txnMark;
    }
    
    public void setTxnMark(Integer txnMark) {
        this.txnMark = txnMark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SyncTime", length=23)
    public Date getSyncTime() {
        return this.syncTime;
    }
    
    public void setSyncTime(Date syncTime) {
        this.syncTime = syncTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EstablishTime", length=23)
    public Date getEstablishTime() {
        return this.establishTime;
    }
    
    public void setEstablishTime(Date establishTime) {
        this.establishTime = establishTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ImportTime", length=23)
    public Date getImportTime() {
        return this.importTime;
    }
    
    public void setImportTime(Date importTime) {
        this.importTime = importTime;
    }

    
    @Column(name="DeleteFlag", nullable=false, length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    
    @Column(name="MainUserId", nullable=false, length=10)
    public String getMainUserId() {
        return this.mainUserId;
    }
    
    public void setMainUserId(String mainUserId) {
        this.mainUserId = mainUserId;
    }

    
    @Column(name="MaintainProgramId", nullable=false, length=10)
    public String getMaintainProgramId() {
        return this.maintainProgramId;
    }
    
    public void setMaintainProgramId(String maintainProgramId) {
        this.maintainProgramId = maintainProgramId;
    }

    
    @Column(name="MaintainHost", nullable=false, length=2)
    public String getMaintainHost() {
        return this.maintainHost;
    }
    
    public void setMaintainHost(String maintainHost) {
        this.maintainHost = maintainHost;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdateTime", nullable=false, length=23)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    
    @Column(name="InspectTermNo", precision=4, scale=0)
    public Integer getInspectTermNo() {
        return this.inspectTermNo;
    }
    
    public void setInspectTermNo(Integer inspectTermNo) {
        this.inspectTermNo = inspectTermNo;
    }

    
    @Column(name="InspectTermLoc", length=2)
    public String getInspectTermLoc() {
        return this.inspectTermLoc;
    }
    
    public void setInspectTermLoc(String inspectTermLoc) {
        this.inspectTermLoc = inspectTermLoc;
    }

    
    @Column(name="PermitDocType", length=1)
    public String getPermitDocType() {
        return this.permitDocType;
    }
    
    public void setPermitDocType(String permitDocType) {
        this.permitDocType = permitDocType;
    }

    
    @Column(name="ApplyType", length=1)
    public String getApplyType() {
        return this.applyType;
    }
    
    public void setApplyType(String applyType) {
        this.applyType = applyType;
    }

    
    @Column(name="ApplyRemark", length=1)
    public String getApplyRemark() {
        return this.applyRemark;
    }
    
    public void setApplyRemark(String applyRemark) {
        this.applyRemark = applyRemark;
    }

    
    @Column(name="TrimEngName", length=50)
    public String getTrimEngName() {
        return this.trimEngName;
    }
    
    public void setTrimEngName(String trimEngName) {
        this.trimEngName = trimEngName;
    }

    
    @Column(name="StayDays", length=3)
    public String getStayDays() {
        return this.stayDays;
    }
    
    public void setStayDays(String stayDays) {
        this.stayDays = stayDays;
    }

    
    @Column(name="CruisesOrder", length=1)
    public String getCruisesOrder() {
        return this.cruisesOrder;
    }
    
    public void setCruisesOrder(String cruisesOrder) {
        this.cruisesOrder = cruisesOrder;
    }

    
    @Column(name="ReferencePermitNo", length=12)
    public String getReferencePermitNo() {
        return this.referencePermitNo;
    }
    
    public void setReferencePermitNo(String referencePermitNo) {
        this.referencePermitNo = referencePermitNo;
    }

    
    @Column(name="LastestExchangeDate", length=8)
    public String getLastestExchangeDate() {
        return this.lastestExchangeDate;
    }
    
    public void setLastestExchangeDate(String lastestExchangeDate) {
        this.lastestExchangeDate = lastestExchangeDate;
    }




}


